/**
 * 与命令及其实现相关的类
 *
 *
 * Classes relevant to command and their implementations.
 */
package org.chorus.command

import org.chorus.camera.data.CameraPreset.Companion.presets
import org.chorus.camera.instruction.impl.ClearInstruction.get
import org.chorus.camera.data.CameraPreset.Companion.getPreset
import org.chorus.command.data.CommandEnum
import org.chorus.command.data.CommandOverload
import java.util.HashMap
import java.util.EnumSet
import org.chorus.command.data.ChainedSubCommandData
import org.chorus.command.data.CommandData
import org.chorus.network.protocol.UpdateSoftEnumPacket
import org.chorus.camera.data.CameraPreset
import org.chorus.command.data.CommandParameter
import org.chorus.command.data.CommandInput
import org.chorus.command.data.CommandParamType
import org.chorus.command.tree.node.IParamNode
import org.chorus.command.data.CommandParamOption
import org.chorus.network.protocol.AvailableCommandsPacket
import org.chorus.command.data.GenericParameter.CommandParameterSupplier
import org.chorus.command.tree.node.ItemNode
import org.chorus.command.tree.node.ChainedCommandNode
import org.chorus.command.tree.node.ParamNode
import org.chorus.command.tree.ParamList
import org.chorus.lang.CommandOutputContainer
import org.chorus.network.protocol.types.CommandOutputMessage
import org.chorus.command.tree.node.TargetNode
import org.chorus.command.selector.EntitySelectorAPI
import org.chorus.command.exceptions.SelectorSyntaxException
import org.chorus.IPlayer
import org.chorus.command.tree.node.StringNode
import org.chorus.command.tree.node.IPStringNode
import org.chorus.math.BVector3
import org.chorus.block.BlockProperties
import org.chorus.block.property.type.BlockPropertyType
import org.chorus.command.tree.node.PositionNode
import org.chorus.command.tree.node.RelativeNumberNode
import org.chorus.command.tree.node.EnumNode
import java.util.HashSet
import org.chorus.command.tree.node.OperatorStringNode
import org.chorus.command.tree.node.CompareOperatorStringNode
import org.chorus.command.tree.node.WildcardIntNode
import org.chorus.command.tree.node.EntitiesNode
import org.chorus.command.tree.node.WildcardTargetStringNode
import org.chorus.command.tree.node.CommandNode
import org.chorus.command.tree.node.MessageStringNode
import org.chorus.command.tree.node.RemainStringNode
import org.chorus.command.tree.node.RawTextNode
import org.chorus.command.tree.node.BlockStateNode
import java.util.function.ToIntFunction
import org.chorus.command.utils.CommandLogger
import org.chorus.command.PluginCommand
import org.chorus.plugin.InternalPlugin
import org.chorus.utils.JSONUtils
import org.chorus.command.utils.RawText.Component.ScoreComponent

import org.chorus.scoreboard.IScoreboard
import org.chorus.scoreboard.scorer.IScorer
import org.chorus.scoreboard.scorer.PlayerScorer
import org.chorus.scoreboard.scorer.EntityScorer
import org.chorus.scoreboard.scorer.FakeScorer
import org.chorus.plugin.PluginBase
import org.chorus.lang.PluginI18n
import org.chorus.lang.PluginI18nManager
import org.chorus.command.ConsoleCommandSender
import org.chorus.level.GameRule
import org.chorus.lang.TranslationContainer
import org.chorus.command.ExecutorCommandSender
import org.chorus.blockentity.ICommandBlock
import org.chorus.permission.Permissible
import org.chorus.command.simple.SimpleCommand
import org.chorus.command.defaults.VanillaCommand
import org.chorus.command.tree.node.IPlayersNode
import org.chorus.inventory.fake.FakeStructBlock
import org.chorus.command.tree.node.PlayersNode
import org.chorus.command.tree.node.XpLevelNode
import org.chorus.event.player.PlayerKickEvent
import org.chorus.network.protocol.PlayerFogPacket
import java.util.concurrent.atomic.AtomicInteger
import org.chorus.network.protocol.types.hud.HudVisibility
import org.chorus.network.protocol.types.hud.HudElement
import org.chorus.network.protocol.SetHudPacket
import org.chorus.nbt.tag.StringTag
import org.chorus.command.defaults.CoreCommand
import org.chorus.command.defaults.TpsCommand.TpsTestTask
import org.chorus.command.defaults.FillCommand.FillMode
import org.chorus.math.AxisAlignedBB
import org.chorus.math.SimpleAxisAlignedBB
import org.chorus.math.NukkitMath
import org.chorus.level.generator.``object`

