/**
 * 与命令及其实现相关的类
 *
 *
 * Classes relevant to command and their implementations.
 */
package org.chorus.command

import cn.nukkit.camera.data.CameraPreset.Companion.presets
import cn.nukkit.camera.instruction.impl.ClearInstruction.get
import cn.nukkit.camera.data.CameraPreset.Companion.getPreset
import cn.nukkit.command.data.CommandEnum
import cn.nukkit.command.data.CommandOverload
import java.util.HashMap
import java.util.EnumSet
import cn.nukkit.command.data.ChainedSubCommandData
import cn.nukkit.command.data.CommandData
import cn.nukkit.network.protocol.UpdateSoftEnumPacket
import cn.nukkit.camera.data.CameraPreset
import cn.nukkit.command.data.CommandParameter
import cn.nukkit.command.data.CommandInput
import cn.nukkit.command.data.CommandParamType
import cn.nukkit.command.tree.node.IParamNode
import cn.nukkit.command.data.CommandParamOption
import cn.nukkit.network.protocol.AvailableCommandsPacket
import cn.nukkit.command.data.GenericParameter.CommandParameterSupplier
import cn.nukkit.command.tree.node.ItemNode
import cn.nukkit.command.tree.node.ChainedCommandNode
import cn.nukkit.command.tree.node.ParamNode
import cn.nukkit.command.tree.ParamList
import cn.nukkit.lang.CommandOutputContainer
import cn.nukkit.network.protocol.types.CommandOutputMessage
import cn.nukkit.command.tree.node.TargetNode
import cn.nukkit.command.selector.EntitySelectorAPI
import cn.nukkit.command.exceptions.SelectorSyntaxException
import cn.nukkit.IPlayer
import cn.nukkit.command.tree.node.StringNode
import cn.nukkit.command.tree.node.IPStringNode
import cn.nukkit.math.BVector3
import cn.nukkit.block.BlockProperties
import cn.nukkit.block.property.type.BlockPropertyType
import cn.nukkit.command.tree.node.PositionNode
import cn.nukkit.command.tree.node.RelativeNumberNode
import cn.nukkit.command.tree.node.EnumNode
import java.util.HashSet
import cn.nukkit.command.tree.node.OperatorStringNode
import cn.nukkit.command.tree.node.CompareOperatorStringNode
import cn.nukkit.command.tree.node.WildcardIntNode
import cn.nukkit.command.tree.node.EntitiesNode
import cn.nukkit.command.tree.node.WildcardTargetStringNode
import cn.nukkit.command.tree.node.CommandNode
import cn.nukkit.command.tree.node.MessageStringNode
import cn.nukkit.command.tree.node.RemainStringNode
import cn.nukkit.command.tree.node.RawTextNode
import cn.nukkit.command.tree.node.BlockStateNode
import java.util.function.ToIntFunction
import cn.nukkit.command.utils.CommandLogger
import cn.nukkit.command.PluginCommand
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.utils.JSONUtils
import org.chorus.command.utils.RawText.Component.ScoreComponent
import lombok.SneakyThrows
import cn.nukkit.scoreboard.IScoreboard
import cn.nukkit.scoreboard.scorer.IScorer
import cn.nukkit.scoreboard.scorer.PlayerScorer
import cn.nukkit.scoreboard.scorer.EntityScorer
import cn.nukkit.scoreboard.scorer.FakeScorer
import cn.nukkit.plugin.PluginBase
import cn.nukkit.lang.PluginI18n
import cn.nukkit.lang.PluginI18nManager
import cn.nukkit.command.ConsoleCommandSender
import cn.nukkit.level.GameRule
import cn.nukkit.lang.TranslationContainer
import cn.nukkit.command.ExecutorCommandSender
import cn.nukkit.blockentity.ICommandBlock
import cn.nukkit.permission.Permissible
import cn.nukkit.command.simple.SimpleCommand
import cn.nukkit.command.defaults.VanillaCommand
import cn.nukkit.command.tree.node.IPlayersNode
import cn.nukkit.inventory.fake.FakeStructBlock
import cn.nukkit.command.tree.node.PlayersNode
import cn.nukkit.command.tree.node.XpLevelNode
import cn.nukkit.event.player.PlayerKickEvent
import cn.nukkit.network.protocol.PlayerFogPacket
import java.util.concurrent.atomic.AtomicInteger
import cn.nukkit.network.protocol.types.hud.HudVisibility
import cn.nukkit.network.protocol.types.hud.HudElement
import cn.nukkit.network.protocol.SetHudPacket
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.command.defaults.CoreCommand
import cn.nukkit.command.defaults.TpsCommand.TpsTestTask
import cn.nukkit.command.defaults.FillCommand.FillMode
import cn.nukkit.math.AxisAlignedBB
import cn.nukkit.math.SimpleAxisAlignedBB
import cn.nukkit.math.NukkitMath
import cn.nukkit.level.generator.``object`

