/* Generated by: JavaCC 21 Parser Generator. Do not edit.
 * Generated Code for ByteArrayNBT AST Node type
 * by the ASTNode.java.ftl template
 */
package org.chorus.nbt.snbt.ast

import org.chorus.nbt.snbt.BaseNode

class ByteArrayNBT : BaseNode()


