/* Generated by: JavaCC 21 Parser Generator. Do not edit.
 * Generated Code for Literal Token subclass
 * by the ASTToken.java.ftl template
 */
package org.chorus.nbt.snbt.ast

import cn.nukkit.nbt.snbt.SNBTConstants
import cn.nukkit.nbt.snbt.SNBTLexer
import cn.nukkit.nbt.snbt.Token

class Literal(type: SNBTConstants.TokenType?, tokenSource: SNBTLexer?, beginOffset: Int, endOffset: Int) :
    Token(type, tokenSource, beginOffset, endOffset)


