/* Generated by: JavaCC 21 Parser Generator. Do not edit.
 * Generated Code for Root AST Node type
 * by the ASTNode.java.ftl template
 */
package org.chorus.nbt.snbt.ast

import cn.nukkit.nbt.snbt.BaseNode

class Root : BaseNode()


