/**
 * 与实体相关的类,包含友好生物,敌对生物等.
 *
 *
 * Classes relevant to entity,
 * Including friendly creatures, hostile creatures, etc.
 */
package org.chorus.entity

import org.chorus.blockentity.BlockEntityBeehive.isHoneyFull
import org.chorus.blockentity.BlockEntityBeehive.occupantsCount
import org.chorus.blockentity.BlockEntityBeehive.addOccupant
import org.chorus.blockentity.BlockEntityCreakingHeart.setLinkedCreaking
import org.chorus.blockentity.BlockEntityCreakingHeart.isBlockEntityValid
import org.chorus.blockentity.BlockEntityCreakingHeart.heart
import org.chorus.dialog.window.FormWindowDialog.buttonJSONData
import org.chorus.dialog.window.FormWindowDialog.addHandler
import org.chorus.dialog.element.ElementDialogButton.getData
import org.chorus.dialog.window.FormWindowDialog.getButtons
import org.chorus.dialog.element.ElementDialogButton.getMode
import org.chorus.entity.ai.route.posevaluator.IPosEvaluator
import org.chorus.entity.mob.EntityMob
import org.chorus.entity.ai.route.finder.SimpleRouteFinder
import java.util.HashSet
import org.chorus.entity.ai.EntityAI
import org.chorus.level.particle.BlockForceFieldParticle
import org.chorus.entity.ai.route.finder.impl.SimpleFlatAStarRouteFinder
import org.chorus.math.VectorMath
import org.chorus.entity.ai.route.finder.IRouteFinder
import org.chorus.entity.ai.route.finder.impl.SimpleSpaceAStarRouteFinder
import java.util.concurrent.locks.ReentrantReadWriteLock
import org.chorus.math.AxisAlignedBB
import org.chorus.math.SimpleAxisAlignedBB
import org.chorus.block.BlockFence
import org.chorus.block.BlockFenceGate
import java.util.concurrent.ForkJoinPool
import org.chorus.entity.ai.route.RouteFindingManager.RouteFindingPoolThreadFactory
import org.chorus.entity.ai.route.RouteFindingManager.RouteFindingTask
import java.util.concurrent.ForkJoinWorkerThread
import org.chorus.entity.ai.route.RouteFindingManager
import java.util.concurrent.ForkJoinPool.ForkJoinWorkerThreadFactory
import java.security.AccessController
import java.security.PrivilegedAction
import org.chorus.entity.ai.route.RouteFindingManager.RouteFindingThread
import java.security.AccessControlContext
import org.chorus.entity.ai.route.RouteFindingManager.RouteFindingTask.FinishCallback
import java.util.concurrent.RecursiveAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import org.chorus.nbt.tag.CompoundTag
import org.chorus.entity.ai.memory.codec.IMemoryCodec
import org.chorus.entity.ai.memory.codec.MemoryCodec
import org.chorus.entity.ai.memory.codec.NumberMemoryCodec.TagReader
import org.chorus.nbt.tag.NumberTag
import org.chorus.entity.ai.memory.codec.NumberMemoryCodec
import org.chorus.nbt.tag.ByteTag
import org.chorus.nbt.tag.ShortTag
import org.chorus.nbt.tag.IntTag
import org.chorus.nbt.tag.LongTag
import org.chorus.nbt.tag.FloatTag
import org.chorus.nbt.tag.DoubleTag
import org.chorus.entity.ai.memory.IMemoryStorage
import java.util.concurrent.ConcurrentHashMap
import org.chorus.entity.ai.memory.MemoryStorage
import java.util.HashMap
import org.chorus.event.entity.EntityDamageEvent
import org.chorus.entity.mob.monster.humanoid_monster.EntityEvocationIllager.SPELL
import org.chorus.math.BlockVector3
import org.chorus.block.BlockBed
import org.chorus.block.BlockWoodenDoor
import org.chorus.entity.item.EntityItem
import org.chorus.entity.mob.villagers.EntityVillagerV2
import org.chorus.entity.ai.memory.codec.BooleanMemoryCodec
import org.chorus.entity.data.EntityFlag
import org.chorus.entity.ai.memory.codec.StringMemoryCodec
import org.chorus.entity.data.EntityDataTypes
import org.chorus.entity.ai.sensor.ISensor
import org.chorus.entity.ai.memory.CoreMemoryTypes
import org.chorus.entity.mob.animal.EntityAnimal
import org.chorus.entity.EntityOwnable
import org.chorus.inventory.ChestInventory
import org.chorus.inventory.DoubleChestInventory
import org.chorus.inventory.HumanEnderChestInventory
import org.chorus.inventory.ShulkerBoxInventory
import org.chorus.inventory.BarrelInventory
import org.chorus.inventory.MinecartChestInventory
import org.chorus.inventory.ChestBoatInventory
import org.chorus.entity.ai.sensor.NearestFeedingPlayerSensor
import org.chorus.entity.ai.executor.IBehaviorExecutor
import org.chorus.entity.ai.evaluator.IBehaviorEvaluator
import org.chorus.entity.ai.behavior.AbstractBehavior
import org.chorus.entity.ai.behavior.BehaviorState
import org.chorus.entity.ai.behavior.IBehavior
import org.chorus.entity.ai.executor.EntityControl
import org.chorus.entity.ai.executor.NearbyFlatRandomRoamExecutor
import org.chorus.entity.data.profession.Profession
import org.chorus.block.BlockCrops
import org.chorus.math.BlockFace
import org.chorus.math.BVector3
import lombok.RequiredArgsConstructor
import org.chorus.item.ItemFood
import org.chorus.entity.ai.executor.EntityBreedingExecutor
import org.chorus.network.protocol.EntityEventPacket
import org.chorus.entity.ai.executor.armadillo.PeekExecutor
import org.chorus.entity.mob.animal.EntityArmadillo
import org.chorus.entity.mob.animal.EntityArmadillo.RollupEvaluator
import org.chorus.entity.mob.animal.EntityArmadillo.RollState
import org.chorus.level.Sound
import org.chorus.entity.ai.executor.armadillo.RollUpExecutor
import org.chorus.entity.ai.executor.armadillo.UnrollingExecutor
import org.chorus.entity.ai.executor.evocation.FangLineExecutor
import org.chorus.entity.EntityLiving
import org.chorus.utils.BlockColor
import org.chorus.entity.mob.monster.humanoid_monster.EntityEvocationIllager
import org.chorus.nbt.tag.ListTag
import org.chorus.entity.EntityID
import org.chorus.entity.mob.monster.EntityEvocationFang
import org.chorus.entity.ai.executor.evocation.VexSummonExecutor
import org.chorus.entity.mob.monster.EntityVex
import org.chorus.entity.ai.executor.evocation.FangCircleExecutor
import org.chorus.entity.ai.executor.evocation.ColorConversionExecutor
import org.chorus.entity.mob.animal.EntitySheep
import org.chorus.utils.DyeColor
import org.chorus.entity.item.EntityAreaEffectCloud
import org.chorus.entity.mob.monster.EntityEnderDragon
import org.chorus.entity.item.EntityEnderCrystal
import lombok.AllArgsConstructor
import org.chorus.item.ItemBow
import org.chorus.entity.projectile.abstract_arrow.EntityArrow
import org.chorus.event.entity.EntityShootBowEvent
import org.chorus.entity.projectile.EntityProjectile
import org.chorus.item.enchantment.bow.EnchantmentBow
import org.chorus.event.entity.ProjectileLaunchEvent
import org.chorus.level.particle.DestroyBlockParticle
import org.chorus.block.BlockID
import org.chorus.level.GameRule
import org.chorus.entity.ai.executor.MultipleExecutor
import org.chorus.entity.ai.executor.MeleeAttackExecutor
import org.chorus.entity.mob.animal.EntityBee
import org.chorus.entity.ai.executor.FlatRandomRoamExecutor
import org.chorus.entity.mob.animal.EntityHorse
import org.chorus.plugin.InternalPlugin
import org.chorus.entity.mob.monster.EntityMonster
import org.chorus.item.ItemPotion
import org.chorus.block.BlockMagma
import org.chorus.event.entity.EntityDamageByEntityEvent
import org.chorus.entity.projectile.EntitySmallFireball
import org.chorus.network.protocol.LevelEventPacket
import org.chorus.entity.projectile.EntityFireball
import org.chorus.math.IVector3
import org.chorus.entity.ai.executor.MoveToTargetExecutor
import org.chorus.entity.mob.animal.EntityWolf
import org.chorus.entity.projectile.EntityBreezeWindCharge
import org.chorus.inventory.EntityInventoryHolder
import org.chorus.entity.EntityCanAttack
import org.chorus.event.entity.EntityDamageEvent.DamageModifier
import org.chorus.item.ItemGoldIngot
import org.chorus.entity.EntityEquipment
import org.chorus.entity.projectile.throwable.EntitySplashPotion
import org.chorus.entity.mob.EntityShulker
import org.chorus.entity.mob.monster.EntityWarden
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident
import org.chorus.item.ItemCrossbow
import org.chorus.entity.mob.monster.EntityEnderman
import org.chorus.block.Natural
import org.chorus.entity.projectile.EntityShulkerBullet
import org.chorus.entity.ai.evaluator.AllMatchEvaluator
import org.chorus.entity.ai.evaluator.EntityCheckEvaluator
import org.chorus.entity.ai.evaluator.DistanceEvaluator
import org.chorus.entity.ai.evaluator.NotMatchEvaluator
import org.chorus.entity.ai.evaluator.PassByTimeEvaluator
import org.chorus.network.protocol.LevelSoundEventPacketV2
import org.chorus.entity.projectile.throwable.EntitySnowball
import org.chorus.event.entity.EntityExplosionPrimeEvent
import org.chorus.entity.mob.monster.EntityCreeper
import org.chorus.level.Explosion
import org.chorus.level.particle.HugeExplodeSeedParticle
import org.chorus.entity.mob.EntityZoglin
import org.chorus.entity.mob.monster.humanoid_monster.EntityZombiePigman
import org.chorus.network.protocol.LevelEventGenericPacket
import org.chorus.math.Vector3f
import org.chorus.entity.ai.evaluator.AnyMatchEvaluator
import org.chorus.entity.ai.evaluator.MultiBehaviorEvaluator
import org.chorus.entity.ai.evaluator.ProbabilityEvaluator
import org.chorus.entity.ai.controller.IController
import org.chorus.block.BlockCarpet
import org.chorus.entity.ai.controller.WalkController
import org.chorus.entity.EntityPhysical
import org.chorus.block.BlockLiquid
import org.chorus.entity.mob.animal.EntityRabbit
import org.chorus.entity.mob.monster.EntitySlime
import org.chorus.entity.ai.behaviorgroup.IBehaviorGroup
import org.chorus.entity.ai.behavior.Behavior
import org.chorus.entity.ai.behaviorgroup.BehaviorGroup
import org.chorus.entity.ai.behaviorgroup.BehaviorGroup.ChunkSectionVector
import org.chorus.level.format.IChunk
import org.chorus.level.DimensionData
import java.util.EnumSet
import org.chorus.entity.EntityFlyable
import org.chorus.entity.ai.executor.BeeAttackExecutor
import org.chorus.entity.ai.evaluator.MemoryCheckNotEmptyEvaluator
import org.chorus.entity.ai.executor.SpaceRandomRoamExecutor
import org.chorus.entity.ai.sensor.MemorizedBlockSensor
import org.chorus.entity.ai.controller.SpaceMoveController
import org.chorus.entity.ai.controller.LiftController
import org.chorus.entity.ai.route.posevaluator.FlyingPosEvaluator
import org.chorus.block.BlockBeehive
import org.chorus.block.BlockFlower
import org.chorus.block.BlockWitherRose
import org.chorus.blockentity.BlockEntityBeehive
import org.chorus.entity.EntityWalkable
import org.chorus.entity.EntityCanSit
import org.chorus.entity.EntityHealable
import org.chorus.entity.EntityVariant
import org.chorus.entity.EntityColor
import org.chorus.entity.ai.executor.InLoveExecutor
import org.chorus.entity.ai.executor.SleepOnOwnerBedExecutor
import org.chorus.entity.mob.animal.EntityCat
import org.chorus.entity.ai.executor.EntityMoveToOwnerExecutor
import org.chorus.entity.ai.executor.LookAtFeedingPlayerExecutor
import org.chorus.entity.ai.executor.LookAtTargetExecutor
import org.chorus.entity.ai.evaluator.ConditionalProbabilityEvaluator
import org.chorus.entity.ai.sensor.NearestPlayerSensor
import org.chorus.entity.ai.sensor.NearestTargetEntitySensor
import org.chorus.entity.ai.controller.FluctuateController
import org.chorus.entity.ai.route.posevaluator.WalkingPosEvaluator
import org.chorus.network.protocol.LevelSoundEventPacket
import org.chorus.level.particle.ItemBreakParticle
import org.chorus.item.ItemDye
import org.chorus.item.ItemID
import org.chorus.entity.mob.animal.EntityCow
import org.chorus.entity.mob.animal.EntityFox
import org.chorus.entity.ai.executor.AnimalGrowExecutor
import org.chorus.entity.mob.animal.EntityPig
import org.chorus.entity.mob.animal.EntityFrog
import org.chorus.entity.ai.controller.HoppingController
import org.chorus.entity.EntityAngryable
import org.chorus.entity.ai.executor.WolfAttackExecutor
import org.chorus.entity.ai.sensor.WolfNearestFeedingPlayerSensor
import org.chorus.entity.ai.sensor.EntityAttackedByOwnerSensor
import org.chorus.entity.mob.animal.EntityCamel
import org.chorus.entity.EntityMarkVariant
import org.chorus.entity.EntityRideable
import org.chorus.inventory.HorseInventory
import org.chorus.nbt.NBTIO
import org.chorus.network.protocol.UpdateAttributesPacket
import org.chorus.entity.ai.executor.TameHorseExecutor
import org.chorus.event.entity.EntityFallEvent
import org.chorus.event.block.FarmLandDecayEvent
import org.chorus.block.BlockDirt
import org.chorus.block.BlockTurtleEgg
import org.chorus.network.protocol.types.EntityLink
import org.chorus.network.protocol.DataPacket
import org.chorus.network.protocol.AddEntityPacket
import org.chorus.entity.custom.CustomEntity
import org.chorus.entity.mob.animal.EntityPanda
import org.chorus.entity.EntityShearable
import org.chorus.entity.ai.executor.EatGrassExecutor
import org.chorus.entity.ai.evaluator.BlockCheckEvaluator
import org.chorus.level.vibration.VibrationType
import org.chorus.entity.mob.animal.EntityDonkey
import org.chorus.entity.EntitySwimmable
import org.chorus.entity.ai.controller.DiveController
import org.chorus.entity.ai.executor.PlaySoundExecutor
import org.chorus.entity.ai.evaluator.RandomSoundEvaluator
import org.chorus.entity.mob.animal.EntityAxolotl
import org.chorus.entity.ai.sensor.BlockSensor
import org.chorus.block.BlockFlowingWater
import org.chorus.entity.ai.controller.ConditionalController
import org.chorus.entity.ai.route.finder.impl.ConditionalAStarRouteFinder
import org.chorus.entity.ai.route.posevaluator.SwimmingPosEvaluator
import org.chorus.entity.mob.animal.EntityChicken
import org.chorus.entity.mob.animal.EntitySniffer
import org.chorus.entity.ai.executor.armadillo.RelaxingExecutor
import org.chorus.entity.ai.executor.armadillo.ShedExecutor
import org.chorus.item.ItemBrush
import org.chorus.entity.mob.animal.EntityMooshroom
import org.chorus.level.ParticleEffect
import org.chorus.entity.mob.animal.EntityLlama
import org.chorus.entity.EntitySmite
import org.chorus.entity.mob.monster.EntityVex.VexMeleeAttackExecutor
import org.chorus.entity.mob.villagers.EntityVillager
import org.chorus.item.ItemTool
import org.chorus.network.protocol.BossEventPacket
import org.chorus.entity.ai.executor.BlazeShootExecutor
import org.chorus.event.entity.EntityDamageEvent.DamageCause
import org.chorus.entity.ai.executor.GhastShootExecutor
import org.chorus.entity.mob.EntityGolem
import org.chorus.entity.mob.monster.humanoid_monster.EntityZombie
import org.chorus.entity.ai.executor.JumpExecutor
import org.chorus.entity.mob.monster.humanoid_monster.EntitySkeleton
import org.chorus.entity.mob.monster.humanoid_monster.EntityHumanoidMonster
import org.chorus.entity.ai.executor.UsePotionExecutor
import org.chorus.entity.ai.executor.PotionThrowExecutor
import org.chorus.entity.ai.sensor.NearestEntitySensor
import org.chorus.entity.ai.executor.BowShootExecutor
import org.chorus.entity.ai.executor.PiglinTransformExecutor
import org.chorus.entity.ai.executor.PiglinTradeExecutor
import org.chorus.entity.mob.monster.humanoid_monster.EntityPiglin
import org.chorus.entity.ai.executor.CrossBowShootExecutor
import org.chorus.item.ItemArmor
import org.chorus.entity.mob.monster.humanoid_monster.EntityPiglin.PiglinMeleeAttackExecutor
import org.chorus.entity.mob.monster.humanoid_monster.EntityPiglin.PiglinFleeFromTargetExecutor
import org.chorus.block.BlockSoulFire
import org.chorus.entity.mob.monster.EntityWither
import org.chorus.entity.mob.monster.humanoid_monster.EntityWitherSkeleton
import org.chorus.entity.ai.sensor.NearestPlayerAngryPiglinSensor
import org.chorus.block.BlockDoor
import org.chorus.entity.mob.EntityHoglin
import org.chorus.network.protocol.AnimateEntityPacket.Animation
import org.chorus.network.protocol.AnimateEntityPacket
import org.chorus.item.ItemPorkchop
import org.chorus.network.protocol.TakeItemEntityPacket
import org.chorus.entity.ai.executor.FleeFromTargetExecutor
import org.chorus.entity.ai.executor.NearestBlockIncementExecutor
import org.chorus.entity.mob.monster.humanoid_monster.EntityHusk
import org.chorus.entity.mob.animal.EntityTurtle
import org.chorus.entity.mob.monster.humanoid_monster.EntityDrowned
import org.chorus.entity.ai.executor.TridentThrowExecutor
import org.chorus.item.ItemTrident
import org.chorus.entity.mob.monster.humanoid_monster.EntityIllager
import org.chorus.entity.mob.monster.humanoid_monster.EntityVindicator.VindicatorMeleeAttackExecutor
import org.chorus.item.ItemGoldenApple
import org.chorus.entity.ai.evaluator.MemoryCheckEmptyEvaluator
import org.chorus.entity.ai.executor.DoNothingExecutor
import org.chorus.entity.mob.monster.EntityCreaking
import org.chorus.entity.ai.executor.BreezeShootExecutor
import org.chorus.entity.ai.executor.BreezeJumpExecutor
import org.chorus.entity.EntityArthropod
import org.chorus.level.vibration.VibrationListener
import org.chorus.entity.ai.executor.WardenViolentAnimationExecutor
import org.chorus.entity.ai.executor.WardenRangedAttackExecutor
import org.chorus.entity.ai.executor.WardenMeleeAttackExecutor
import org.chorus.entity.ai.executor.WardenSniffExecutor
import org.chorus.entity.ai.evaluator.RandomTimeRangeEvaluator
import org.chorus.entity.ai.sensor.RouteUnreachableTimeSensor
import org.chorus.math.NukkitMath
import org.chorus.entity.EntityCreature
import org.chorus.entity.mob.monster.EntityBoss
import org.chorus.entity.ai.executor.WitherDashExecutor
import org.chorus.entity.ai.executor.WitherShootExecutor
import org.chorus.block.BlockBedrock
import org.chorus.block.BlockWitherSkeletonSkull
import org.chorus.block.BlockSoulSand
import org.chorus.entity.EntityInteractable
import org.chorus.entity.ai.executor.EntityExplosionExecutor
import org.chorus.entity.mob.animal.EntityOcelot
import org.chorus.entity.weather.EntityLightningStrike
import org.chorus.event.entity.CreeperPowerEvent
import org.chorus.entity.ai.executor.CircleAboveTargetExecutor
import org.chorus.entity.mob.monster.EntityPhantom.PhantomMeleeAttackExecutor
import org.chorus.blockentity.BlockEntityCreakingHeart
import org.chorus.entity.mob.monster.EntityCreaking.PlayerStaringCreakingSensor
import org.chorus.entity.mob.monster.EntityCreaking.NearestPlayerCreakingSensor
import org.chorus.block.BlockCreakingHeart
import org.chorus.block.BlockPaleOakLog
import org.chorus.block.BlockResinClump
import org.chorus.block.property.type.IntPropertyType
import org.chorus.block.property.CommonBlockProperties
import org.chorus.entity.ai.sensor.PlayerStaringSensor
import org.chorus.entity.ai.executor.StaringAttackTargetExecutor
import org.chorus.entity.ai.executor.TeleportExecutor
import org.chorus.entity.ai.executor.EndermanBlockExecutor
import org.chorus.entity.mob.monster.EntityEndermite
import org.chorus.entity.ai.executor.GuardianAttackExecutor
import org.chorus.entity.mob.EntityIronGolem
import org.chorus.entity.mob.monster.EntityMagmaCube
import org.chorus.entity.ai.executor.enderdragon.PerchingExecutor
import org.chorus.entity.ai.executor.enderdragon.StrafeExecutor
import org.chorus.entity.ai.executor.enderdragon.CircleMovementExecutor
import org.chorus.entity.mob.monster.EntityEnderDragon.EnderDragonRouteFinder
import org.chorus.entity.mob.monster.EntityEnderDragon.EnderDragonPosEvaluator
import org.chorus.block.BlockEndGateway
import org.chorus.entity.mob.monster.humanoid_monster.EntityZombieVillager
import org.chorus.utils.TradeRecipeBuildUtils
import org.chorus.inventory.TradeInventory
import org.chorus.inventory.EntityEquipmentInventory
import org.chorus.entity.ai.executor.villager.DoorExecutor
import org.chorus.entity.ai.executor.villager.WillingnessExecutor
import org.chorus.entity.ai.executor.villager.SleepExecutor
import org.chorus.entity.ai.executor.villager.WorkExecutor
import org.chorus.entity.ai.executor.villager.GossipExecutor
import org.chorus.entity.ai.executor.villager.VillagerBreedingExecutor
import org.chorus.utils.random.NukkitRandom
import org.chorus.entity.mob.villagers.EntityVillagerV2.Clothing
import org.chorus.entity.mob.villagers.EntityVillagerV2.Gossip
import org.chorus.network.protocol.UpdateTradePacket
import org.chorus.inventory.InventorySlice
import org.chorus.registry.BiomeRegistry.BiomeDefinition
import org.chorus.entity.mob.water_animal.fish.EntityFish
import org.chorus.entity.mob.water_animal.EntityWaterAnimal
import org.chorus.entity.mob.water_animal.EntityTropicalfish
import org.chorus.entity.ai.evaluator.LogicalUtils
import org.chorus.entity.ai.controller.EntityControlUtils
import kotlin.math.pow
import org.chorus.network.protocol.MoveEntityDeltaPacket
import org.chorus.entity.ai.behaviorgroup.EmptyBehaviorGroup
import org.chorus.form.window.SimpleForm
import org.chorus.dialog.window.FormWindowDialog
import org.chorus.entity.mob.EntityNPC
import org.chorus.nbt.tag.StringTag
import org.chorus.dialog.handler.FormDialogHandler
import org.chorus.dialog.response.FormResponseDialog
import org.chorus.network.protocol.NPCRequestPacket
import org.chorus.dialog.element.ElementDialogButton
import org.chorus.dialog.element.ElementDialogButton.CmdLine
import org.chorus.command.NPCCommandSender
import org.chorus.entity.ai.sensor.NearestItemSensor
import org.chorus.entity.mob.EntityAllay
import org.chorus.entity.ai.executor.HoglinTransformExecutor
import org.chorus.entity.mob.EntityHoglin.HoglinMeleeAttackExecutor
import org.chorus.entity.mob.EntityHoglin.HoglinFleeFromTargetExecutor
import org.chorus.block.BlockPortal
import org.chorus.block.BlockWarpedFungus
import org.chorus.block.BlockRespawnAnchor
import org.chorus.entity.ai.executor.ShulkerIdleExecutor
import org.chorus.entity.ai.executor.ShulkerAttackExecutor
import org.chorus.event.player.PlayerTeleportEvent
import org.chorus.event.player.PlayerTeleportEvent.TeleportCause
import org.chorus.entity.mob.EntitySquid
import org.chorus.item.ItemIronIngot
import org.chorus.block.BlockPumpkin
import org.chorus.block.BlockIronBlock
import org.chorus.entity.ai.executor.SnowGolemShootExecutor
import org.chorus.entity.mob.EntitySnowGolem
import org.chorus.item.ItemShears
import org.chorus.block.BlockSnow
import org.chorus.entity.EntityNameable
import org.chorus.entity.mob.EntityArmorStand
import org.chorus.item.ItemShield
import org.chorus.event.player.PlayerChangeArmorStandEvent
import org.chorus.inventory.BaseInventory
import org.chorus.network.protocol.SetEntityDataPacket
import org.chorus.inventory.EntityArmorInventory
import org.chorus.entity.data.property.EntityProperty
import org.chorus.entity.data.property.IntEntityProperty
import org.chorus.entity.data.property.FloatEntityProperty
import org.chorus.entity.data.property.BooleanEntityProperty
import org.chorus.entity.data.property.EnumEntityProperty
import java.io.IOException
import org.chorus.network.protocol.SyncEntityPropertyPacket
import org.chorus.utils.SkinAnimation
import org.chorus.utils.PersonaPiece
import org.chorus.utils.PersonaPieceTint
import org.chorus.utils.SerializedImage
import java.awt.image.BufferedImage
import org.chorus.entity.data.profession.ProfessionFarmer
import org.chorus.entity.data.profession.ProfessionFisherman
import org.chorus.entity.data.profession.ProfessionShepherd
import org.chorus.entity.data.profession.ProfessionFletcher
import org.chorus.entity.data.profession.ProfessionLibrarian
import org.chorus.entity.data.profession.ProfessionCartographer
import org.chorus.entity.data.profession.ProfessionCleric
import org.chorus.entity.data.profession.ProfessionArmor
import org.chorus.entity.data.profession.ProfessionWeapon
import org.chorus.entity.data.profession.ProfessionTool
import org.chorus.entity.data.profession.ProfessionButcher
import org.chorus.entity.data.profession.ProfessionLeather
import org.chorus.entity.data.profession.ProfessionMason
import java.util.Locale
import org.chorus.item.ItemLeatherChestplate
import org.chorus.item.ItemLeatherLeggings
import org.chorus.item.ItemLeatherHelmet
import org.chorus.item.ItemLeatherBoots
import org.chorus.entity.data.EntityDataType
import org.chorus.entity.data.EntityDataMap
import org.chorus.entity.data.EntityDataFormat
import org.chorus.entity.EntityExplosive
import org.chorus.entity.item.EntityVehicle
import org.chorus.entity.item.EntityBoat
import org.chorus.event.vehicle.VehicleUpdateEvent
import org.chorus.event.vehicle.VehicleMoveEvent
import org.chorus.math.AxisAlignedBB.BBConsumer
import org.chorus.entity.EntityHuman
import org.chorus.network.protocol.AnimatePacket
import org.chorus.event.entity.ItemSpawnEvent
import org.chorus.event.entity.ItemDespawnEvent
import org.chorus.network.protocol.AddItemEntityPacket
import org.chorus.entity.item.EntityXpOrb
import org.chorus.event.vehicle.VehicleDamageByEntityEvent
import org.chorus.event.vehicle.VehicleDamageEvent
import org.chorus.event.vehicle.VehicleDestroyByEntityEvent
import org.chorus.event.vehicle.VehicleDestroyEvent
import org.chorus.entity.item.EntityMinecartAbstract
import org.chorus.utils.MinecartType
import org.chorus.event.entity.EntityDamageByBlockEvent
import org.chorus.entity.EntityHanging
import org.chorus.entity.item.EntityPainting.Motive
import org.chorus.item.ItemPainting
import org.chorus.entity.item.EntityPainting
import org.chorus.network.protocol.AddPaintingPacket
import org.chorus.blockentity.BlockEntityPistonArm
import org.chorus.entity.item.EntityPainting.PaintingPlacePredicate
import java.util.function.BiFunction
import java.util.function.BinaryOperator
import org.chorus.inventory.InventoryType
import org.chorus.entity.projectile.SlenderProjectile
import org.chorus.level.particle.BubbleParticle
import org.chorus.level.particle.WaterParticle
import org.chorus.item.randomitem.Fishing
import org.chorus.event.player.PlayerFishEvent
import org.chorus.event.entity.ProjectileHitEvent
import org.chorus.level.MovingObjectPosition
import org.chorus.event.entity.EntityDamageByChildEntityEvent
import org.chorus.item.ItemTntMinecart
import org.chorus.entity.item.EntityFallingBlock
import org.chorus.block.BlockFlowingLava
import org.chorus.event.entity.EntityBlockChangeEvent
import org.chorus.block.BlockAnvil
import org.chorus.block.property.enums.Damage
import org.chorus.block.BlockAir
import org.chorus.block.BlockFallable
import org.chorus.entity.item.EntityFireworksRocket
import org.chorus.entity.item.EntityElytraFirework
import org.chorus.block.BlockHopper.IHopper
import org.chorus.inventory.MinecartHopperInventory
import org.chorus.event.block.HopperSearchItemEvent
import org.chorus.block.BlockComposter
import org.chorus.block.BlockActivatorRail
import org.chorus.item.ItemFireworkRocket
import org.chorus.entity.item.EntityCrossbowFirework
import org.chorus.math.MathHelper
import org.chorus.utils.Rail
import org.chorus.block.BlockRail
import org.chorus.block.BlockDetectorRail
import org.chorus.entity.item.EntityHopperMinecart
import org.chorus.item.ItemMinecart
import org.chorus.blockentity.BlockEntityHopper
import org.chorus.block.BlockGoldenRail
import org.chorus.entity.effect.PotionEffects
import org.chorus.event.potion.PotionApplyEvent
import org.chorus.entity.effect.EffectNightVision
import org.chorus.entity.effect.EffectInvisibility
import org.chorus.entity.effect.EffectJumpBoost
import org.chorus.entity.effect.EffectFireResistance
import org.chorus.entity.effect.EffectSpeed
import org.chorus.entity.effect.EffectSlowness
import org.chorus.entity.effect.EffectWaterBreathing
import org.chorus.entity.effect.EffectInstantHealth
import org.chorus.entity.effect.EffectInstantDamage
import org.chorus.entity.effect.EffectPoison
import org.chorus.entity.effect.EffectRegeneration
import org.chorus.entity.effect.EffectStrength
import org.chorus.entity.effect.EffectWeakness
import org.chorus.entity.effect.EffectWither
import org.chorus.entity.effect.EffectResistance
import org.chorus.entity.effect.EffectSlowFalling
import org.chorus.entity.effect.InstantEffect
import org.chorus.event.entity.EntityRegainHealthEvent
import org.chorus.block.BlockFire
import org.chorus.event.block.BlockIgniteEvent
import org.chorus.entity.weather.EntityLightningBolt
import org.chorus.block.property.enums.OxidizationLevel
import org.chorus.block.Oxidizable
import org.chorus.event.block.BlockFadeEvent
import org.chorus.level.particle.ElectricSparkParticle
import org.chorus.block.Waxable
import org.chorus.entity.weather.EntityWeather
import org.chorus.entity.projectile.throwable.EntityThrowable
import org.chorus.item.ItemEgg
import org.chorus.entity.mob.monster.EntityBlaze
import org.chorus.level.particle.GenericParticle
import org.chorus.level.particle.SpellParticle
import org.chorus.event.potion.PotionCollideEvent
import org.chorus.entity.projectile.abstract_arrow.EntityAbstractArrow
import org.chorus.item.ItemArrow
import org.chorus.event.entity.EntityCombustByEntityEvent
import org.chorus.block.BlockTrapdoor
import org.chorus.block.BlockButton
import org.chorus.block.BlockLever
import org.chorus.block.BlockCandle
import org.chorus.block.BlockCandleCake
import org.chorus.block.BlockChorusFlower
import org.chorus.block.BlockDecoratedPot
import org.chorus.entity.projectile.EntityWindCharge
import org.chorus.entity.projectile.EntityWitherSkull
import org.chorus.metadata.Metadatable
import org.chorus.math.Rotator2
import org.chorus.utils.ChunkException
import org.chorus.event.entity.EntityEffectRemoveEvent
import org.chorus.network.protocol.MobEffectPacket
import org.chorus.event.entity.EntityEffectUpdateEvent
import org.chorus.network.protocol.SetEntityLinkPacket
import org.chorus.network.protocol.RemoveEntityPacket
import org.chorus.item.ItemTotemOfUndying
import org.chorus.level.particle.ExplodeParticle
import org.chorus.event.entity.EntityPortalEnterEvent
import org.chorus.event.entity.EntityPortalEnterEvent.PortalType
import org.chorus.utils.PortalHelper
import org.chorus.network.protocol.SetEntityMotionPacket
import org.chorus.network.protocol.MoveEntityAbsolutePacket
import org.chorus.event.entity.EntityVehicleEnterEvent
import org.chorus.event.entity.EntityVehicleExitEvent
import org.chorus.tags.ItemTags
import org.chorus.event.player.PlayerInteractEvent
import org.chorus.event.entity.EntityInteractEvent
import org.chorus.event.entity.EntityLevelChangeEvent
import org.chorus.block.BlockBubbleColumn
import org.chorus.block.BlockEndPortal
import org.chorus.event.entity.EntityMotionEvent
import org.chorus.event.entity.EntityTeleportEvent
import org.chorus.event.entity.EntityDespawnEvent
import org.chorus.entity.data.PlayerFlag
import org.chorus.metadata.MetadataValue
import org.chorus.network.protocol.types.PropertySyncData
import org.chorus.inventory.HumanInventory
import org.chorus.inventory.HumanOffHandInventory
import org.chorus.entity.EntityHumanType
import org.chorus.entity.EntityComponent
import org.chorus.event.player.EntityFreezeEvent
import org.chorus.network.protocol.MovePlayerPacket
import org.chorus.network.protocol.AddPlayerPacket
import org.chorus.entity.EntityTimer
import org.chorus.entity.EntityDamageable
import org.chorus.event.entity.EntityDeathEvent
import org.chorus.scoreboard.manager.IScoreboardManager
import org.chorus.item.ItemTurtleHelmet
import org.chorus.block.BlockCactus
import org.chorus.utils.TickCachedBlockIterator
import org.chorus.event.entity.EntityDamageBlockedEvent
import org.chorus.entity.EntityAgeable
import org.chorus.entity.EntityItemSlot
import org.chorus.entity.EntityAsyncPrepare
import org.chorus.entity.EntityAbilities
import org.chorus.network.protocol.MobEquipmentPacket
import org.chorus.network.protocol.MobArmorEquipmentPacket
import org.chorus.entity.IHuman

