/**
 * 与实体相关的类,包含友好生物,敌对生物等.
 *
 *
 * Classes relevant to entity,
 * Including friendly creatures, hostile creatures, etc.
 */
package org.chorus.entity

import cn.nukkit.blockentity.BlockEntityBeehive.isHoneyFull
import cn.nukkit.blockentity.BlockEntityBeehive.occupantsCount
import cn.nukkit.blockentity.BlockEntityBeehive.addOccupant
import cn.nukkit.blockentity.BlockEntityCreakingHeart.setLinkedCreaking
import cn.nukkit.blockentity.BlockEntityCreakingHeart.isBlockEntityValid
import cn.nukkit.blockentity.BlockEntityCreakingHeart.heart
import cn.nukkit.dialog.window.FormWindowDialog.buttonJSONData
import cn.nukkit.dialog.window.FormWindowDialog.addHandler
import cn.nukkit.dialog.element.ElementDialogButton.getData
import cn.nukkit.dialog.window.FormWindowDialog.getButtons
import cn.nukkit.dialog.element.ElementDialogButton.getMode
import cn.nukkit.entity.ai.route.posevaluator.IPosEvaluator
import cn.nukkit.entity.mob.EntityMob
import cn.nukkit.entity.ai.route.finder.SimpleRouteFinder
import java.util.HashSet
import cn.nukkit.entity.ai.EntityAI
import cn.nukkit.level.particle.BlockForceFieldParticle
import cn.nukkit.entity.ai.route.finder.impl.SimpleFlatAStarRouteFinder
import cn.nukkit.math.VectorMath
import cn.nukkit.entity.ai.route.finder.IRouteFinder
import cn.nukkit.entity.ai.route.finder.impl.SimpleSpaceAStarRouteFinder
import java.util.concurrent.locks.ReentrantReadWriteLock
import cn.nukkit.math.AxisAlignedBB
import cn.nukkit.math.SimpleAxisAlignedBB
import cn.nukkit.block.BlockFence
import cn.nukkit.block.BlockFenceGate
import java.util.concurrent.ForkJoinPool
import cn.nukkit.entity.ai.route.RouteFindingManager.RouteFindingPoolThreadFactory
import cn.nukkit.entity.ai.route.RouteFindingManager.RouteFindingTask
import java.util.concurrent.ForkJoinWorkerThread
import cn.nukkit.entity.ai.route.RouteFindingManager
import java.util.concurrent.ForkJoinPool.ForkJoinWorkerThreadFactory
import java.security.AccessController
import java.security.PrivilegedAction
import cn.nukkit.entity.ai.route.RouteFindingManager.RouteFindingThread
import java.security.AccessControlContext
import cn.nukkit.entity.ai.route.RouteFindingManager.RouteFindingTask.FinishCallback
import java.util.concurrent.RecursiveAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.entity.ai.memory.codec.IMemoryCodec
import cn.nukkit.entity.ai.memory.codec.MemoryCodec
import cn.nukkit.entity.ai.memory.codec.NumberMemoryCodec.TagReader
import cn.nukkit.nbt.tag.NumberTag
import cn.nukkit.entity.ai.memory.codec.NumberMemoryCodec
import cn.nukkit.nbt.tag.ByteTag
import cn.nukkit.nbt.tag.ShortTag
import cn.nukkit.nbt.tag.IntTag
import cn.nukkit.nbt.tag.LongTag
import cn.nukkit.nbt.tag.FloatTag
import cn.nukkit.nbt.tag.DoubleTag
import cn.nukkit.entity.ai.memory.IMemoryStorage
import java.util.concurrent.ConcurrentHashMap
import cn.nukkit.entity.ai.memory.MemoryStorage
import java.util.HashMap
import cn.nukkit.event.entity.EntityDamageEvent
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityEvocationIllager.SPELL
import cn.nukkit.math.BlockVector3
import cn.nukkit.block.BlockBed
import cn.nukkit.block.BlockWoodenDoor
import cn.nukkit.entity.item.EntityItem
import cn.nukkit.entity.mob.villagers.EntityVillagerV2
import cn.nukkit.entity.ai.memory.codec.BooleanMemoryCodec
import cn.nukkit.entity.data.EntityFlag
import cn.nukkit.entity.ai.memory.codec.StringMemoryCodec
import cn.nukkit.entity.data.EntityDataTypes
import cn.nukkit.entity.ai.sensor.ISensor
import cn.nukkit.entity.ai.memory.CoreMemoryTypes
import cn.nukkit.entity.mob.animal.EntityAnimal
import cn.nukkit.entity.EntityOwnable
import cn.nukkit.inventory.ChestInventory
import cn.nukkit.inventory.DoubleChestInventory
import cn.nukkit.inventory.HumanEnderChestInventory
import cn.nukkit.inventory.ShulkerBoxInventory
import cn.nukkit.inventory.BarrelInventory
import cn.nukkit.inventory.MinecartChestInventory
import cn.nukkit.inventory.ChestBoatInventory
import cn.nukkit.entity.ai.sensor.NearestFeedingPlayerSensor
import cn.nukkit.entity.ai.executor.IBehaviorExecutor
import cn.nukkit.entity.ai.evaluator.IBehaviorEvaluator
import cn.nukkit.entity.ai.behavior.AbstractBehavior
import cn.nukkit.entity.ai.behavior.BehaviorState
import cn.nukkit.entity.ai.behavior.IBehavior
import cn.nukkit.entity.ai.executor.EntityControl
import cn.nukkit.entity.ai.executor.NearbyFlatRandomRoamExecutor
import cn.nukkit.entity.data.profession.Profession
import cn.nukkit.block.BlockCrops
import cn.nukkit.math.BlockFace
import cn.nukkit.math.BVector3
import lombok.RequiredArgsConstructor
import cn.nukkit.item.ItemFood
import cn.nukkit.entity.ai.executor.EntityBreedingExecutor
import cn.nukkit.network.protocol.EntityEventPacket
import cn.nukkit.entity.ai.executor.armadillo.PeekExecutor
import cn.nukkit.entity.mob.animal.EntityArmadillo
import cn.nukkit.entity.mob.animal.EntityArmadillo.RollupEvaluator
import cn.nukkit.entity.mob.animal.EntityArmadillo.RollState
import cn.nukkit.level.Sound
import cn.nukkit.entity.ai.executor.armadillo.RollUpExecutor
import cn.nukkit.entity.ai.executor.armadillo.UnrollingExecutor
import cn.nukkit.entity.ai.executor.evocation.FangLineExecutor
import cn.nukkit.entity.EntityLiving
import cn.nukkit.utils.BlockColor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityEvocationIllager
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.entity.EntityID
import cn.nukkit.entity.mob.monster.EntityEvocationFang
import cn.nukkit.entity.ai.executor.evocation.VexSummonExecutor
import cn.nukkit.entity.mob.monster.EntityVex
import cn.nukkit.entity.ai.executor.evocation.FangCircleExecutor
import cn.nukkit.entity.ai.executor.evocation.ColorConversionExecutor
import cn.nukkit.entity.mob.animal.EntitySheep
import cn.nukkit.utils.DyeColor
import cn.nukkit.entity.item.EntityAreaEffectCloud
import cn.nukkit.entity.mob.monster.EntityEnderDragon
import cn.nukkit.entity.item.EntityEnderCrystal
import lombok.AllArgsConstructor
import cn.nukkit.item.ItemBow
import cn.nukkit.entity.projectile.abstract_arrow.EntityArrow
import cn.nukkit.event.entity.EntityShootBowEvent
import cn.nukkit.entity.projectile.EntityProjectile
import cn.nukkit.item.enchantment.bow.EnchantmentBow
import cn.nukkit.event.entity.ProjectileLaunchEvent
import cn.nukkit.level.particle.DestroyBlockParticle
import cn.nukkit.block.BlockID
import cn.nukkit.level.GameRule
import cn.nukkit.entity.ai.executor.MultipleExecutor
import cn.nukkit.entity.ai.executor.MeleeAttackExecutor
import cn.nukkit.entity.mob.animal.EntityBee
import cn.nukkit.entity.ai.executor.FlatRandomRoamExecutor
import cn.nukkit.entity.mob.animal.EntityHorse
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.entity.mob.monster.EntityMonster
import cn.nukkit.item.ItemPotion
import cn.nukkit.block.BlockMagma
import cn.nukkit.event.entity.EntityDamageByEntityEvent
import cn.nukkit.entity.projectile.EntitySmallFireball
import cn.nukkit.network.protocol.LevelEventPacket
import cn.nukkit.entity.projectile.EntityFireball
import cn.nukkit.math.IVector3
import cn.nukkit.entity.ai.executor.MoveToTargetExecutor
import cn.nukkit.entity.mob.animal.EntityWolf
import cn.nukkit.entity.projectile.EntityBreezeWindCharge
import cn.nukkit.inventory.EntityInventoryHolder
import cn.nukkit.entity.EntityCanAttack
import cn.nukkit.event.entity.EntityDamageEvent.DamageModifier
import cn.nukkit.item.ItemGoldIngot
import cn.nukkit.entity.EntityEquipment
import cn.nukkit.entity.projectile.throwable.EntitySplashPotion
import cn.nukkit.entity.mob.EntityShulker
import cn.nukkit.entity.mob.monster.EntityWarden
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident
import cn.nukkit.item.ItemCrossbow
import cn.nukkit.entity.mob.monster.EntityEnderman
import cn.nukkit.block.Natural
import cn.nukkit.entity.projectile.EntityShulkerBullet
import cn.nukkit.entity.ai.evaluator.AllMatchEvaluator
import cn.nukkit.entity.ai.evaluator.EntityCheckEvaluator
import cn.nukkit.entity.ai.evaluator.DistanceEvaluator
import cn.nukkit.entity.ai.evaluator.NotMatchEvaluator
import cn.nukkit.entity.ai.evaluator.PassByTimeEvaluator
import cn.nukkit.network.protocol.LevelSoundEventPacketV2
import cn.nukkit.entity.projectile.throwable.EntitySnowball
import cn.nukkit.event.entity.EntityExplosionPrimeEvent
import cn.nukkit.entity.mob.monster.EntityCreeper
import cn.nukkit.level.Explosion
import cn.nukkit.level.particle.HugeExplodeSeedParticle
import cn.nukkit.entity.mob.EntityZoglin
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityZombiePigman
import cn.nukkit.network.protocol.LevelEventGenericPacket
import cn.nukkit.math.Vector3f
import cn.nukkit.entity.ai.evaluator.AnyMatchEvaluator
import cn.nukkit.entity.ai.evaluator.MultiBehaviorEvaluator
import cn.nukkit.entity.ai.evaluator.ProbabilityEvaluator
import cn.nukkit.entity.ai.controller.IController
import cn.nukkit.block.BlockCarpet
import cn.nukkit.entity.ai.controller.WalkController
import cn.nukkit.entity.EntityPhysical
import cn.nukkit.block.BlockLiquid
import cn.nukkit.entity.mob.animal.EntityRabbit
import cn.nukkit.entity.mob.monster.EntitySlime
import cn.nukkit.entity.ai.behaviorgroup.IBehaviorGroup
import cn.nukkit.entity.ai.behavior.Behavior
import cn.nukkit.entity.ai.behaviorgroup.BehaviorGroup
import cn.nukkit.entity.ai.behaviorgroup.BehaviorGroup.ChunkSectionVector
import cn.nukkit.level.format.IChunk
import cn.nukkit.level.DimensionData
import java.util.EnumSet
import cn.nukkit.entity.EntityFlyable
import cn.nukkit.entity.ai.executor.BeeAttackExecutor
import cn.nukkit.entity.ai.evaluator.MemoryCheckNotEmptyEvaluator
import cn.nukkit.entity.ai.executor.SpaceRandomRoamExecutor
import cn.nukkit.entity.ai.sensor.MemorizedBlockSensor
import cn.nukkit.entity.ai.controller.SpaceMoveController
import cn.nukkit.entity.ai.controller.LiftController
import cn.nukkit.entity.ai.route.posevaluator.FlyingPosEvaluator
import cn.nukkit.block.BlockBeehive
import cn.nukkit.block.BlockFlower
import cn.nukkit.block.BlockWitherRose
import cn.nukkit.blockentity.BlockEntityBeehive
import cn.nukkit.entity.EntityWalkable
import cn.nukkit.entity.EntityCanSit
import cn.nukkit.entity.EntityHealable
import cn.nukkit.entity.EntityVariant
import cn.nukkit.entity.EntityColor
import cn.nukkit.entity.ai.executor.InLoveExecutor
import cn.nukkit.entity.ai.executor.SleepOnOwnerBedExecutor
import cn.nukkit.entity.mob.animal.EntityCat
import cn.nukkit.entity.ai.executor.EntityMoveToOwnerExecutor
import cn.nukkit.entity.ai.executor.LookAtFeedingPlayerExecutor
import cn.nukkit.entity.ai.executor.LookAtTargetExecutor
import cn.nukkit.entity.ai.evaluator.ConditionalProbabilityEvaluator
import cn.nukkit.entity.ai.sensor.NearestPlayerSensor
import cn.nukkit.entity.ai.sensor.NearestTargetEntitySensor
import cn.nukkit.entity.ai.controller.FluctuateController
import cn.nukkit.entity.ai.route.posevaluator.WalkingPosEvaluator
import cn.nukkit.network.protocol.LevelSoundEventPacket
import cn.nukkit.level.particle.ItemBreakParticle
import cn.nukkit.item.ItemDye
import cn.nukkit.item.ItemID
import cn.nukkit.entity.mob.animal.EntityCow
import cn.nukkit.entity.mob.animal.EntityFox
import cn.nukkit.entity.ai.executor.AnimalGrowExecutor
import cn.nukkit.entity.mob.animal.EntityPig
import cn.nukkit.entity.mob.animal.EntityFrog
import cn.nukkit.entity.ai.controller.HoppingController
import cn.nukkit.entity.EntityAngryable
import cn.nukkit.entity.ai.executor.WolfAttackExecutor
import cn.nukkit.entity.ai.sensor.WolfNearestFeedingPlayerSensor
import cn.nukkit.entity.ai.sensor.EntityAttackedByOwnerSensor
import cn.nukkit.entity.mob.animal.EntityCamel
import cn.nukkit.entity.EntityMarkVariant
import cn.nukkit.entity.EntityRideable
import cn.nukkit.inventory.HorseInventory
import cn.nukkit.nbt.NBTIO
import cn.nukkit.network.protocol.UpdateAttributesPacket
import cn.nukkit.entity.ai.executor.TameHorseExecutor
import cn.nukkit.event.entity.EntityFallEvent
import cn.nukkit.event.block.FarmLandDecayEvent
import cn.nukkit.block.BlockDirt
import cn.nukkit.block.BlockTurtleEgg
import cn.nukkit.network.protocol.types.EntityLink
import cn.nukkit.network.protocol.DataPacket
import cn.nukkit.network.protocol.AddEntityPacket
import cn.nukkit.entity.custom.CustomEntity
import cn.nukkit.entity.mob.animal.EntityPanda
import cn.nukkit.entity.EntityShearable
import cn.nukkit.entity.ai.executor.EatGrassExecutor
import cn.nukkit.entity.ai.evaluator.BlockCheckEvaluator
import cn.nukkit.level.vibration.VibrationType
import cn.nukkit.entity.mob.animal.EntityDonkey
import cn.nukkit.entity.EntitySwimmable
import cn.nukkit.entity.ai.controller.DiveController
import cn.nukkit.entity.ai.executor.PlaySoundExecutor
import cn.nukkit.entity.ai.evaluator.RandomSoundEvaluator
import cn.nukkit.entity.mob.animal.EntityAxolotl
import cn.nukkit.entity.ai.sensor.BlockSensor
import cn.nukkit.block.BlockFlowingWater
import cn.nukkit.entity.ai.controller.ConditionalController
import cn.nukkit.entity.ai.route.finder.impl.ConditionalAStarRouteFinder
import cn.nukkit.entity.ai.route.posevaluator.SwimmingPosEvaluator
import cn.nukkit.entity.mob.animal.EntityChicken
import cn.nukkit.entity.mob.animal.EntitySniffer
import cn.nukkit.entity.ai.executor.armadillo.RelaxingExecutor
import cn.nukkit.entity.ai.executor.armadillo.ShedExecutor
import cn.nukkit.item.ItemBrush
import cn.nukkit.entity.mob.animal.EntityMooshroom
import cn.nukkit.level.ParticleEffect
import cn.nukkit.entity.mob.animal.EntityLlama
import cn.nukkit.entity.EntitySmite
import cn.nukkit.entity.mob.monster.EntityVex.VexMeleeAttackExecutor
import cn.nukkit.entity.mob.villagers.EntityVillager
import cn.nukkit.item.ItemTool
import cn.nukkit.network.protocol.BossEventPacket
import cn.nukkit.entity.ai.executor.BlazeShootExecutor
import cn.nukkit.event.entity.EntityDamageEvent.DamageCause
import cn.nukkit.entity.ai.executor.GhastShootExecutor
import cn.nukkit.entity.mob.EntityGolem
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityZombie
import cn.nukkit.entity.ai.executor.JumpExecutor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntitySkeleton
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityHumanoidMonster
import cn.nukkit.entity.ai.executor.UsePotionExecutor
import cn.nukkit.entity.ai.executor.PotionThrowExecutor
import cn.nukkit.entity.ai.sensor.NearestEntitySensor
import cn.nukkit.entity.ai.executor.BowShootExecutor
import cn.nukkit.entity.ai.executor.PiglinTransformExecutor
import cn.nukkit.entity.ai.executor.PiglinTradeExecutor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityPiglin
import cn.nukkit.entity.ai.executor.CrossBowShootExecutor
import cn.nukkit.item.ItemArmor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityPiglin.PiglinMeleeAttackExecutor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityPiglin.PiglinFleeFromTargetExecutor
import cn.nukkit.block.BlockSoulFire
import cn.nukkit.entity.mob.monster.EntityWither
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityWitherSkeleton
import cn.nukkit.entity.ai.sensor.NearestPlayerAngryPiglinSensor
import cn.nukkit.block.BlockDoor
import cn.nukkit.entity.mob.EntityHoglin
import cn.nukkit.network.protocol.AnimateEntityPacket.Animation
import cn.nukkit.network.protocol.AnimateEntityPacket
import cn.nukkit.item.ItemPorkchop
import cn.nukkit.network.protocol.TakeItemEntityPacket
import cn.nukkit.entity.ai.executor.FleeFromTargetExecutor
import cn.nukkit.entity.ai.executor.NearestBlockIncementExecutor
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityHusk
import cn.nukkit.entity.mob.animal.EntityTurtle
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityDrowned
import cn.nukkit.entity.ai.executor.TridentThrowExecutor
import cn.nukkit.item.ItemTrident
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityIllager
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityVindicator.VindicatorMeleeAttackExecutor
import cn.nukkit.item.ItemGoldenApple
import cn.nukkit.entity.ai.evaluator.MemoryCheckEmptyEvaluator
import cn.nukkit.entity.ai.executor.DoNothingExecutor
import cn.nukkit.entity.mob.monster.EntityCreaking
import cn.nukkit.entity.ai.executor.BreezeShootExecutor
import cn.nukkit.entity.ai.executor.BreezeJumpExecutor
import cn.nukkit.entity.EntityArthropod
import cn.nukkit.level.vibration.VibrationListener
import cn.nukkit.entity.ai.executor.WardenViolentAnimationExecutor
import cn.nukkit.entity.ai.executor.WardenRangedAttackExecutor
import cn.nukkit.entity.ai.executor.WardenMeleeAttackExecutor
import cn.nukkit.entity.ai.executor.WardenSniffExecutor
import cn.nukkit.entity.ai.evaluator.RandomTimeRangeEvaluator
import cn.nukkit.entity.ai.sensor.RouteUnreachableTimeSensor
import cn.nukkit.math.NukkitMath
import cn.nukkit.entity.EntityCreature
import cn.nukkit.entity.mob.monster.EntityBoss
import cn.nukkit.entity.ai.executor.WitherDashExecutor
import cn.nukkit.entity.ai.executor.WitherShootExecutor
import cn.nukkit.block.BlockBedrock
import cn.nukkit.block.BlockWitherSkeletonSkull
import cn.nukkit.block.BlockSoulSand
import cn.nukkit.entity.EntityInteractable
import cn.nukkit.entity.ai.executor.EntityExplosionExecutor
import cn.nukkit.entity.mob.animal.EntityOcelot
import cn.nukkit.entity.weather.EntityLightningStrike
import cn.nukkit.event.entity.CreeperPowerEvent
import cn.nukkit.entity.ai.executor.CircleAboveTargetExecutor
import cn.nukkit.entity.mob.monster.EntityPhantom.PhantomMeleeAttackExecutor
import cn.nukkit.blockentity.BlockEntityCreakingHeart
import cn.nukkit.entity.mob.monster.EntityCreaking.PlayerStaringCreakingSensor
import cn.nukkit.entity.mob.monster.EntityCreaking.NearestPlayerCreakingSensor
import cn.nukkit.block.BlockCreakingHeart
import cn.nukkit.block.BlockPaleOakLog
import cn.nukkit.block.BlockResinClump
import cn.nukkit.block.property.type.IntPropertyType
import cn.nukkit.block.property.CommonBlockProperties
import cn.nukkit.entity.ai.sensor.PlayerStaringSensor
import cn.nukkit.entity.ai.executor.StaringAttackTargetExecutor
import cn.nukkit.entity.ai.executor.TeleportExecutor
import cn.nukkit.entity.ai.executor.EndermanBlockExecutor
import cn.nukkit.entity.mob.monster.EntityEndermite
import cn.nukkit.entity.ai.executor.GuardianAttackExecutor
import cn.nukkit.entity.mob.EntityIronGolem
import cn.nukkit.entity.mob.monster.EntityMagmaCube
import cn.nukkit.entity.ai.executor.enderdragon.PerchingExecutor
import cn.nukkit.entity.ai.executor.enderdragon.StrafeExecutor
import cn.nukkit.entity.ai.executor.enderdragon.CircleMovementExecutor
import cn.nukkit.entity.mob.monster.EntityEnderDragon.EnderDragonRouteFinder
import cn.nukkit.entity.mob.monster.EntityEnderDragon.EnderDragonPosEvaluator
import cn.nukkit.block.BlockEndGateway
import cn.nukkit.entity.mob.monster.humanoid_monster.EntityZombieVillager
import cn.nukkit.utils.TradeRecipeBuildUtils
import cn.nukkit.inventory.TradeInventory
import cn.nukkit.inventory.EntityEquipmentInventory
import cn.nukkit.entity.ai.executor.villager.DoorExecutor
import cn.nukkit.entity.ai.executor.villager.WillingnessExecutor
import cn.nukkit.entity.ai.executor.villager.SleepExecutor
import cn.nukkit.entity.ai.executor.villager.WorkExecutor
import cn.nukkit.entity.ai.executor.villager.GossipExecutor
import cn.nukkit.entity.ai.executor.villager.VillagerBreedingExecutor
import cn.nukkit.utils.random.NukkitRandom
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.Clothing
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.Gossip
import cn.nukkit.network.protocol.UpdateTradePacket
import cn.nukkit.inventory.InventorySlice
import cn.nukkit.registry.BiomeRegistry.BiomeDefinition
import cn.nukkit.entity.mob.water_animal.fish.EntityFish
import cn.nukkit.entity.mob.water_animal.EntityWaterAnimal
import cn.nukkit.entity.mob.water_animal.EntityTropicalfish
import cn.nukkit.entity.ai.evaluator.LogicalUtils
import cn.nukkit.entity.ai.controller.EntityControlUtils
import kotlin.math.pow
import cn.nukkit.network.protocol.MoveEntityDeltaPacket
import cn.nukkit.entity.ai.behaviorgroup.EmptyBehaviorGroup
import cn.nukkit.form.window.SimpleForm
import cn.nukkit.dialog.window.FormWindowDialog
import cn.nukkit.entity.mob.EntityNPC
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.dialog.handler.FormDialogHandler
import cn.nukkit.dialog.response.FormResponseDialog
import cn.nukkit.network.protocol.NPCRequestPacket
import cn.nukkit.dialog.element.ElementDialogButton
import cn.nukkit.dialog.element.ElementDialogButton.CmdLine
import cn.nukkit.command.NPCCommandSender
import cn.nukkit.entity.ai.sensor.NearestItemSensor
import cn.nukkit.entity.mob.EntityAllay
import cn.nukkit.entity.ai.executor.HoglinTransformExecutor
import cn.nukkit.entity.mob.EntityHoglin.HoglinMeleeAttackExecutor
import cn.nukkit.entity.mob.EntityHoglin.HoglinFleeFromTargetExecutor
import cn.nukkit.block.BlockPortal
import cn.nukkit.block.BlockWarpedFungus
import cn.nukkit.block.BlockRespawnAnchor
import cn.nukkit.entity.ai.executor.ShulkerIdleExecutor
import cn.nukkit.entity.ai.executor.ShulkerAttackExecutor
import cn.nukkit.event.player.PlayerTeleportEvent
import cn.nukkit.event.player.PlayerTeleportEvent.TeleportCause
import cn.nukkit.entity.mob.EntitySquid
import cn.nukkit.item.ItemIronIngot
import cn.nukkit.block.BlockPumpkin
import cn.nukkit.block.BlockIronBlock
import cn.nukkit.entity.ai.executor.SnowGolemShootExecutor
import cn.nukkit.entity.mob.EntitySnowGolem
import cn.nukkit.item.ItemShears
import cn.nukkit.block.BlockSnow
import cn.nukkit.entity.EntityNameable
import cn.nukkit.entity.mob.EntityArmorStand
import cn.nukkit.item.ItemShield
import cn.nukkit.event.player.PlayerChangeArmorStandEvent
import cn.nukkit.inventory.BaseInventory
import cn.nukkit.network.protocol.SetEntityDataPacket
import cn.nukkit.inventory.EntityArmorInventory
import cn.nukkit.entity.data.property.EntityProperty
import cn.nukkit.entity.data.property.IntEntityProperty
import cn.nukkit.entity.data.property.FloatEntityProperty
import cn.nukkit.entity.data.property.BooleanEntityProperty
import cn.nukkit.entity.data.property.EnumEntityProperty
import java.io.IOException
import cn.nukkit.network.protocol.SyncEntityPropertyPacket
import cn.nukkit.utils.SkinAnimation
import cn.nukkit.utils.PersonaPiece
import cn.nukkit.utils.PersonaPieceTint
import cn.nukkit.utils.SerializedImage
import java.awt.image.BufferedImage
import cn.nukkit.entity.data.profession.ProfessionFarmer
import cn.nukkit.entity.data.profession.ProfessionFisherman
import cn.nukkit.entity.data.profession.ProfessionShepherd
import cn.nukkit.entity.data.profession.ProfessionFletcher
import cn.nukkit.entity.data.profession.ProfessionLibrarian
import cn.nukkit.entity.data.profession.ProfessionCartographer
import cn.nukkit.entity.data.profession.ProfessionCleric
import cn.nukkit.entity.data.profession.ProfessionArmor
import cn.nukkit.entity.data.profession.ProfessionWeapon
import cn.nukkit.entity.data.profession.ProfessionTool
import cn.nukkit.entity.data.profession.ProfessionButcher
import cn.nukkit.entity.data.profession.ProfessionLeather
import cn.nukkit.entity.data.profession.ProfessionMason
import java.util.Locale
import cn.nukkit.item.ItemLeatherChestplate
import cn.nukkit.item.ItemLeatherLeggings
import cn.nukkit.item.ItemLeatherHelmet
import cn.nukkit.item.ItemLeatherBoots
import cn.nukkit.entity.data.EntityDataType
import cn.nukkit.entity.data.EntityDataMap
import cn.nukkit.entity.data.EntityDataFormat
import cn.nukkit.entity.EntityExplosive
import cn.nukkit.entity.item.EntityVehicle
import cn.nukkit.entity.item.EntityBoat
import cn.nukkit.event.vehicle.VehicleUpdateEvent
import cn.nukkit.event.vehicle.VehicleMoveEvent
import cn.nukkit.math.AxisAlignedBB.BBConsumer
import cn.nukkit.entity.EntityHuman
import cn.nukkit.network.protocol.AnimatePacket
import cn.nukkit.event.entity.ItemSpawnEvent
import cn.nukkit.event.entity.ItemDespawnEvent
import cn.nukkit.network.protocol.AddItemEntityPacket
import cn.nukkit.entity.item.EntityXpOrb
import cn.nukkit.event.vehicle.VehicleDamageByEntityEvent
import cn.nukkit.event.vehicle.VehicleDamageEvent
import cn.nukkit.event.vehicle.VehicleDestroyByEntityEvent
import cn.nukkit.event.vehicle.VehicleDestroyEvent
import cn.nukkit.entity.item.EntityMinecartAbstract
import cn.nukkit.utils.MinecartType
import cn.nukkit.event.entity.EntityDamageByBlockEvent
import cn.nukkit.entity.EntityHanging
import cn.nukkit.entity.item.EntityPainting.Motive
import cn.nukkit.item.ItemPainting
import cn.nukkit.entity.item.EntityPainting
import cn.nukkit.network.protocol.AddPaintingPacket
import cn.nukkit.blockentity.BlockEntityPistonArm
import cn.nukkit.entity.item.EntityPainting.PaintingPlacePredicate
import java.util.function.BiFunction
import java.util.function.BinaryOperator
import cn.nukkit.inventory.InventoryType
import cn.nukkit.entity.projectile.SlenderProjectile
import cn.nukkit.level.particle.BubbleParticle
import cn.nukkit.level.particle.WaterParticle
import cn.nukkit.item.randomitem.Fishing
import cn.nukkit.event.player.PlayerFishEvent
import cn.nukkit.event.entity.ProjectileHitEvent
import cn.nukkit.level.MovingObjectPosition
import cn.nukkit.event.entity.EntityDamageByChildEntityEvent
import cn.nukkit.item.ItemTntMinecart
import cn.nukkit.entity.item.EntityFallingBlock
import cn.nukkit.block.BlockFlowingLava
import cn.nukkit.event.entity.EntityBlockChangeEvent
import cn.nukkit.block.BlockAnvil
import cn.nukkit.block.property.enums.Damage
import cn.nukkit.block.BlockAir
import cn.nukkit.block.BlockFallable
import cn.nukkit.entity.item.EntityFireworksRocket
import cn.nukkit.entity.item.EntityElytraFirework
import cn.nukkit.block.BlockHopper.IHopper
import cn.nukkit.inventory.MinecartHopperInventory
import cn.nukkit.event.block.HopperSearchItemEvent
import cn.nukkit.block.BlockComposter
import cn.nukkit.block.BlockActivatorRail
import cn.nukkit.item.ItemFireworkRocket
import cn.nukkit.entity.item.EntityCrossbowFirework
import cn.nukkit.math.MathHelper
import cn.nukkit.utils.Rail
import cn.nukkit.block.BlockRail
import cn.nukkit.block.BlockDetectorRail
import cn.nukkit.entity.item.EntityHopperMinecart
import cn.nukkit.item.ItemMinecart
import cn.nukkit.blockentity.BlockEntityHopper
import cn.nukkit.block.BlockGoldenRail
import cn.nukkit.entity.effect.PotionEffects
import cn.nukkit.event.potion.PotionApplyEvent
import cn.nukkit.entity.effect.EffectNightVision
import cn.nukkit.entity.effect.EffectInvisibility
import cn.nukkit.entity.effect.EffectJumpBoost
import cn.nukkit.entity.effect.EffectFireResistance
import cn.nukkit.entity.effect.EffectSpeed
import cn.nukkit.entity.effect.EffectSlowness
import cn.nukkit.entity.effect.EffectWaterBreathing
import cn.nukkit.entity.effect.EffectInstantHealth
import cn.nukkit.entity.effect.EffectInstantDamage
import cn.nukkit.entity.effect.EffectPoison
import cn.nukkit.entity.effect.EffectRegeneration
import cn.nukkit.entity.effect.EffectStrength
import cn.nukkit.entity.effect.EffectWeakness
import cn.nukkit.entity.effect.EffectWither
import cn.nukkit.entity.effect.EffectResistance
import cn.nukkit.entity.effect.EffectSlowFalling
import cn.nukkit.entity.effect.InstantEffect
import cn.nukkit.event.entity.EntityRegainHealthEvent
import cn.nukkit.block.BlockFire
import cn.nukkit.event.block.BlockIgniteEvent
import cn.nukkit.entity.weather.EntityLightningBolt
import cn.nukkit.block.property.enums.OxidizationLevel
import cn.nukkit.block.Oxidizable
import cn.nukkit.event.block.BlockFadeEvent
import cn.nukkit.level.particle.ElectricSparkParticle
import cn.nukkit.block.Waxable
import cn.nukkit.entity.weather.EntityWeather
import cn.nukkit.entity.projectile.throwable.EntityThrowable
import cn.nukkit.item.ItemEgg
import cn.nukkit.entity.mob.monster.EntityBlaze
import cn.nukkit.level.particle.GenericParticle
import cn.nukkit.level.particle.SpellParticle
import cn.nukkit.event.potion.PotionCollideEvent
import cn.nukkit.entity.projectile.abstract_arrow.EntityAbstractArrow
import cn.nukkit.item.ItemArrow
import cn.nukkit.event.entity.EntityCombustByEntityEvent
import cn.nukkit.block.BlockTrapdoor
import cn.nukkit.block.BlockButton
import cn.nukkit.block.BlockLever
import cn.nukkit.block.BlockCandle
import cn.nukkit.block.BlockCandleCake
import cn.nukkit.block.BlockChorusFlower
import cn.nukkit.block.BlockDecoratedPot
import cn.nukkit.entity.projectile.EntityWindCharge
import cn.nukkit.entity.projectile.EntityWitherSkull
import cn.nukkit.metadata.Metadatable
import cn.nukkit.math.Rotator2
import cn.nukkit.utils.ChunkException
import cn.nukkit.event.entity.EntityEffectRemoveEvent
import cn.nukkit.network.protocol.MobEffectPacket
import cn.nukkit.event.entity.EntityEffectUpdateEvent
import cn.nukkit.network.protocol.SetEntityLinkPacket
import cn.nukkit.network.protocol.RemoveEntityPacket
import cn.nukkit.item.ItemTotemOfUndying
import cn.nukkit.level.particle.ExplodeParticle
import cn.nukkit.event.entity.EntityPortalEnterEvent
import cn.nukkit.event.entity.EntityPortalEnterEvent.PortalType
import cn.nukkit.utils.PortalHelper
import cn.nukkit.network.protocol.SetEntityMotionPacket
import cn.nukkit.network.protocol.MoveEntityAbsolutePacket
import cn.nukkit.event.entity.EntityVehicleEnterEvent
import cn.nukkit.event.entity.EntityVehicleExitEvent
import cn.nukkit.tags.ItemTags
import cn.nukkit.event.player.PlayerInteractEvent
import cn.nukkit.event.entity.EntityInteractEvent
import cn.nukkit.event.entity.EntityLevelChangeEvent
import cn.nukkit.block.BlockBubbleColumn
import cn.nukkit.block.BlockEndPortal
import cn.nukkit.event.entity.EntityMotionEvent
import cn.nukkit.event.entity.EntityTeleportEvent
import cn.nukkit.event.entity.EntityDespawnEvent
import cn.nukkit.entity.data.PlayerFlag
import cn.nukkit.metadata.MetadataValue
import cn.nukkit.network.protocol.types.PropertySyncData
import cn.nukkit.inventory.HumanInventory
import cn.nukkit.inventory.HumanOffHandInventory
import cn.nukkit.entity.EntityHumanType
import cn.nukkit.entity.EntityComponent
import cn.nukkit.event.player.EntityFreezeEvent
import cn.nukkit.network.protocol.MovePlayerPacket
import cn.nukkit.network.protocol.AddPlayerPacket
import cn.nukkit.entity.EntityTimer
import cn.nukkit.entity.EntityDamageable
import cn.nukkit.event.entity.EntityDeathEvent
import cn.nukkit.scoreboard.manager.IScoreboardManager
import cn.nukkit.item.ItemTurtleHelmet
import cn.nukkit.block.BlockCactus
import cn.nukkit.utils.TickCachedBlockIterator
import cn.nukkit.event.entity.EntityDamageBlockedEvent
import cn.nukkit.entity.EntityAgeable
import cn.nukkit.entity.EntityItemSlot
import cn.nukkit.entity.EntityAsyncPrepare
import cn.nukkit.entity.EntityAbilities
import cn.nukkit.network.protocol.MobEquipmentPacket
import cn.nukkit.network.protocol.MobArmorEquipmentPacket
import cn.nukkit.entity.IHuman

