/**
 * 与物品相关的类.
 *
 *
 * Classes relevant to item.
 */
package org.chorus.item

import org.chorus.event.entity.EntityEvent.entity
import org.chorus.entity.Entity.addEffect
import org.chorus.entity.effect.Effect.Companion.get
import org.chorus.entity.effect.Effect.setDuration
import org.chorus.entity.effect.Effect.setAmplifier
import org.chorus.entity.Entity.isTouchingWater
import org.chorus.event.entity.EntityDamageEvent.setDamage
import org.chorus.event.entity.EntityDamageEvent.getDamage
import org.chorus.entity.EntityHumanType.getInventory
import org.chorus.inventory.HumanInventory.armorContents
import org.chorus.entity.Entity.attack
import org.chorus.event.Event.isCancelled
import org.chorus.entity.Entity.setOnFire
import org.chorus.inventory.BaseInventory.contents
import org.chorus.entity.EntityHumanType.getOffhandInventory
import org.chorus.inventory.BaseInventory.sendContents
import org.chorus.inventory.HumanInventory.sendContents
import org.chorus.entity.Entity.getTransform
import org.chorus.entity.Entity.getDirectionVector
import org.chorus.entity.EntityHuman.getEyeHeight
import org.chorus.entity.Entity.Companion.createEntity
import org.chorus.entity.projectile.abstract_arrow.EntityArrow.setItem
import org.chorus.event.Event.setCancelled
import org.chorus.event.entity.EntityShootBowEvent.getProjectile
import org.chorus.entity.Entity.kill
import org.chorus.entity.Entity.setMotion
import org.chorus.entity.Entity.getMotion
import org.chorus.entity.projectile.abstract_arrow.EntityArrow.setPickupMode
import org.chorus.inventory.HumanOffHandInventory.setItem
import org.chorus.inventory.BaseInventory.getItem
import org.chorus.inventory.HumanInventory.setItem
import org.chorus.inventory.HumanInventory.setItemInHand
import org.chorus.entity.projectile.EntityProjectile.spawnToAll
import org.chorus.inventory.HumanInventory.itemInHand
import org.chorus.entity.Entity.spawnToAll
import org.chorus.entity.Entity.resetFallDistance
import org.chorus.inventory.HumanInventory.helmet
import org.chorus.inventory.HumanInventory.setHelmet
import org.chorus.inventory.HumanInventory.chestplate
import org.chorus.inventory.HumanInventory.setChestplate
import org.chorus.inventory.HumanInventory.leggings
import org.chorus.inventory.HumanInventory.setLeggings
import org.chorus.inventory.HumanInventory.boots
import org.chorus.inventory.HumanInventory.setBoots
import org.chorus.inventory.HumanInventory.heldItemIndex
import org.chorus.entity.effect.PotionType.Companion.get
import org.chorus.entity.Entity.getServer
import org.chorus.inventory.HumanInventory.canAddItem
import org.chorus.inventory.HumanInventory.addItem
import org.chorus.entity.EntityVariant.setVariant
import org.chorus.entity.effect.PotionType.equals
import org.chorus.entity.effect.PotionType.getRomanLevel
import org.chorus.entity.effect.PotionType.applyEffects
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident.setItem
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident.setPickupMode
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident.setFavoredSlot
import org.chorus.entity.Entity.close
import org.chorus.inventory.Inventory.removeItem
import org.chorus.event.entity.EntityShootCrossbowEvent.getProjectile
import org.chorus.entity.item.EntityPainting.PaintingPlacePredicate.test
import org.chorus.inventory.BaseInventory.decreaseCount
import org.chorus.entity.Entity.Companion.getDefaultNBT
import org.chorus.entity.Entity.removeAllEffects
import org.chorus.entity.Entity.isInsideOfWater
import org.chorus.entity.Entity.teleport
import org.chorus.entity.Entity.getBoundingBox
import org.chorus.entity.item.EntityAreaEffectCloud.isDragonBreath
import org.chorus.entity.item.EntityAreaEffectCloud.setRadius
import org.chorus.entity.item.EntityAreaEffectCloud.getRadius
import org.chorus.entity.Entity.removeEffect
import org.chorus.entity.Entity.getLocator
import org.chorus.item.ItemID
import org.chorus.nbt.tag.CompoundTag
import org.chorus.item.Item.ItemJsonComponents
import org.chorus.item.Item.ItemJsonComponents.ItemLock
import org.chorus.item.Item.ItemLockMode
import org.chorus.nbt.tag.ListTag
import org.chorus.nbt.tag.IntTag
import org.chorus.nbt.tag.StringTag
import org.chorus.nbt.NBTIO
import java.nio.ByteOrder
import java.io.IOException
import org.chorus.tags.ItemTags
import org.chorus.block.BlockID
import org.chorus.math.BlockFace
import it.unimi.dsi.fastutil.ints.Int2IntArrayMap
import org.chorus.item.Item.ItemJsonComponents.CanPlaceOn
import org.chorus.item.Item.ItemJsonComponents.CanDestory
import org.chorus.item.Item.ItemJsonComponents.KeepOnDeath
import org.chorus.utils.JSONUtils
import org.chorus.item.ConstAirItem
import org.chorus.block.BlockAir
import org.chorus.math.Vector3f
import org.chorus.item.customitem.data.Offset
import org.chorus.nbt.tag.FloatTag
import org.chorus.item.customitem.data.RenderOffsets
import org.chorus.item.customitem.data.CreativeCategory
import org.chorus.item.customitem.CustomItemDefinition
import org.chorus.item.customitem.CustomItem
import org.chorus.item.customitem.ItemCustom
import org.chorus.item.ItemFood
import org.chorus.item.ItemTool
import org.chorus.item.ItemArmor
import org.chorus.item.customitem.data.CreativeGroup
import org.chorus.item.customitem.CustomItemDefinition.SimpleBuilder
import org.chorus.item.customitem.ItemCustomTool
import org.chorus.item.customitem.CustomItemDefinition.ToolBuilder
import org.chorus.item.customitem.data.DigProperty
import java.util.HashMap
import org.chorus.item.customitem.ItemCustomArmor
import org.chorus.item.customitem.CustomItemDefinition.ArmorBuilder
import org.chorus.item.customitem.ItemCustomFood
import java.util.concurrent.atomic.AtomicInteger
import org.chorus.item.customitem.CustomItemDefinition.EdibleBuilder
import org.chorus.item.ItemEnchantedBook
import org.chorus.item.randomitem.EnchantmentItemSelector
import org.chorus.item.randomitem.RandomItem
import org.chorus.item.randomitem.Fishing
import org.chorus.item.randomitem.ConstantItemSelector
import org.chorus.item.randomitem.fishing.FishingEnchantmentItemSelector
import org.chorus.math.NukkitMath
import org.chorus.item.enchantment.Enchantment.Rarity
import org.chorus.item.enchantment.EnchantmentType
import org.chorus.entity.EntityLiving
import org.chorus.entity.projectile.EntityProjectile
import org.chorus.item.ItemBow
import org.chorus.item.enchantment.bow.EnchantmentBow
import org.chorus.item.enchantment.loot.EnchantmentLoot
import org.chorus.item.enchantment.damage.EnchantmentDamage
import org.chorus.entity.EntitySmite
import org.chorus.entity.EntityArthropod
import org.chorus.event.entity.EntityDamageByEntityEvent
import org.chorus.item.enchantment.trident.EnchantmentTrident
import org.chorus.item.enchantment.crossbow.EnchantmentCrossbow
import org.chorus.item.ItemElytra
import org.chorus.item.enchantment.protection.EnchantmentProtection
import org.chorus.event.entity.EntityDamageEvent
import org.chorus.event.entity.EntityDamageEvent.DamageCause
import org.chorus.item.enchantment.protection.EnchantmentProtectionAll
import org.chorus.item.enchantment.protection.EnchantmentProtectionFire
import org.chorus.item.enchantment.protection.EnchantmentProtectionFall
import org.chorus.item.enchantment.protection.EnchantmentProtectionExplosion
import org.chorus.item.enchantment.protection.EnchantmentProtectionProjectile
import org.chorus.item.enchantment.EnchantmentThorns
import org.chorus.item.enchantment.EnchantmentWaterBreath
import org.chorus.item.enchantment.EnchantmentWaterWorker
import org.chorus.item.enchantment.EnchantmentWaterWalker
import org.chorus.item.enchantment.damage.EnchantmentDamageAll
import org.chorus.item.enchantment.damage.EnchantmentDamageSmite
import org.chorus.item.enchantment.damage.EnchantmentDamageArthropods
import org.chorus.item.enchantment.EnchantmentKnockback
import org.chorus.item.enchantment.EnchantmentFireAspect
import org.chorus.item.enchantment.loot.EnchantmentLootWeapon
import org.chorus.item.enchantment.EnchantmentEfficiency
import org.chorus.item.enchantment.EnchantmentSilkTouch
import org.chorus.item.enchantment.EnchantmentDurability
import org.chorus.item.enchantment.loot.EnchantmentLootDigging
import org.chorus.item.enchantment.bow.EnchantmentBowPower
import org.chorus.item.enchantment.bow.EnchantmentBowKnockback
import org.chorus.item.enchantment.bow.EnchantmentBowFlame
import org.chorus.item.enchantment.bow.EnchantmentBowInfinity
import org.chorus.item.enchantment.loot.EnchantmentLootFishing
import org.chorus.item.enchantment.EnchantmentLure
import org.chorus.item.enchantment.EnchantmentFrostWalker
import org.chorus.item.enchantment.EnchantmentMending
import org.chorus.item.enchantment.EnchantmentBindingCurse
import org.chorus.item.enchantment.EnchantmentVanishingCurse
import org.chorus.item.enchantment.trident.EnchantmentTridentImpaling
import org.chorus.item.enchantment.trident.EnchantmentTridentRiptide
import org.chorus.item.enchantment.trident.EnchantmentTridentLoyalty
import org.chorus.item.enchantment.trident.EnchantmentTridentChanneling
import org.chorus.item.enchantment.crossbow.EnchantmentCrossbowMultishot
import org.chorus.item.enchantment.crossbow.EnchantmentCrossbowPiercing
import org.chorus.item.enchantment.crossbow.EnchantmentCrossbowQuickCharge
import org.chorus.item.enchantment.EnchantmentSoulSpeed
import org.chorus.item.enchantment.EnchantmentSwiftSneak
import org.chorus.item.enchantment.EnchantmentDensity
import org.chorus.item.enchantment.EnchantmentBreach
import org.chorus.utils.OK
import org.chorus.plugin.InternalPlugin
import org.chorus.registry.RegisterException
import org.chorus.item.enchantment.Enchantment.UnknownEnchantment
import java.util.LinkedHashSet
import java.util.HashSet
import org.chorus.item.enchantment.EnchantmentEntry
import org.chorus.item.enchantment.EnchantmentList
import org.chorus.item.ItemBook
import org.chorus.item.ItemTrident
import org.chorus.item.ItemFishingRod
import org.chorus.item.ItemHead
import org.chorus.block.BlockCarvedPumpkin
import org.chorus.item.ItemCrossbow
import org.chorus.item.ItemMace
import org.chorus.event.entity.EntityDamageEvent.DamageModifier
import org.chorus.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import org.chorus.utils.random.NukkitRandom
import org.chorus.item.enchantment.EnchantmentHelper
import java.util.concurrent.atomic.AtomicReference
import org.chorus.entity.EntityHumanType
import org.chorus.event.entity.EntityCombustByEntityEvent
import org.chorus.utils.DyeColor
import org.chorus.block.BlockBed
import org.chorus.item.ItemArrow
import org.chorus.entity.projectile.abstract_arrow.EntityArrow
import org.chorus.event.entity.EntityShootBowEvent
import org.chorus.level.Sound
import org.chorus.event.entity.ProjectileLaunchEvent
import org.chorus.item.ItemFish
import org.chorus.item.ProjectileItem
import org.chorus.block.BlockFlowingWater
import org.chorus.entity.item.EntityBoat
import org.chorus.item.ItemBlock
import org.chorus.block.BlockDirt
import org.chorus.event.player.PlayerItemConsumeEvent
import org.chorus.network.protocol.CompletedUsingItemPacket
import org.chorus.level.vibration.VibrationType
import org.chorus.block.BlockSand
import org.chorus.item.ItemDurable
import org.chorus.event.item.ItemWearEvent
import org.chorus.nbt.tag.ByteTag
import org.chorus.block.BlockAnvil
import org.chorus.item.ItemPotion
import org.chorus.block.BlockStandingBanner
import org.chorus.block.property.CommonBlockProperties
import org.chorus.network.protocol.types.BannerPattern
import org.chorus.entity.EntityID
import org.chorus.item.ItemBucket
import org.chorus.block.BlockPowderSnow
import org.chorus.block.BlockLiquid
import org.chorus.block.BlockFlowingLava
import org.chorus.event.player.PlayerBucketFillEvent
import org.chorus.event.player.PlayerBucketEmptyEvent
import org.chorus.network.protocol.UpdateBlockPacket
import org.chorus.network.protocol.LevelSoundEventPacket
import org.chorus.level.particle.ExplodeParticle
import org.chorus.entity.EntityVariant
import org.chorus.item.ItemDye
import org.chorus.item.ItemGlassBottle
import org.chorus.item.ItemBanner
import org.chorus.item.ItemBoat
import org.chorus.item.ItemSign
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident
import org.chorus.item.ItemFireworkRocket
import org.chorus.entity.item.EntityCrossbowFirework
import org.chorus.event.entity.EntityShootCrossbowEvent
import org.chorus.utils.Rail
import org.chorus.block.BlockRail
import org.chorus.entity.item.EntityMinecart
import org.chorus.level.format.IChunk
import org.chorus.entity.item.EntityPainting.Motive
import org.chorus.entity.item.EntityPainting
import org.chorus.item.ItemPainting
import org.chorus.event.entity.CreatureSpawnEvent
import org.chorus.event.entity.CreatureSpawnEvent.SpawnReason
import org.chorus.entity.item.EntityChestBoat
import org.chorus.item.ItemCod
import java.awt.image.BufferedImage
import org.chorus.item.ItemFilledMap
import javax.imageio.ImageIO
import java.awt.Graphics2D
import java.io.ByteArrayInputStream
import org.chorus.network.protocol.ClientboundMapItemDataPacket
import org.chorus.item.ItemBundle
import org.chorus.block.BlockSandstone
import org.chorus.math.SimpleAxisAlignedBB
import org.chorus.entity.mob.EntityArmorStand
import org.chorus.math.CompassRoseDirection
import org.chorus.item.ItemColorArmor
import org.chorus.utils.BlockColor
import org.chorus.block.BlockBedrock
import org.chorus.block.BlockObsidian
import org.chorus.entity.projectile.throwable.EntityEnderPearl
import org.chorus.block.BlockFire
import org.chorus.event.block.BlockIgniteEvent
import org.chorus.network.protocol.LevelEventPacket
import org.chorus.item.ItemMusicDisc
import org.chorus.item.ItemBowl
import org.chorus.block.BlockOakSlab
import org.chorus.block.property.enums.MinecraftVerticalHalf
import org.chorus.block.property.type.EnumPropertyType
import org.chorus.block.BlockSpruceSlab
import org.chorus.block.BlockBirchSlab
import org.chorus.block.BlockJungleSlab
import org.chorus.block.BlockAcaciaSlab
import org.chorus.block.BlockDarkOakSlab
import org.chorus.network.protocol.LevelSoundEventPacketV2
import org.chorus.item.ItemSpawnEgg
import org.chorus.event.player.PlayerTeleportEvent
import org.chorus.entity.item.EntityAreaEffectCloud
import org.chorus.item.ItemDragonBreath
import org.chorus.block.BlockBeehive
import org.chorus.block.BlockCaveVines
import org.chorus.block.property.type.IntPropertyType
import org.chorus.entity.item.EntityTntMinecart
import org.chorus.item.ItemBookWritable
import org.chorus.item.ItemWrittenBook
import org.chorus.item.ItemSalmon
import org.chorus.item.ItemChestBoat
import org.chorus.block.BlockSweetBerryBush
import org.chorus.network.protocol.types.BannerPatternType
import org.chorus.entity.item.EntityChestMinecart
import org.chorus.item.ItemFireworkRocket.FireworkExplosion
import org.chorus.entity.item.EntityFireworksRocket
import org.chorus.entity.item.EntityElytraFirework
import org.chorus.item.ItemFireworkRocket.FireworkExplosion.ExplosionType
import org.chorus.entity.item.EntityHopperMinecart
import org.chorus.item.ItemHangingSign
import org.chorus.item.ItemPotato
import org.chorus.item.ItemPotterySherd
import org.chorus.positiontracking.NamedPosition
import org.chorus.item.ItemBannerPattern

