/**
 * 与物品相关的类.
 *
 *
 * Classes relevant to item.
 */
package org.chorus.item

import cn.nukkit.event.entity.EntityEvent.entity
import cn.nukkit.entity.Entity.addEffect
import cn.nukkit.entity.effect.Effect.Companion.get
import cn.nukkit.entity.effect.Effect.setDuration
import cn.nukkit.entity.effect.Effect.setAmplifier
import cn.nukkit.entity.Entity.isTouchingWater
import cn.nukkit.event.entity.EntityDamageEvent.setDamage
import cn.nukkit.event.entity.EntityDamageEvent.getDamage
import cn.nukkit.entity.EntityHumanType.getInventory
import cn.nukkit.inventory.HumanInventory.armorContents
import cn.nukkit.entity.Entity.attack
import cn.nukkit.event.Event.isCancelled
import cn.nukkit.entity.Entity.setOnFire
import cn.nukkit.inventory.BaseInventory.contents
import cn.nukkit.entity.EntityHumanType.getOffhandInventory
import cn.nukkit.inventory.BaseInventory.sendContents
import cn.nukkit.inventory.HumanInventory.sendContents
import cn.nukkit.entity.Entity.getTransform
import cn.nukkit.entity.Entity.getDirectionVector
import cn.nukkit.entity.EntityHuman.getEyeHeight
import cn.nukkit.entity.Entity.Companion.createEntity
import cn.nukkit.entity.projectile.abstract_arrow.EntityArrow.setItem
import cn.nukkit.event.Event.setCancelled
import cn.nukkit.event.entity.EntityShootBowEvent.getProjectile
import cn.nukkit.entity.Entity.kill
import cn.nukkit.entity.Entity.setMotion
import cn.nukkit.entity.Entity.getMotion
import cn.nukkit.entity.projectile.abstract_arrow.EntityArrow.setPickupMode
import cn.nukkit.inventory.HumanOffHandInventory.setItem
import cn.nukkit.inventory.BaseInventory.getItem
import cn.nukkit.inventory.HumanInventory.setItem
import cn.nukkit.inventory.HumanInventory.setItemInHand
import cn.nukkit.entity.projectile.EntityProjectile.spawnToAll
import cn.nukkit.inventory.HumanInventory.itemInHand
import cn.nukkit.entity.Entity.spawnToAll
import cn.nukkit.entity.Entity.resetFallDistance
import cn.nukkit.inventory.HumanInventory.helmet
import cn.nukkit.inventory.HumanInventory.setHelmet
import cn.nukkit.inventory.HumanInventory.chestplate
import cn.nukkit.inventory.HumanInventory.setChestplate
import cn.nukkit.inventory.HumanInventory.leggings
import cn.nukkit.inventory.HumanInventory.setLeggings
import cn.nukkit.inventory.HumanInventory.boots
import cn.nukkit.inventory.HumanInventory.setBoots
import cn.nukkit.inventory.HumanInventory.heldItemIndex
import cn.nukkit.entity.effect.PotionType.Companion.get
import cn.nukkit.entity.Entity.getServer
import cn.nukkit.inventory.HumanInventory.canAddItem
import cn.nukkit.inventory.HumanInventory.addItem
import cn.nukkit.entity.EntityVariant.setVariant
import cn.nukkit.entity.effect.PotionType.equals
import cn.nukkit.entity.effect.PotionType.getRomanLevel
import cn.nukkit.entity.effect.PotionType.applyEffects
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident.setItem
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident.setPickupMode
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident.setFavoredSlot
import cn.nukkit.entity.Entity.close
import cn.nukkit.inventory.Inventory.removeItem
import cn.nukkit.event.entity.EntityShootCrossbowEvent.getProjectile
import cn.nukkit.entity.item.EntityPainting.PaintingPlacePredicate.test
import cn.nukkit.inventory.BaseInventory.decreaseCount
import cn.nukkit.entity.Entity.Companion.getDefaultNBT
import cn.nukkit.entity.Entity.removeAllEffects
import cn.nukkit.entity.Entity.isInsideOfWater
import cn.nukkit.entity.Entity.teleport
import cn.nukkit.entity.Entity.getBoundingBox
import cn.nukkit.entity.item.EntityAreaEffectCloud.isDragonBreath
import cn.nukkit.entity.item.EntityAreaEffectCloud.setRadius
import cn.nukkit.entity.item.EntityAreaEffectCloud.getRadius
import cn.nukkit.entity.Entity.removeEffect
import cn.nukkit.entity.Entity.getLocator
import cn.nukkit.item.ItemID
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.item.Item.ItemJsonComponents
import cn.nukkit.item.Item.ItemJsonComponents.ItemLock
import cn.nukkit.item.Item.ItemLockMode
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.nbt.tag.IntTag
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.nbt.NBTIO
import java.nio.ByteOrder
import java.io.IOException
import cn.nukkit.tags.ItemTags
import cn.nukkit.block.BlockID
import cn.nukkit.math.BlockFace
import it.unimi.dsi.fastutil.ints.Int2IntArrayMap
import cn.nukkit.item.Item.ItemJsonComponents.CanPlaceOn
import cn.nukkit.item.Item.ItemJsonComponents.CanDestory
import cn.nukkit.item.Item.ItemJsonComponents.KeepOnDeath
import cn.nukkit.utils.JSONUtils
import cn.nukkit.item.ConstAirItem
import cn.nukkit.block.BlockAir
import cn.nukkit.math.Vector3f
import cn.nukkit.item.customitem.data.Offset
import cn.nukkit.nbt.tag.FloatTag
import cn.nukkit.item.customitem.data.RenderOffsets
import cn.nukkit.item.customitem.data.CreativeCategory
import cn.nukkit.item.customitem.CustomItemDefinition
import cn.nukkit.item.customitem.CustomItem
import cn.nukkit.item.customitem.ItemCustom
import cn.nukkit.item.ItemFood
import cn.nukkit.item.ItemTool
import cn.nukkit.item.ItemArmor
import cn.nukkit.item.customitem.data.CreativeGroup
import cn.nukkit.item.customitem.CustomItemDefinition.SimpleBuilder
import cn.nukkit.item.customitem.ItemCustomTool
import cn.nukkit.item.customitem.CustomItemDefinition.ToolBuilder
import cn.nukkit.item.customitem.data.DigProperty
import java.util.HashMap
import cn.nukkit.item.customitem.ItemCustomArmor
import cn.nukkit.item.customitem.CustomItemDefinition.ArmorBuilder
import cn.nukkit.item.customitem.ItemCustomFood
import java.util.concurrent.atomic.AtomicInteger
import cn.nukkit.item.customitem.CustomItemDefinition.EdibleBuilder
import cn.nukkit.item.ItemEnchantedBook
import cn.nukkit.item.randomitem.EnchantmentItemSelector
import cn.nukkit.item.randomitem.RandomItem
import cn.nukkit.item.randomitem.Fishing
import cn.nukkit.item.randomitem.ConstantItemSelector
import cn.nukkit.item.randomitem.fishing.FishingEnchantmentItemSelector
import cn.nukkit.math.NukkitMath
import cn.nukkit.item.enchantment.Enchantment.Rarity
import cn.nukkit.item.enchantment.EnchantmentType
import cn.nukkit.entity.EntityLiving
import cn.nukkit.entity.projectile.EntityProjectile
import cn.nukkit.item.ItemBow
import cn.nukkit.item.enchantment.bow.EnchantmentBow
import cn.nukkit.item.enchantment.loot.EnchantmentLoot
import cn.nukkit.item.enchantment.damage.EnchantmentDamage
import cn.nukkit.entity.EntitySmite
import cn.nukkit.entity.EntityArthropod
import cn.nukkit.event.entity.EntityDamageByEntityEvent
import cn.nukkit.item.enchantment.trident.EnchantmentTrident
import cn.nukkit.item.enchantment.crossbow.EnchantmentCrossbow
import cn.nukkit.item.ItemElytra
import cn.nukkit.item.enchantment.protection.EnchantmentProtection
import cn.nukkit.event.entity.EntityDamageEvent
import cn.nukkit.event.entity.EntityDamageEvent.DamageCause
import cn.nukkit.item.enchantment.protection.EnchantmentProtectionAll
import cn.nukkit.item.enchantment.protection.EnchantmentProtectionFire
import cn.nukkit.item.enchantment.protection.EnchantmentProtectionFall
import cn.nukkit.item.enchantment.protection.EnchantmentProtectionExplosion
import cn.nukkit.item.enchantment.protection.EnchantmentProtectionProjectile
import cn.nukkit.item.enchantment.EnchantmentThorns
import cn.nukkit.item.enchantment.EnchantmentWaterBreath
import cn.nukkit.item.enchantment.EnchantmentWaterWorker
import cn.nukkit.item.enchantment.EnchantmentWaterWalker
import cn.nukkit.item.enchantment.damage.EnchantmentDamageAll
import cn.nukkit.item.enchantment.damage.EnchantmentDamageSmite
import cn.nukkit.item.enchantment.damage.EnchantmentDamageArthropods
import cn.nukkit.item.enchantment.EnchantmentKnockback
import cn.nukkit.item.enchantment.EnchantmentFireAspect
import cn.nukkit.item.enchantment.loot.EnchantmentLootWeapon
import cn.nukkit.item.enchantment.EnchantmentEfficiency
import cn.nukkit.item.enchantment.EnchantmentSilkTouch
import cn.nukkit.item.enchantment.EnchantmentDurability
import cn.nukkit.item.enchantment.loot.EnchantmentLootDigging
import cn.nukkit.item.enchantment.bow.EnchantmentBowPower
import cn.nukkit.item.enchantment.bow.EnchantmentBowKnockback
import cn.nukkit.item.enchantment.bow.EnchantmentBowFlame
import cn.nukkit.item.enchantment.bow.EnchantmentBowInfinity
import cn.nukkit.item.enchantment.loot.EnchantmentLootFishing
import cn.nukkit.item.enchantment.EnchantmentLure
import cn.nukkit.item.enchantment.EnchantmentFrostWalker
import cn.nukkit.item.enchantment.EnchantmentMending
import cn.nukkit.item.enchantment.EnchantmentBindingCurse
import cn.nukkit.item.enchantment.EnchantmentVanishingCurse
import cn.nukkit.item.enchantment.trident.EnchantmentTridentImpaling
import cn.nukkit.item.enchantment.trident.EnchantmentTridentRiptide
import cn.nukkit.item.enchantment.trident.EnchantmentTridentLoyalty
import cn.nukkit.item.enchantment.trident.EnchantmentTridentChanneling
import cn.nukkit.item.enchantment.crossbow.EnchantmentCrossbowMultishot
import cn.nukkit.item.enchantment.crossbow.EnchantmentCrossbowPiercing
import cn.nukkit.item.enchantment.crossbow.EnchantmentCrossbowQuickCharge
import cn.nukkit.item.enchantment.EnchantmentSoulSpeed
import cn.nukkit.item.enchantment.EnchantmentSwiftSneak
import cn.nukkit.item.enchantment.EnchantmentDensity
import cn.nukkit.item.enchantment.EnchantmentBreach
import cn.nukkit.utils.OK
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.registry.RegisterException
import cn.nukkit.item.enchantment.Enchantment.UnknownEnchantment
import java.util.LinkedHashSet
import java.util.HashSet
import cn.nukkit.item.enchantment.EnchantmentEntry
import cn.nukkit.item.enchantment.EnchantmentList
import cn.nukkit.item.ItemBook
import cn.nukkit.item.ItemTrident
import cn.nukkit.item.ItemFishingRod
import cn.nukkit.item.ItemHead
import cn.nukkit.block.BlockCarvedPumpkin
import cn.nukkit.item.ItemCrossbow
import cn.nukkit.item.ItemMace
import cn.nukkit.event.entity.EntityDamageEvent.DamageModifier
import cn.nukkit.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import cn.nukkit.utils.random.NukkitRandom
import cn.nukkit.item.enchantment.EnchantmentHelper
import java.util.concurrent.atomic.AtomicReference
import cn.nukkit.entity.EntityHumanType
import cn.nukkit.event.entity.EntityCombustByEntityEvent
import cn.nukkit.utils.DyeColor
import cn.nukkit.block.BlockBed
import cn.nukkit.item.ItemArrow
import cn.nukkit.entity.projectile.abstract_arrow.EntityArrow
import cn.nukkit.event.entity.EntityShootBowEvent
import cn.nukkit.level.Sound
import cn.nukkit.event.entity.ProjectileLaunchEvent
import cn.nukkit.item.ItemFish
import cn.nukkit.item.ProjectileItem
import cn.nukkit.block.BlockFlowingWater
import cn.nukkit.entity.item.EntityBoat
import cn.nukkit.item.ItemBlock
import cn.nukkit.block.BlockDirt
import cn.nukkit.event.player.PlayerItemConsumeEvent
import cn.nukkit.network.protocol.CompletedUsingItemPacket
import cn.nukkit.level.vibration.VibrationType
import cn.nukkit.block.BlockSand
import cn.nukkit.item.ItemDurable
import cn.nukkit.event.item.ItemWearEvent
import cn.nukkit.nbt.tag.ByteTag
import cn.nukkit.block.BlockAnvil
import cn.nukkit.item.ItemPotion
import cn.nukkit.block.BlockStandingBanner
import cn.nukkit.block.property.CommonBlockProperties
import cn.nukkit.network.protocol.types.BannerPattern
import cn.nukkit.entity.EntityID
import cn.nukkit.item.ItemBucket
import cn.nukkit.block.BlockPowderSnow
import cn.nukkit.block.BlockLiquid
import cn.nukkit.block.BlockFlowingLava
import cn.nukkit.event.player.PlayerBucketFillEvent
import cn.nukkit.event.player.PlayerBucketEmptyEvent
import cn.nukkit.network.protocol.UpdateBlockPacket
import cn.nukkit.network.protocol.LevelSoundEventPacket
import cn.nukkit.level.particle.ExplodeParticle
import cn.nukkit.entity.EntityVariant
import cn.nukkit.item.ItemDye
import cn.nukkit.item.ItemGlassBottle
import cn.nukkit.item.ItemBanner
import cn.nukkit.item.ItemBoat
import cn.nukkit.item.ItemSign
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident
import cn.nukkit.item.ItemFireworkRocket
import cn.nukkit.entity.item.EntityCrossbowFirework
import cn.nukkit.event.entity.EntityShootCrossbowEvent
import cn.nukkit.utils.Rail
import cn.nukkit.block.BlockRail
import cn.nukkit.entity.item.EntityMinecart
import cn.nukkit.level.format.IChunk
import cn.nukkit.entity.item.EntityPainting.Motive
import cn.nukkit.entity.item.EntityPainting
import cn.nukkit.item.ItemPainting
import cn.nukkit.event.entity.CreatureSpawnEvent
import cn.nukkit.event.entity.CreatureSpawnEvent.SpawnReason
import cn.nukkit.entity.item.EntityChestBoat
import cn.nukkit.item.ItemCod
import java.awt.image.BufferedImage
import cn.nukkit.item.ItemFilledMap
import javax.imageio.ImageIO
import java.awt.Graphics2D
import java.io.ByteArrayInputStream
import cn.nukkit.network.protocol.ClientboundMapItemDataPacket
import cn.nukkit.item.ItemBundle
import cn.nukkit.block.BlockSandstone
import cn.nukkit.math.SimpleAxisAlignedBB
import cn.nukkit.entity.mob.EntityArmorStand
import cn.nukkit.math.CompassRoseDirection
import cn.nukkit.item.ItemColorArmor
import cn.nukkit.utils.BlockColor
import cn.nukkit.block.BlockBedrock
import cn.nukkit.block.BlockObsidian
import cn.nukkit.entity.projectile.throwable.EntityEnderPearl
import cn.nukkit.block.BlockFire
import cn.nukkit.event.block.BlockIgniteEvent
import cn.nukkit.network.protocol.LevelEventPacket
import cn.nukkit.item.ItemMusicDisc
import cn.nukkit.item.ItemBowl
import cn.nukkit.block.BlockOakSlab
import cn.nukkit.block.property.enums.MinecraftVerticalHalf
import org.chorus.block.property.type.EnumPropertyType
import cn.nukkit.block.BlockSpruceSlab
import cn.nukkit.block.BlockBirchSlab
import cn.nukkit.block.BlockJungleSlab
import cn.nukkit.block.BlockAcaciaSlab
import cn.nukkit.block.BlockDarkOakSlab
import cn.nukkit.network.protocol.LevelSoundEventPacketV2
import cn.nukkit.item.ItemSpawnEgg
import cn.nukkit.event.player.PlayerTeleportEvent
import cn.nukkit.entity.item.EntityAreaEffectCloud
import cn.nukkit.item.ItemDragonBreath
import cn.nukkit.block.BlockBeehive
import cn.nukkit.block.BlockCaveVines
import cn.nukkit.block.property.type.IntPropertyType
import cn.nukkit.entity.item.EntityTntMinecart
import cn.nukkit.item.ItemBookWritable
import cn.nukkit.item.ItemWrittenBook
import cn.nukkit.item.ItemSalmon
import cn.nukkit.item.ItemChestBoat
import cn.nukkit.block.BlockSweetBerryBush
import cn.nukkit.network.protocol.types.BannerPatternType
import cn.nukkit.entity.item.EntityChestMinecart
import cn.nukkit.item.ItemFireworkRocket.FireworkExplosion
import cn.nukkit.entity.item.EntityFireworksRocket
import cn.nukkit.entity.item.EntityElytraFirework
import cn.nukkit.item.ItemFireworkRocket.FireworkExplosion.ExplosionType
import cn.nukkit.entity.item.EntityHopperMinecart
import cn.nukkit.item.ItemHangingSign
import cn.nukkit.item.ItemPotato
import cn.nukkit.item.ItemPotterySherd
import cn.nukkit.positiontracking.NamedPosition
import cn.nukkit.item.ItemBannerPattern

