/**
 * 各种工具类.
 *
 *
 * Some tool classes.
 */
package org.chorus.utils

import org.chorus.math.Vector3.floorX
import org.chorus.math.Vector3.floorY
import org.chorus.math.Vector3.floorZ
import org.chorus.math.IntIncrementSupplier.stream
import org.chorus.math.NukkitMath.floorFloat
import org.chorus.math.NukkitMath.floorDouble
import org.chorus.math.AxisAlignedBB.minX
import org.chorus.math.AxisAlignedBB.maxX
import org.chorus.math.AxisAlignedBB.minY
import org.chorus.math.AxisAlignedBB.maxY
import org.chorus.math.AxisAlignedBB.minZ
import org.chorus.math.AxisAlignedBB.maxZ
import org.chorus.level.Level.getBlock
import org.chorus.math.Vector3.setComponents
import org.chorus.math.NukkitMath.ceilDouble
import org.chorus.level.Level.getTickCachedBlock
import org.chorus.entity.data.EntityDataMap.size
import org.chorus.entity.data.EntityDataMap.entrySet
import org.chorus.entity.data.EntityDataType.getValue
import org.chorus.entity.data.EntityDataType.getTransformer
import org.chorus.nbt.NBTIO.write
import org.chorus.math.NukkitMath.round
import org.chorus.scheduler.ServerScheduler.scheduleAsyncTask
import org.chorus.math.MathHelper.clamp
import org.chorus.network.Network.resetStatistics
import org.chorus.nbt.tag.CompoundTag.putInt
import org.chorus.nbt.tag.CompoundTag.putString
import org.chorus.nbt.tag.CompoundTag.putByte
import org.chorus.nbt.tag.CompoundTag.putCompound
import org.chorus.nbt.tag.CompoundTag.getString
import org.chorus.nbt.tag.CompoundTag.getCompound
import org.chorus.nbt.tag.CompoundTag.getTags
import org.chorus.nbt.tag.CompoundTag.put
import org.chorus.nbt.tag.CompoundTag.contains
import org.chorus.nbt.tag.CompoundTag.remove
import org.chorus.nbt.tag.ListTag.size
import org.chorus.nbt.tag.ListTag.get
import org.chorus.nbt.tag.ListTag.add
import org.chorus.nbt.NBTIO.read
import org.chorus.registry.EntityRegistry.getEntityNetworkId
import org.chorus.entity.data.EntityDataMap.getOrCreateFlags
import org.chorus.entity.data.EntityDataMap.put
import org.chorus.entity.Attribute.Companion.getAttribute
import org.chorus.entity.Attribute.setMaxValue
import org.chorus.entity.Attribute.setValue
import org.chorus.level.Level.setBlock
import org.chorus.level.Level.dimensionData
import org.chorus.level.Level.scanBlocks
import org.chorus.math.Vector2.distanceSquared
import org.chorus.level.Level.dimension
import org.chorus.math.NukkitMath.clamp
import org.chorus.level.Level.spawnLocation
import org.chorus.math.BlockFace.getOpposite
import org.chorus.plugin.PluginManager.getPlugin
import org.chorus.plugin.PluginManager.enablePlugin
import org.chorus.plugin.PluginManager.loadPlugin
import org.chorus.network.protocol.LoginPacket.buffer
import org.chorus.network.connection.util.EncryptionUtils.mojangPublicKey
import org.chorus.network.connection.util.EncryptionUtils.oldMojangPublicKey
import org.chorus.math.Vector3.equals
import org.chorus.math.Vector3.hashCode
import org.chorus.level.Locator.levelBlock
import org.chorus.level.Locator.getSide
import org.chorus.item.Item.getCount
import org.chorus.nbt.tag.CompoundTag.putShort
import org.chorus.item.Item.damage
import org.chorus.item.Item.id
import org.chorus.nbt.tag.CompoundTag.putBoolean
import org.chorus.nbt.tag.CompoundTag.putFloat
import org.chorus.item.Item.hasCompoundTag
import org.chorus.item.Item.namedTag
import org.chorus.nbt.tag.CompoundTag.getInt
import org.chorus.utils.random.RandomSourceProvider
import org.apache.commons.rng.RestorableUniformRandomProvider
import org.apache.commons.rng.sampling.distribution.ContinuousSampler
import org.apache.commons.rng.simple.RandomSource
import org.apache.commons.rng.sampling.distribution.GaussianSampler
import org.apache.commons.rng.sampling.distribution.ZigguratSampler
import org.chorus.utils.random.NukkitRandom
import org.chorus.utils.OK
import org.chorus.utils.version.VersionStringComparator
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import java.util.HashSet
import java.time.ZoneId
import org.chorus.utils.Rail
import org.chorus.math.BlockFace
import org.chorus.utils.collection.nb.ConcurrentAutoIntTable
import java.util.concurrent.atomic.AtomicReferenceFieldUpdater
import org.chorus.utils.collection.nb.ConcurrentAutoLongTable
import org.chorus.api.NonComputationAtomic
import org.chorus.utils.collection.nb.Int2ObjectNonBlockingMap
import java.util.concurrent.ConcurrentMap
import java.util.concurrent.atomic.AtomicLongFieldUpdater
import java.util.Enumeration
import java.util.NoSuchElementException
import org.chorus.utils.collection.nb.Int2ObjectNonBlockingMap.IteratorInteger
import org.chorus.utils.collection.nb.IntObjectEntry
import java.io.Serial
import java.io.IOException
import java.io.ObjectOutputStream
import java.io.ObjectInputStream
import java.util.function.BiFunction
import org.chorus.utils.collection.nb.Long2ObjectNonBlockingMap
import org.chorus.utils.collection.nb.Long2ObjectNonBlockingMap.IteratorLong
import org.chorus.utils.collection.nb.LongObjectEntry
import net.jpountz.lz4.LZ4Factory
import net.jpountz.lz4.LZ4Compressor
import org.chorus.utils.collection.LZ4Freezer
import net.jpountz.lz4.LZ4FastDecompressor
import org.chorus.utils.collection.AutoFreezable.FreezeStatus
import org.chorus.utils.collection.ShouldThaw
import java.util.concurrent.atomic.AtomicLong
import org.chorus.utils.collection.AutoFreezable
import org.chorus.utils.collection.FreezableArrayManager
import java.util.concurrent.atomic.AtomicReference
import org.chorus.utils.collection.ConvertingSetWrapper
import org.chorus.utils.collection.FreezableByteArray
import org.chorus.utils.collection.PureByteArray
import java.util.concurrent.locks.ReadWriteLock
import java.util.concurrent.locks.ReentrantReadWriteLock
import org.chorus.utils.functional.BlockPositionConsumer
import org.chorus.math.IntIncrementSupplier
import org.chorus.math.NukkitMath
import org.chorus.utils.functional.ToIntTriFunctionOneInt
import org.chorus.utils.functional.ToIntTriFunctionTwoInts
import org.chorus.utils.functional.ToLongTriFunctionOneLong
import org.chorus.utils.functional.ToLongTriFunctionOneIntOneLong
import java.util.SplittableRandom
import java.io.ByteArrayInputStream
import java.io.FileOutputStream
import java.io.FileNotFoundException
import java.io.FileInputStream
import java.io.BufferedReader
import java.nio.channels.FileChannel
import java.io.PrintWriter
import java.nio.file.SimpleFileVisitor
import java.nio.file.attribute.BasicFileAttributes
import org.chorus.math.AxisAlignedBB
import io.netty.buffer.ByteBuf
import org.chorus.entity.data.EntityDataMap
import org.chorus.entity.data.EntityDataType
import org.chorus.entity.data.EntityDataFormat
import org.chorus.nbt.NBTIO
import org.chorus.nbt.tag.CompoundTag
import java.nio.ByteOrder
import org.chorus.math.BlockVector3
import org.chorus.math.Vector3f
import org.chorus.utils.ConfigSection
import org.chorus.plugin.InternalPlugin
import org.chorus.scheduler.FileWriteTask
import org.chorus.utils.JSONUtils
import java.util.TreeMap
import org.chorus.utils.VarInt
import lombok.experimental.UtilityClass
import java.security.MessageDigest
import java.security.NoSuchAlgorithmException
import org.chorus.utils.BlockColor
import org.chorus.utils.DyeColor
import org.chorus.math.MathHelper
import org.chorus.utils.GameLoop
import java.util.concurrent.atomic.AtomicBoolean
import org.chorus.utils.GameLoop.GameLoopBuilder
import org.chorus.utils.MainLogger
import org.chorus.block.property.type.BlockPropertyType.BlockPropertyValue
import org.chorus.block.BlockID
import org.chorus.nbt.tag.TreeMapCompoundTag
import org.chorus.block.property.type.BlockPropertyType
import lombok.SneakyThrows
import org.chorus.utils.JSONUtils.GsonException
import java.util.HashMap
import java.io.FileWriter
import org.chorus.utils.exception.FormativeRuntimeException
import org.chorus.utils.InvalidIdentifierException
import lombok.NoArgsConstructor
import lombok.AccessLevel
import org.chorus.utils.ThreadedLogger
import org.chorus.nbt.tag.ListTag
import org.chorus.nbt.tag.IntTag
import org.chorus.utils.SemVersion
import java.util.ConcurrentModificationException
import org.chorus.utils.ThreadCache
import org.chorus.utils.IterableThreadLocal
import org.chorus.utils.OptionalValue
import org.chorus.utils.BossBarColor
import org.chorus.utils.DummyBossBar
import org.chorus.network.protocol.AddEntityPacket
import org.chorus.entity.EntityID
import org.chorus.network.protocol.UpdateAttributesPacket
import org.chorus.network.protocol.BossEventPacket
import org.chorus.network.protocol.MoveEntityAbsolutePacket
import org.chorus.network.protocol.SetEntityDataPacket
import org.chorus.network.protocol.RemoveEntityPacket
import org.chorus.utils.MinecartType
import org.chorus.math.SimpleAxisAlignedBB
import java.util.function.BiPredicate
import org.chorus.level.DimensionData
import org.chorus.level.DimensionEnum
import org.chorus.utils.SimpleConfig
import org.chorus.utils.ByteBufVarInt
import org.chorus.utils.CleanerHandle
import org.chorus.utils.CleanerHandle.CleanerTask
import java.util.LinkedHashSet
import org.chorus.utils.SerializedImage
import org.chorus.Nukkit
import org.chorus.utils.UUIDValidator
import cn.powernukkitx.libdeflate.LibdeflateCompressor
import cn.powernukkitx.libdeflate.LibdeflateDecompressor
import org.chorus.utils.LoginChainData
import org.chorus.utils.ClientChainData
import org.chorus.network.connection.util.EncryptionUtils
import org.jose4j.lang.JoseException
import org.chorus.network.protocol.LoginPacket
import java.security.spec.InvalidKeySpecException
import java.security.spec.X509EncodedKeySpec
import org.chorus.utils.HastebinUtility
import org.chorus.utils.OptionalBoolean
import org.chorus.utils.TerracottaColor
import org.chorus.utils.BlockUpdateEntry
import java.util.function.BinaryOperator
import it.unimi.dsi.fastutil.objects.Object2IntLinkedOpenHashMap
import org.chorus.utils.NumberConversions
import org.chorus.utils.RedstoneComponent
import java.util.concurrent.ConcurrentLinkedDeque
import org.chorus.utils.HumanStringComparator
import org.chorus.utils.TradeRecipeBuildUtils
import org.chorus.utils.TickCachedBlockIterator
import java.nio.channels.SeekableByteChannel
import java.nio.channels.ClosedChannelException
import org.chorus.utils.MinecraftNamespaceComparator
import io.netty.buffer.ByteBufInputStream
import io.netty.buffer.ByteBufOutputStream
import io.netty.buffer.ByteBufUtil

