/**
 * 各种工具类.
 *
 *
 * Some tool classes.
 */
package org.chorus.utils

import cn.nukkit.math.Vector3.floorX
import cn.nukkit.math.Vector3.floorY
import cn.nukkit.math.Vector3.floorZ
import cn.nukkit.math.IntIncrementSupplier.stream
import cn.nukkit.math.NukkitMath.floorFloat
import cn.nukkit.math.NukkitMath.floorDouble
import cn.nukkit.math.AxisAlignedBB.minX
import cn.nukkit.math.AxisAlignedBB.maxX
import cn.nukkit.math.AxisAlignedBB.minY
import cn.nukkit.math.AxisAlignedBB.maxY
import cn.nukkit.math.AxisAlignedBB.minZ
import cn.nukkit.math.AxisAlignedBB.maxZ
import cn.nukkit.level.Level.getBlock
import cn.nukkit.math.Vector3.setComponents
import cn.nukkit.math.NukkitMath.ceilDouble
import cn.nukkit.level.Level.getTickCachedBlock
import cn.nukkit.entity.data.EntityDataMap.size
import cn.nukkit.entity.data.EntityDataMap.entrySet
import cn.nukkit.entity.data.EntityDataType.getValue
import cn.nukkit.entity.data.EntityDataType.getTransformer
import cn.nukkit.nbt.NBTIO.write
import cn.nukkit.math.NukkitMath.round
import cn.nukkit.scheduler.ServerScheduler.scheduleAsyncTask
import cn.nukkit.math.MathHelper.clamp
import cn.nukkit.network.Network.resetStatistics
import cn.nukkit.nbt.tag.CompoundTag.putInt
import cn.nukkit.nbt.tag.CompoundTag.putString
import cn.nukkit.nbt.tag.CompoundTag.putByte
import cn.nukkit.nbt.tag.CompoundTag.putCompound
import cn.nukkit.nbt.tag.CompoundTag.getString
import cn.nukkit.nbt.tag.CompoundTag.getCompound
import cn.nukkit.nbt.tag.CompoundTag.getTags
import cn.nukkit.nbt.tag.CompoundTag.put
import cn.nukkit.nbt.tag.CompoundTag.contains
import cn.nukkit.nbt.tag.CompoundTag.remove
import cn.nukkit.nbt.tag.ListTag.size
import cn.nukkit.nbt.tag.ListTag.get
import cn.nukkit.nbt.tag.ListTag.add
import cn.nukkit.nbt.NBTIO.read
import cn.nukkit.registry.EntityRegistry.getEntityNetworkId
import cn.nukkit.entity.data.EntityDataMap.getOrCreateFlags
import cn.nukkit.entity.data.EntityDataMap.put
import cn.nukkit.entity.Attribute.Companion.getAttribute
import cn.nukkit.entity.Attribute.setMaxValue
import cn.nukkit.entity.Attribute.setValue
import cn.nukkit.level.Level.setBlock
import cn.nukkit.level.Level.dimensionData
import cn.nukkit.level.Level.scanBlocks
import cn.nukkit.math.Vector2.distanceSquared
import cn.nukkit.level.Level.dimension
import cn.nukkit.math.NukkitMath.clamp
import cn.nukkit.level.Level.spawnLocation
import cn.nukkit.math.BlockFace.getOpposite
import cn.nukkit.plugin.PluginManager.getPlugin
import cn.nukkit.plugin.PluginManager.enablePlugin
import cn.nukkit.plugin.PluginManager.loadPlugin
import cn.nukkit.network.protocol.LoginPacket.buffer
import cn.nukkit.network.connection.util.EncryptionUtils.mojangPublicKey
import cn.nukkit.network.connection.util.EncryptionUtils.oldMojangPublicKey
import cn.nukkit.math.Vector3.equals
import cn.nukkit.math.Vector3.hashCode
import cn.nukkit.level.Locator.levelBlock
import cn.nukkit.level.Locator.getSide
import cn.nukkit.item.Item.getCount
import cn.nukkit.nbt.tag.CompoundTag.putShort
import cn.nukkit.item.Item.damage
import cn.nukkit.item.Item.id
import cn.nukkit.nbt.tag.CompoundTag.putBoolean
import cn.nukkit.nbt.tag.CompoundTag.putFloat
import cn.nukkit.item.Item.hasCompoundTag
import cn.nukkit.item.Item.namedTag
import cn.nukkit.nbt.tag.CompoundTag.getInt
import cn.nukkit.utils.random.RandomSourceProvider
import org.apache.commons.rng.RestorableUniformRandomProvider
import org.apache.commons.rng.sampling.distribution.ContinuousSampler
import org.apache.commons.rng.simple.RandomSource
import org.apache.commons.rng.sampling.distribution.GaussianSampler
import org.apache.commons.rng.sampling.distribution.ZigguratSampler
import cn.nukkit.utils.random.NukkitRandom
import cn.nukkit.utils.OK
import cn.nukkit.utils.version.VersionStringComparator
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import java.util.HashSet
import java.time.ZoneId
import cn.nukkit.utils.Rail
import cn.nukkit.math.BlockFace
import cn.nukkit.utils.collection.nb.ConcurrentAutoIntTable
import java.util.concurrent.atomic.AtomicReferenceFieldUpdater
import cn.nukkit.utils.collection.nb.ConcurrentAutoLongTable
import cn.nukkit.api.NonComputationAtomic
import cn.nukkit.utils.collection.nb.Int2ObjectNonBlockingMap
import java.util.concurrent.ConcurrentMap
import java.util.concurrent.atomic.AtomicLongFieldUpdater
import java.util.Enumeration
import java.util.NoSuchElementException
import cn.nukkit.utils.collection.nb.Int2ObjectNonBlockingMap.IteratorInteger
import cn.nukkit.utils.collection.nb.IntObjectEntry
import java.io.Serial
import java.io.IOException
import java.io.ObjectOutputStream
import java.io.ObjectInputStream
import java.util.function.BiFunction
import cn.nukkit.utils.collection.nb.Long2ObjectNonBlockingMap
import cn.nukkit.utils.collection.nb.Long2ObjectNonBlockingMap.IteratorLong
import cn.nukkit.utils.collection.nb.LongObjectEntry
import net.jpountz.lz4.LZ4Factory
import net.jpountz.lz4.LZ4Compressor
import cn.nukkit.utils.collection.LZ4Freezer
import net.jpountz.lz4.LZ4FastDecompressor
import cn.nukkit.utils.collection.AutoFreezable.FreezeStatus
import cn.nukkit.utils.collection.ShouldThaw
import java.util.concurrent.atomic.AtomicLong
import cn.nukkit.utils.collection.AutoFreezable
import cn.nukkit.utils.collection.FreezableArrayManager
import java.util.concurrent.atomic.AtomicReference
import cn.nukkit.utils.collection.ConvertingSetWrapper
import cn.nukkit.utils.collection.FreezableByteArray
import cn.nukkit.utils.collection.PureByteArray
import java.util.concurrent.locks.ReadWriteLock
import java.util.concurrent.locks.ReentrantReadWriteLock
import cn.nukkit.utils.functional.BlockPositionConsumer
import cn.nukkit.math.IntIncrementSupplier
import cn.nukkit.math.NukkitMath
import cn.nukkit.utils.functional.ToIntTriFunctionOneInt
import cn.nukkit.utils.functional.ToIntTriFunctionTwoInts
import cn.nukkit.utils.functional.ToLongTriFunctionOneLong
import cn.nukkit.utils.functional.ToLongTriFunctionOneIntOneLong
import java.util.SplittableRandom
import java.io.ByteArrayInputStream
import java.io.FileOutputStream
import java.io.FileNotFoundException
import java.io.FileInputStream
import java.io.BufferedReader
import java.nio.channels.FileChannel
import java.io.PrintWriter
import java.nio.file.SimpleFileVisitor
import java.nio.file.attribute.BasicFileAttributes
import cn.nukkit.math.AxisAlignedBB
import io.netty.buffer.ByteBuf
import cn.nukkit.entity.data.EntityDataMap
import cn.nukkit.entity.data.EntityDataType
import cn.nukkit.entity.data.EntityDataFormat
import cn.nukkit.nbt.NBTIO
import cn.nukkit.nbt.tag.CompoundTag
import java.nio.ByteOrder
import cn.nukkit.math.BlockVector3
import cn.nukkit.math.Vector3f
import cn.nukkit.utils.ConfigSection
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.scheduler.FileWriteTask
import cn.nukkit.utils.JSONUtils
import java.util.TreeMap
import cn.nukkit.utils.VarInt
import lombok.experimental.UtilityClass
import java.security.MessageDigest
import java.security.NoSuchAlgorithmException
import cn.nukkit.utils.BlockColor
import cn.nukkit.utils.DyeColor
import cn.nukkit.math.MathHelper
import cn.nukkit.utils.GameLoop
import java.util.concurrent.atomic.AtomicBoolean
import cn.nukkit.utils.GameLoop.GameLoopBuilder
import cn.nukkit.utils.MainLogger
import cn.nukkit.block.property.type.BlockPropertyType.BlockPropertyValue
import cn.nukkit.block.BlockID
import cn.nukkit.nbt.tag.TreeMapCompoundTag
import cn.nukkit.block.property.type.BlockPropertyType
import lombok.SneakyThrows
import cn.nukkit.utils.JSONUtils.GsonException
import java.util.HashMap
import java.io.FileWriter
import cn.nukkit.utils.exception.FormativeRuntimeException
import cn.nukkit.utils.InvalidIdentifierException
import lombok.NoArgsConstructor
import lombok.AccessLevel
import cn.nukkit.utils.ThreadedLogger
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.nbt.tag.IntTag
import cn.nukkit.utils.SemVersion
import java.util.ConcurrentModificationException
import cn.nukkit.utils.ThreadCache
import cn.nukkit.utils.IterableThreadLocal
import cn.nukkit.utils.OptionalValue
import cn.nukkit.utils.BossBarColor
import cn.nukkit.utils.DummyBossBar
import cn.nukkit.network.protocol.AddEntityPacket
import cn.nukkit.entity.EntityID
import cn.nukkit.network.protocol.UpdateAttributesPacket
import cn.nukkit.network.protocol.BossEventPacket
import cn.nukkit.network.protocol.MoveEntityAbsolutePacket
import cn.nukkit.network.protocol.SetEntityDataPacket
import cn.nukkit.network.protocol.RemoveEntityPacket
import cn.nukkit.utils.MinecartType
import cn.nukkit.math.SimpleAxisAlignedBB
import java.util.function.BiPredicate
import cn.nukkit.level.DimensionData
import cn.nukkit.level.DimensionEnum
import cn.nukkit.utils.SimpleConfig
import cn.nukkit.utils.ByteBufVarInt
import cn.nukkit.utils.CleanerHandle
import cn.nukkit.utils.CleanerHandle.CleanerTask
import java.util.LinkedHashSet
import cn.nukkit.utils.SerializedImage
import cn.nukkit.Nukkit
import cn.nukkit.utils.UUIDValidator
import cn.powernukkitx.libdeflate.LibdeflateCompressor
import cn.powernukkitx.libdeflate.LibdeflateDecompressor
import cn.nukkit.utils.LoginChainData
import cn.nukkit.utils.ClientChainData
import cn.nukkit.network.connection.util.EncryptionUtils
import org.jose4j.lang.JoseException
import cn.nukkit.network.protocol.LoginPacket
import java.security.spec.InvalidKeySpecException
import java.security.spec.X509EncodedKeySpec
import cn.nukkit.utils.HastebinUtility
import cn.nukkit.utils.OptionalBoolean
import cn.nukkit.utils.TerracottaColor
import cn.nukkit.utils.BlockUpdateEntry
import java.util.function.BinaryOperator
import it.unimi.dsi.fastutil.objects.Object2IntLinkedOpenHashMap
import cn.nukkit.utils.NumberConversions
import cn.nukkit.utils.RedstoneComponent
import java.util.concurrent.ConcurrentLinkedDeque
import cn.nukkit.utils.HumanStringComparator
import cn.nukkit.utils.TradeRecipeBuildUtils
import cn.nukkit.utils.TickCachedBlockIterator
import java.nio.channels.SeekableByteChannel
import java.nio.channels.ClosedChannelException
import cn.nukkit.utils.MinecraftNamespaceComparator
import io.netty.buffer.ByteBufInputStream
import io.netty.buffer.ByteBufOutputStream
import io.netty.buffer.ByteBufUtil

