/**
 * 与事件相关的类,事件在指定代码触发.
 *
 *
 * Classes relevant to event,events are emitted in the specified code.
 */
package org.chorus.event

import cn.nukkit.blockentity.BlockEntity.block
import cn.nukkit.blockentity.BlockEntityLectern.totalPages
import cn.nukkit.entity.Entity.getNetworkId
import cn.nukkit.entity.Entity.getLocator
import cn.nukkit.entity.Entity.hasEffect
import cn.nukkit.entity.Entity.getEffect
import cn.nukkit.entity.effect.Effect.getLevel
import cn.nukkit.entity.Entity.Companion.getDefaultNBT
import cn.nukkit.entity.Entity.getViewers
import cn.nukkit.entity.Entity.kill
import cn.nukkit.entity.Entity.close
import cn.nukkit.entity.EntityHuman.getName
import cn.nukkit.blockentity.BlockEntityBrewingStand.getInventory
import cn.nukkit.event.HandlerList
import cn.nukkit.event.item.ItemWearEvent
import cn.nukkit.block.BlockBell
import cn.nukkit.event.block.BellRingEvent.RingCause
import cn.nukkit.event.block.BlockEvent
import cn.nukkit.event.block.BellRingEvent
import cn.nukkit.event.block.SignGlowEvent
import cn.nukkit.event.block.BlockBurnEvent
import cn.nukkit.event.block.BlockFadeEvent
import cn.nukkit.event.block.BlockFallEvent
import cn.nukkit.event.block.BlockGrowEvent
import cn.nukkit.event.block.BlockFormEvent
import cn.nukkit.event.block.SignWaxedEvent
import cn.nukkit.math.BlockFace
import cn.nukkit.event.block.BlockBreakEvent
import cn.nukkit.event.block.BlockPlaceEvent
import cn.nukkit.event.block.BlockUpdateEvent
import cn.nukkit.event.block.DoorToggleEvent
import cn.nukkit.block.BlockLiquid
import cn.nukkit.event.block.LiquidFlowEvent
import cn.nukkit.event.block.SignChangeEvent
import cn.nukkit.event.block.WaterFrostEvent
import cn.nukkit.event.block.BlockFromToEvent
import cn.nukkit.event.block.BlockIgniteEvent.BlockIgniteCause
import cn.nukkit.event.block.BlockIgniteEvent
import cn.nukkit.block.BlockPistonBase
import cn.nukkit.event.block.BlockPistonEvent
import cn.nukkit.event.block.BlockSpreadEvent
import cn.nukkit.event.block.LeavesDecayEvent
import cn.nukkit.event.block.BlockExplodeEvent
import cn.nukkit.event.block.BlockHarvestEvent
import cn.nukkit.blockentity.BlockEntityItemFrame
import cn.nukkit.event.block.ItemFrameUseEvent
import cn.nukkit.event.block.BlockRedstoneEvent
import cn.nukkit.event.block.ComposterFillEvent
import cn.nukkit.event.block.FarmLandDecayEvent
import cn.nukkit.event.block.ComposterEmptyEvent
import cn.nukkit.block.BlockTurtleEgg
import cn.nukkit.block.BlockAir
import cn.nukkit.block.property.enums.TurtleEggCount
import cn.nukkit.event.block.TurtleEggHatchEvent
import cn.nukkit.event.block.ConduitActivateEvent
import cn.nukkit.blockentity.BlockEntityLectern
import cn.nukkit.event.block.LecternDropBookEvent
import cn.nukkit.utils.BlockColor
import cn.nukkit.event.block.SignColorChangeEvent
import cn.nukkit.block.BlockHopper.IHopper
import cn.nukkit.event.block.HopperSearchItemEvent
import cn.nukkit.event.block.LecternPlaceBookEvent
import cn.nukkit.event.block.ConduitDeactivateEvent
import cn.nukkit.event.block.LecternPageChangeEvent
import cn.nukkit.event.block.BlockExplosionPrimeEvent
import cn.nukkit.block.property.enums.BigDripleafTilt
import cn.nukkit.event.block.BigDripleafTiltChangeEvent
import cn.nukkit.block.property.enums.CauldronLiquid
import cn.nukkit.event.block.CauldronFilledByDrippingLiquidEvent
import cn.nukkit.level.format.IChunk
import cn.nukkit.event.level.LevelEvent
import cn.nukkit.event.level.ChunkEvent
import cn.nukkit.event.level.ChunkLoadEvent
import cn.nukkit.event.level.LevelInitEvent
import cn.nukkit.event.level.LevelLoadEvent
import cn.nukkit.event.level.LevelSaveEvent
import cn.nukkit.event.level.ChunkUnloadEvent
import cn.nukkit.event.level.LevelUnloadEvent
import cn.nukkit.event.level.SpawnChangeEvent
import cn.nukkit.event.level.StructureGrowEvent
import cn.nukkit.event.level.WeatherEvent
import cn.nukkit.event.level.ThunderChangeEvent
import cn.nukkit.event.level.WeatherChangeEvent
import cn.nukkit.event.level.VibrationOccurEvent
import cn.nukkit.level.vibration.VibrationListener
import cn.nukkit.event.level.VibrationArriveEvent
import cn.nukkit.entity.item.EntityItem
import cn.nukkit.event.entity.EntityEvent
import cn.nukkit.event.entity.ItemSpawnEvent
import cn.nukkit.event.entity.EntityFallEvent
import cn.nukkit.entity.EntityLiving
import cn.nukkit.event.entity.EntityDeathEvent
import cn.nukkit.entity.EntityCreature
import cn.nukkit.entity.EntityHuman
import cn.nukkit.entity.projectile.EntityProjectile
import cn.nukkit.event.entity.ItemDespawnEvent
import cn.nukkit.entity.mob.monster.EntityCreeper
import cn.nukkit.event.entity.CreeperPowerEvent.PowerCause
import cn.nukkit.entity.weather.EntityLightningStrike
import cn.nukkit.event.entity.CreeperPowerEvent
import cn.nukkit.event.entity.EntityDamageEvent.DamageCause
import cn.nukkit.event.entity.EntityDamageEvent.DamageModifier
import cn.nukkit.event.entity.EntityDamageEvent
import cn.nukkit.event.entity.EntityMotionEvent
import cn.nukkit.event.entity.CreatureSpawnEvent.SpawnReason
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.event.entity.CreatureSpawnEvent
import cn.nukkit.event.entity.EntityCombustEvent
import cn.nukkit.event.entity.EntityDespawnEvent
import java.util.HashSet
import cn.nukkit.event.entity.EntityExplodeEvent
import cn.nukkit.level.MovingObjectPosition
import cn.nukkit.event.entity.ProjectileHitEvent
import cn.nukkit.event.entity.EntityInteractEvent
import cn.nukkit.event.entity.EntityShootBowEvent
import cn.nukkit.event.player.PlayerTeleportEvent.TeleportCause
import cn.nukkit.event.entity.EntityTeleportEvent
import cn.nukkit.event.entity.ExplosionPrimeEvent
import cn.nukkit.event.entity.ProjectileLaunchEvent
import cn.nukkit.event.entity.EntityArmorChangeEvent
import cn.nukkit.event.entity.EntityBlockChangeEvent
import cn.nukkit.event.entity.EntityLevelChangeEvent
import cn.nukkit.event.entity.EntityPortalEnterEvent.PortalType
import cn.nukkit.event.entity.EntityPortalEnterEvent
import cn.nukkit.event.entity.EntityVehicleExitEvent
import cn.nukkit.event.entity.EntityEffectRemoveEvent
import cn.nukkit.event.entity.EntityEffectUpdateEvent
import cn.nukkit.event.entity.EntityRegainHealthEvent
import cn.nukkit.event.entity.EntityVehicleEnterEvent
import cn.nukkit.event.entity.EntityDamageBlockedEvent
import cn.nukkit.event.entity.EntityShootCrossbowEvent
import cn.nukkit.event.entity.EntityExplosionPrimeEvent
import cn.nukkit.event.entity.EntityInventoryChangeEvent
import cn.nukkit.event.entity.EntityDamageByEntityEvent
import cn.nukkit.event.player.PlayerMessageEvent
import cn.nukkit.permission.Permissible
import cn.nukkit.event.player.PlayerChatEvent
import cn.nukkit.entity.item.EntityFishingHook
import cn.nukkit.event.player.PlayerEvent
import cn.nukkit.event.player.PlayerFishEvent
import cn.nukkit.lang.TextContainer
import cn.nukkit.event.player.PlayerJoinEvent
import cn.nukkit.event.player.PlayerJumpEvent
import cn.nukkit.event.player.PlayerKickEvent
import cn.nukkit.event.player.PlayerMoveEvent
import cn.nukkit.event.player.PlayerQuitEvent
import cn.nukkit.lang.TranslationContainer
import cn.nukkit.event.player.PlayerDeathEvent
import cn.nukkit.event.player.PlayerLoginEvent
import cn.nukkit.event.player.EntityFreezeEvent
import cn.nukkit.network.protocol.types.SpawnPointType
import cn.nukkit.event.player.PlayerRespawnEvent
import cn.nukkit.event.player.PlayerBedEnterEvent
import cn.nukkit.event.player.PlayerBedLeaveEvent
import cn.nukkit.event.player.PlayerCreationEvent
import cn.nukkit.event.player.PlayerDropItemEvent
import cn.nukkit.network.protocol.BookEditPacket
import cn.nukkit.event.player.PlayerEditBookEvent
import cn.nukkit.math.IVector3
import cn.nukkit.event.player.PlayerInteractEvent
import cn.nukkit.event.player.PlayerItemHeldEvent
import cn.nukkit.event.player.PlayerTeleportEvent
import cn.nukkit.network.protocol.AnimatePacket
import cn.nukkit.event.player.PlayerAnimationEvent
import cn.nukkit.event.player.PlayerBlockPickEvent
import cn.nukkit.event.player.PlayerBucketEvent
import cn.nukkit.event.player.PlayerBucketFillEvent
import cn.nukkit.event.player.PlayerChangeSkinEvent
import cn.nukkit.event.player.PlayerToggleSwimEvent
import cn.nukkit.event.player.PlayerBucketEmptyEvent
import cn.nukkit.event.player.PlayerInvalidMoveEvent
import cn.nukkit.event.player.PlayerItemConsumeEvent
import cn.nukkit.event.player.PlayerShowCreditsEvent
import cn.nukkit.event.player.PlayerToggleGlideEvent
import cn.nukkit.event.player.PlayerToggleSneakEvent
import cn.nukkit.event.player.PlayerChunkRequestEvent
import cn.nukkit.event.player.PlayerHackDetectedEvent.HackType
import cn.nukkit.event.player.PlayerHackDetectedEvent
import cn.nukkit.event.player.PlayerToggleFlightEvent
import cn.nukkit.event.player.PlayerToggleSprintEvent
import cn.nukkit.event.player.PlayerTransferItemEvent
import cn.nukkit.event.player.PlayerFormRespondedEvent
import cn.nukkit.event.player.PlayerIllegalFlightEvent
import cn.nukkit.AdventureSettings
import cn.nukkit.event.player.PlayerGameModeChangeEvent
import cn.nukkit.event.player.PlayerInteractEntityEvent
import cn.nukkit.event.player.PlayerMapInfoRequestEvent
import cn.nukkit.dialog.window.FormWindowDialog
import cn.nukkit.dialog.response.FormResponseDialog
import cn.nukkit.event.player.PlayerDialogRespondedEvent
import cn.nukkit.event.player.PlayerFoodLevelChangeEvent
import cn.nukkit.event.player.PlayerMouseOverEntityEvent
import cn.nukkit.event.player.PlayerChangeArmorStandEvent
import cn.nukkit.event.player.PlayerExperienceChangeEvent
import cn.nukkit.event.player.PlayerToggleSpinAttackEvent
import cn.nukkit.event.player.PlayerCommandPreprocessEvent
import cn.nukkit.event.player.PlayerSettingsRespondedEvent
import cn.nukkit.event.player.PlayerAchievementAwardedEvent
import cn.nukkit.inventory.EnchantInventory
import cn.nukkit.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import cn.nukkit.event.player.PlayerEnchantOptionsRequestEvent
import cn.nukkit.event.player.PlayerServerSettingsRequestEvent
import cn.nukkit.event.plugin.PluginEvent
import cn.nukkit.event.potion.PotionEvent
import cn.nukkit.event.potion.PotionApplyEvent
import cn.nukkit.entity.projectile.throwable.EntitySplashPotion
import cn.nukkit.event.potion.PotionCollideEvent
import cn.nukkit.event.server.ServerEvent
import cn.nukkit.event.server.ServerStopEvent
import cn.nukkit.network.protocol.DataPacket
import cn.nukkit.event.server.BatchPacketsEvent
import cn.nukkit.event.server.ServerCommandEvent
import cn.nukkit.event.server.ServerStartedEvent
import cn.nukkit.event.server.DataPacketSendEvent
import java.util.HashMap
import cn.nukkit.network.protocol.ProtocolInfo
import io.netty.buffer.ByteBuf
import io.netty.buffer.ByteBufAllocator
import cn.nukkit.plugin.PluginDescription
import cn.nukkit.event.server.QueryRegenerateEvent
import cn.nukkit.network.connection.netty.BedrockPacketWrapper
import cn.nukkit.event.server.DataPacketDecodeEvent
import cn.nukkit.event.server.DataPacketReceiveEvent
import cn.nukkit.event.server.RemoteServerCommandEvent
import cn.nukkit.event.server.ConsoleCommandOutputEvent
import cn.nukkit.event.command.CommandBlockExecuteEvent
import cn.nukkit.event.vehicle.VehicleEvent
import cn.nukkit.event.vehicle.VehicleMoveEvent
import cn.nukkit.event.vehicle.VehicleCreateEvent
import cn.nukkit.entity.item.EntityVehicle
import cn.nukkit.event.vehicle.VehicleDamageEvent
import cn.nukkit.event.vehicle.VehicleUpdateEvent
import cn.nukkit.event.vehicle.VehicleDestroyEvent
import cn.nukkit.event.vehicle.EntityExitVehicleEvent
import cn.nukkit.event.vehicle.EntityEnterVehicleEvent
import cn.nukkit.event.vehicle.VehicleDamageByEntityEvent
import cn.nukkit.event.weather.LightningStrikeEvent
import cn.nukkit.event.redstone.RedstoneUpdateEvent
import cn.nukkit.blockentity.BlockEntityBrewingStand
import cn.nukkit.event.inventory.InventoryEvent
import cn.nukkit.event.inventory.BrewEvent
import cn.nukkit.recipe.Recipe
import cn.nukkit.event.inventory.CraftItemEvent
import cn.nukkit.event.inventory.StartBrewEvent
import cn.nukkit.inventory.GrindstoneInventory
import cn.nukkit.event.inventory.GrindstoneEvent
import cn.nukkit.inventory.AnvilInventory
import cn.nukkit.event.inventory.RepairItemEvent
import cn.nukkit.event.inventory.EnchantItemEvent
import cn.nukkit.blockentity.BlockEntityFurnace
import cn.nukkit.event.inventory.FurnaceBurnEvent
import cn.nukkit.event.inventory.FurnaceSmeltEvent
import cn.nukkit.blockentity.BlockEntityCampfire
import cn.nukkit.event.inventory.CampfireSmeltEvent
import cn.nukkit.event.inventory.InventoryOpenEvent
import cn.nukkit.inventory.SmithingInventory
import cn.nukkit.event.inventory.SmithingTableEvent
import cn.nukkit.event.inventory.InventoryCloseEvent
import cn.nukkit.event.inventory.InventoryMoveItemEvent
import cn.nukkit.event.inventory.InventoryPickupItemEvent
import cn.nukkit.entity.projectile.abstract_arrow.EntityArrow
import cn.nukkit.event.inventory.InventoryPickupArrowEvent
import cn.nukkit.entity.projectile.abstract_arrow.EntityThrownTrident
import cn.nukkit.event.inventory.InventoryPickupTridentEvent
import cn.nukkit.network.protocol.types.itemstack.request.action.ItemStackRequestAction
import cn.nukkit.inventory.request.ItemStackRequestContext
import cn.nukkit.inventory.request.ActionResponse
import cn.nukkit.event.inventory.ItemStackRequestActionEvent
import cn.nukkit.event.inventory.PlayerTypingAnvilInventoryEvent
import cn.nukkit.scoreboard.IScoreboard
import cn.nukkit.event.scoreboard.ScoreboardEvent
import cn.nukkit.scoreboard.IScoreboardLine
import cn.nukkit.event.scoreboard.ScoreboardLineChangeEvent
import cn.nukkit.event.scoreboard.ScoreboardObjectiveChangeEvent
import cn.nukkit.plugin.RegisteredListener
import cn.nukkit.event.EventPriority

