/**
 * 与事件相关的类,事件在指定代码触发.
 *
 *
 * Classes relevant to event,events are emitted in the specified code.
 */
package org.chorus.event

import org.chorus.blockentity.BlockEntity.block
import org.chorus.blockentity.BlockEntityLectern.totalPages
import org.chorus.entity.Entity.getNetworkId
import org.chorus.entity.Entity.getLocator
import org.chorus.entity.Entity.hasEffect
import org.chorus.entity.Entity.getEffect
import org.chorus.entity.effect.Effect.getLevel
import org.chorus.entity.Entity.Companion.getDefaultNBT
import org.chorus.entity.Entity.getViewers
import org.chorus.entity.Entity.kill
import org.chorus.entity.Entity.close
import org.chorus.entity.EntityHuman.getName
import org.chorus.blockentity.BlockEntityBrewingStand.getInventory
import org.chorus.event.HandlerList
import org.chorus.event.item.ItemWearEvent
import org.chorus.block.BlockBell
import org.chorus.event.block.BellRingEvent.RingCause
import org.chorus.event.block.BlockEvent
import org.chorus.event.block.BellRingEvent
import org.chorus.event.block.SignGlowEvent
import org.chorus.event.block.BlockBurnEvent
import org.chorus.event.block.BlockFadeEvent
import org.chorus.event.block.BlockFallEvent
import org.chorus.event.block.BlockGrowEvent
import org.chorus.event.block.BlockFormEvent
import org.chorus.event.block.SignWaxedEvent
import org.chorus.math.BlockFace
import org.chorus.event.block.BlockBreakEvent
import org.chorus.event.block.BlockPlaceEvent
import org.chorus.event.block.BlockUpdateEvent
import org.chorus.event.block.DoorToggleEvent
import org.chorus.block.BlockLiquid
import org.chorus.event.block.LiquidFlowEvent
import org.chorus.event.block.SignChangeEvent
import org.chorus.event.block.WaterFrostEvent
import org.chorus.event.block.BlockFromToEvent
import org.chorus.event.block.BlockIgniteEvent.BlockIgniteCause
import org.chorus.event.block.BlockIgniteEvent
import org.chorus.block.BlockPistonBase
import org.chorus.event.block.BlockPistonEvent
import org.chorus.event.block.BlockSpreadEvent
import org.chorus.event.block.LeavesDecayEvent
import org.chorus.event.block.BlockExplodeEvent
import org.chorus.event.block.BlockHarvestEvent
import org.chorus.blockentity.BlockEntityItemFrame
import org.chorus.event.block.ItemFrameUseEvent
import org.chorus.event.block.BlockRedstoneEvent
import org.chorus.event.block.ComposterFillEvent
import org.chorus.event.block.FarmLandDecayEvent
import org.chorus.event.block.ComposterEmptyEvent
import org.chorus.block.BlockTurtleEgg
import org.chorus.block.BlockAir
import org.chorus.block.property.enums.TurtleEggCount
import org.chorus.event.block.TurtleEggHatchEvent
import org.chorus.event.block.ConduitActivateEvent
import org.chorus.blockentity.BlockEntityLectern
import org.chorus.event.block.LecternDropBookEvent
import org.chorus.utils.BlockColor
import org.chorus.event.block.SignColorChangeEvent
import org.chorus.block.BlockHopper.IHopper
import org.chorus.event.block.HopperSearchItemEvent
import org.chorus.event.block.LecternPlaceBookEvent
import org.chorus.event.block.ConduitDeactivateEvent
import org.chorus.event.block.LecternPageChangeEvent
import org.chorus.event.block.BlockExplosionPrimeEvent
import org.chorus.block.property.enums.BigDripleafTilt
import org.chorus.event.block.BigDripleafTiltChangeEvent
import org.chorus.block.property.enums.CauldronLiquid
import org.chorus.event.block.CauldronFilledByDrippingLiquidEvent
import org.chorus.level.format.IChunk
import org.chorus.event.level.LevelEvent
import org.chorus.event.level.ChunkEvent
import org.chorus.event.level.ChunkLoadEvent
import org.chorus.event.level.LevelInitEvent
import org.chorus.event.level.LevelLoadEvent
import org.chorus.event.level.LevelSaveEvent
import org.chorus.event.level.ChunkUnloadEvent
import org.chorus.event.level.LevelUnloadEvent
import org.chorus.event.level.SpawnChangeEvent
import org.chorus.event.level.StructureGrowEvent
import org.chorus.event.level.WeatherEvent
import org.chorus.event.level.ThunderChangeEvent
import org.chorus.event.level.WeatherChangeEvent
import org.chorus.event.level.VibrationOccurEvent
import org.chorus.level.vibration.VibrationListener
import org.chorus.event.level.VibrationArriveEvent
import org.chorus.entity.item.EntityItem
import org.chorus.event.entity.EntityEvent
import org.chorus.event.entity.ItemSpawnEvent
import org.chorus.event.entity.EntityFallEvent
import org.chorus.entity.EntityLiving
import org.chorus.event.entity.EntityDeathEvent
import org.chorus.entity.EntityCreature
import org.chorus.entity.EntityHuman
import org.chorus.entity.projectile.EntityProjectile
import org.chorus.event.entity.ItemDespawnEvent
import org.chorus.entity.mob.monster.EntityCreeper
import org.chorus.event.entity.CreeperPowerEvent.PowerCause
import org.chorus.entity.weather.EntityLightningStrike
import org.chorus.event.entity.CreeperPowerEvent
import org.chorus.event.entity.EntityDamageEvent.DamageCause
import org.chorus.event.entity.EntityDamageEvent.DamageModifier
import org.chorus.event.entity.EntityDamageEvent
import org.chorus.event.entity.EntityMotionEvent
import org.chorus.event.entity.CreatureSpawnEvent.SpawnReason
import org.chorus.nbt.tag.CompoundTag
import org.chorus.event.entity.CreatureSpawnEvent
import org.chorus.event.entity.EntityCombustEvent
import org.chorus.event.entity.EntityDespawnEvent
import java.util.HashSet
import org.chorus.event.entity.EntityExplodeEvent
import org.chorus.level.MovingObjectPosition
import org.chorus.event.entity.ProjectileHitEvent
import org.chorus.event.entity.EntityInteractEvent
import org.chorus.event.entity.EntityShootBowEvent
import org.chorus.event.player.PlayerTeleportEvent.TeleportCause
import org.chorus.event.entity.EntityTeleportEvent
import org.chorus.event.entity.ExplosionPrimeEvent
import org.chorus.event.entity.ProjectileLaunchEvent
import org.chorus.event.entity.EntityArmorChangeEvent
import org.chorus.event.entity.EntityBlockChangeEvent
import org.chorus.event.entity.EntityLevelChangeEvent
import org.chorus.event.entity.EntityPortalEnterEvent.PortalType
import org.chorus.event.entity.EntityPortalEnterEvent
import org.chorus.event.entity.EntityVehicleExitEvent
import org.chorus.event.entity.EntityEffectRemoveEvent
import org.chorus.event.entity.EntityEffectUpdateEvent
import org.chorus.event.entity.EntityRegainHealthEvent
import org.chorus.event.entity.EntityVehicleEnterEvent
import org.chorus.event.entity.EntityDamageBlockedEvent
import org.chorus.event.entity.EntityShootCrossbowEvent
import org.chorus.event.entity.EntityExplosionPrimeEvent
import org.chorus.event.entity.EntityInventoryChangeEvent
import org.chorus.event.entity.EntityDamageByEntityEvent
import org.chorus.event.player.PlayerMessageEvent
import org.chorus.permission.Permissible
import org.chorus.event.player.PlayerChatEvent
import org.chorus.entity.item.EntityFishingHook
import org.chorus.event.player.PlayerEvent
import org.chorus.event.player.PlayerFishEvent
import org.chorus.lang.TextContainer
import org.chorus.event.player.PlayerJoinEvent
import org.chorus.event.player.PlayerJumpEvent
import org.chorus.event.player.PlayerKickEvent
import org.chorus.event.player.PlayerMoveEvent
import org.chorus.event.player.PlayerQuitEvent
import org.chorus.lang.TranslationContainer
import org.chorus.event.player.PlayerDeathEvent
import org.chorus.event.player.PlayerLoginEvent
import org.chorus.event.player.EntityFreezeEvent
import org.chorus.network.protocol.types.SpawnPointType
import org.chorus.event.player.PlayerRespawnEvent
import org.chorus.event.player.PlayerBedEnterEvent
import org.chorus.event.player.PlayerBedLeaveEvent
import org.chorus.event.player.PlayerCreationEvent
import org.chorus.event.player.PlayerDropItemEvent
import org.chorus.network.protocol.BookEditPacket
import org.chorus.event.player.PlayerEditBookEvent
import org.chorus.math.IVector3
import org.chorus.event.player.PlayerInteractEvent
import org.chorus.event.player.PlayerItemHeldEvent
import org.chorus.event.player.PlayerTeleportEvent
import org.chorus.network.protocol.AnimatePacket
import org.chorus.event.player.PlayerAnimationEvent
import org.chorus.event.player.PlayerBlockPickEvent
import org.chorus.event.player.PlayerBucketEvent
import org.chorus.event.player.PlayerBucketFillEvent
import org.chorus.event.player.PlayerChangeSkinEvent
import org.chorus.event.player.PlayerToggleSwimEvent
import org.chorus.event.player.PlayerBucketEmptyEvent
import org.chorus.event.player.PlayerInvalidMoveEvent
import org.chorus.event.player.PlayerItemConsumeEvent
import org.chorus.event.player.PlayerShowCreditsEvent
import org.chorus.event.player.PlayerToggleGlideEvent
import org.chorus.event.player.PlayerToggleSneakEvent
import org.chorus.event.player.PlayerChunkRequestEvent
import org.chorus.event.player.PlayerHackDetectedEvent.HackType
import org.chorus.event.player.PlayerHackDetectedEvent
import org.chorus.event.player.PlayerToggleFlightEvent
import org.chorus.event.player.PlayerToggleSprintEvent
import org.chorus.event.player.PlayerTransferItemEvent
import org.chorus.event.player.PlayerFormRespondedEvent
import org.chorus.event.player.PlayerIllegalFlightEvent
import org.chorus.AdventureSettings
import org.chorus.event.player.PlayerGameModeChangeEvent
import org.chorus.event.player.PlayerInteractEntityEvent
import org.chorus.event.player.PlayerMapInfoRequestEvent
import org.chorus.dialog.window.FormWindowDialog
import org.chorus.dialog.response.FormResponseDialog
import org.chorus.event.player.PlayerDialogRespondedEvent
import org.chorus.event.player.PlayerFoodLevelChangeEvent
import org.chorus.event.player.PlayerMouseOverEntityEvent
import org.chorus.event.player.PlayerChangeArmorStandEvent
import org.chorus.event.player.PlayerExperienceChangeEvent
import org.chorus.event.player.PlayerToggleSpinAttackEvent
import org.chorus.event.player.PlayerCommandPreprocessEvent
import org.chorus.event.player.PlayerSettingsRespondedEvent
import org.chorus.event.player.PlayerAchievementAwardedEvent
import org.chorus.inventory.EnchantInventory
import org.chorus.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import org.chorus.event.player.PlayerEnchantOptionsRequestEvent
import org.chorus.event.player.PlayerServerSettingsRequestEvent
import org.chorus.event.plugin.PluginEvent
import org.chorus.event.potion.PotionEvent
import org.chorus.event.potion.PotionApplyEvent
import org.chorus.entity.projectile.throwable.EntitySplashPotion
import org.chorus.event.potion.PotionCollideEvent
import org.chorus.event.server.ServerEvent
import org.chorus.event.server.ServerStopEvent
import org.chorus.network.protocol.DataPacket
import org.chorus.event.server.BatchPacketsEvent
import org.chorus.event.server.ServerCommandEvent
import org.chorus.event.server.ServerStartedEvent
import org.chorus.event.server.DataPacketSendEvent
import java.util.HashMap
import org.chorus.network.protocol.ProtocolInfo
import io.netty.buffer.ByteBuf
import io.netty.buffer.ByteBufAllocator
import org.chorus.plugin.PluginDescription
import org.chorus.event.server.QueryRegenerateEvent
import org.chorus.network.connection.netty.BedrockPacketWrapper
import org.chorus.event.server.DataPacketDecodeEvent
import org.chorus.event.server.DataPacketReceiveEvent
import org.chorus.event.server.RemoteServerCommandEvent
import org.chorus.event.server.ConsoleCommandOutputEvent
import org.chorus.event.command.CommandBlockExecuteEvent
import org.chorus.event.vehicle.VehicleEvent
import org.chorus.event.vehicle.VehicleMoveEvent
import org.chorus.event.vehicle.VehicleCreateEvent
import org.chorus.entity.item.EntityVehicle
import org.chorus.event.vehicle.VehicleDamageEvent
import org.chorus.event.vehicle.VehicleUpdateEvent
import org.chorus.event.vehicle.VehicleDestroyEvent
import org.chorus.event.vehicle.EntityExitVehicleEvent
import org.chorus.event.vehicle.EntityEnterVehicleEvent
import org.chorus.event.vehicle.VehicleDamageByEntityEvent
import org.chorus.event.weather.LightningStrikeEvent
import org.chorus.event.redstone.RedstoneUpdateEvent
import org.chorus.blockentity.BlockEntityBrewingStand
import org.chorus.event.inventory.InventoryEvent
import org.chorus.event.inventory.BrewEvent
import org.chorus.recipe.Recipe
import org.chorus.event.inventory.CraftItemEvent
import org.chorus.event.inventory.StartBrewEvent
import org.chorus.inventory.GrindstoneInventory
import org.chorus.event.inventory.GrindstoneEvent
import org.chorus.inventory.AnvilInventory
import org.chorus.event.inventory.RepairItemEvent
import org.chorus.event.inventory.EnchantItemEvent
import org.chorus.blockentity.BlockEntityFurnace
import org.chorus.event.inventory.FurnaceBurnEvent
import org.chorus.event.inventory.FurnaceSmeltEvent
import org.chorus.blockentity.BlockEntityCampfire
import org.chorus.event.inventory.CampfireSmeltEvent
import org.chorus.event.inventory.InventoryOpenEvent
import org.chorus.inventory.SmithingInventory
import org.chorus.event.inventory.SmithingTableEvent
import org.chorus.event.inventory.InventoryCloseEvent
import org.chorus.event.inventory.InventoryMoveItemEvent
import org.chorus.event.inventory.InventoryPickupItemEvent
import org.chorus.entity.projectile.abstract_arrow.EntityArrow
import org.chorus.event.inventory.InventoryPickupArrowEvent
import org.chorus.entity.projectile.abstract_arrow.EntityThrownTrident
import org.chorus.event.inventory.InventoryPickupTridentEvent
import org.chorus.network.protocol.types.itemstack.request.action.ItemStackRequestAction
import org.chorus.inventory.request.ItemStackRequestContext
import org.chorus.inventory.request.ActionResponse
import org.chorus.event.inventory.ItemStackRequestActionEvent
import org.chorus.event.inventory.PlayerTypingAnvilInventoryEvent
import org.chorus.scoreboard.IScoreboard
import org.chorus.event.scoreboard.ScoreboardEvent
import org.chorus.scoreboard.IScoreboardLine
import org.chorus.event.scoreboard.ScoreboardLineChangeEvent
import org.chorus.event.scoreboard.ScoreboardObjectiveChangeEvent
import org.chorus.plugin.RegisteredListener
import org.chorus.event.EventPriority

