package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class Color {
    BLACK,

    BLUE,

    BROWN,

    CYAN,

    GRAY,

    GREEN,

    LIGHT_BLUE,

    LIME,

    MAGENTA,

    ORANGE,

    PINK,

    PURPLE,

    RED,

    SILVER,

    WHITE,

    YELLOW
}
