package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class CrackedState {
    NO_CRACKS,
    CRACKED,
    MAX_CRACKED;

    fun next(): CrackedState {
        return entries[ordinal + 1]
    }
}
