package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class CreakingHeartState(val stateName: String) {
    UPROOTED("uprooted"),
    DORMANT("dormant"),
    AWAKE("awake")
}
