package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class MinecraftCardinalDirection {
    SOUTH,
    WEST,
    NORTH,
    EAST;

    companion object {
        val VALUES: Array<MinecraftCardinalDirection> = entries.toTypedArray()
    }
}
