package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 *
 * Placeholder，use [cn.nukkit.math.BlockFace]
 * @author daoge_cmd
 */
@Deprecated("")
enum class MinecraftBlockFace 
