package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * Placeholder，use [org.chorus.math.BlockFace.Axis]
 * @author daoge_cmd
 */
@Deprecated("")
enum class PillarAxis 
