package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class StoneSlabType2 {
    RED_SANDSTONE,
    PURPUR,
    PRISMARINE_ROUGH,
    PRISMARINE_DARK,
    PRISMARINE_BRICK,
    MOSSY_COBBLESTONE,
    SMOOTH_SANDSTONE,
    RED_NETHER_BRICK
}
