package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class StoneSlabType3 {
    END_STONE_BRICK,
    SMOOTH_RED_SANDSTONE,
    POLISHED_ANDESITE,
    ANDESITE,
    DIORITE,
    POLISHED_DIORITE,
    GRANITE,
    POLISHED_GRANITE
}
