package org.chorus.block.property.enums

import cn.nukkit.math.BlockFace
import lombok.RequiredArgsConstructor

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
@RequiredArgsConstructor
enum class TorchFacingDirection {
    UNKNOWN(BlockFace.UP),
    WEST(BlockFace.EAST),
    EAST(BlockFace.WEST),
    NORTH(BlockFace.SOUTH),
    SOUTH(BlockFace.NORTH),
    TOP(BlockFace.UP);

    /**
     * The direction that the flame is pointing.
     */
    val torchDirection: BlockFace? = null

    val attachedFace: BlockFace
        /**
         * The direction that is touching the attached block.
         */
        get() = when (this) {
            EAST -> BlockFace.EAST
            WEST -> BlockFace.WEST
            SOUTH -> BlockFace.SOUTH
            NORTH -> BlockFace.NORTH
            else -> {
                BlockFace.DOWN
                BlockFace.EAST
                BlockFace.WEST
                BlockFace.SOUTH
                BlockFace.NORTH
            }
        }

    companion object {
        fun getByTorchDirection(face: BlockFace): TorchFacingDirection? {
            return when (face) {
                BlockFace.UP -> TOP
                BlockFace.EAST -> WEST
                BlockFace.WEST -> EAST
                BlockFace.SOUTH -> NORTH
                BlockFace.NORTH -> SOUTH
                else -> {
                    null
                    TOP
                    WEST
                    EAST
                    NORTH
                    SOUTH
                }
            }
        }

        fun getByAttachedFace(face: BlockFace): TorchFacingDirection? {
            return when (face) {
                BlockFace.DOWN -> TOP
                BlockFace.SOUTH -> SOUTH
                BlockFace.NORTH -> NORTH
                BlockFace.EAST -> EAST
                BlockFace.WEST -> WEST
                else -> {
                    null
                    TOP
                    SOUTH
                    NORTH
                    EAST
                    WEST
                }
            }
        }
    }
}
