package org.chorus.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class TurtleEggCount {
    ONE_EGG,
    TWO_EGG,
    THREE_EGG,
    FOUR_EGG;

    fun before(): TurtleEggCount {
        return entries[ordinal - 1]
    }

    fun next(): TurtleEggCount {
        return entries[ordinal + 1]
    }
}
