/**
 * 与[NBT格式](https://minecraft.wiki/w/NBT_format)相关的类.
 *
 *
 * Classes relevant to [NBT format](https://minecraft.wiki/w/NBT_format).
 */
package org.chorus.nbt

import cn.nukkit.item.Item.getCount
import cn.nukkit.item.Item.damage
import cn.nukkit.item.Item.id
import cn.nukkit.item.Item.hasCompoundTag
import cn.nukkit.item.Item.namedTag
import cn.nukkit.item.Item.isBlock
import cn.nukkit.item.Item.blockId
import cn.nukkit.item.Item.blockUnsafe
import cn.nukkit.level.updater.item.ItemUpdaters.updateItem
import cn.nukkit.item.Item.Companion.get
import cn.nukkit.item.Item.isNull
import cn.nukkit.item.Item.setNamedTag
import cn.nukkit.level.updater.block.BlockStateUpdaters.updateBlockState
import cn.nukkit.item.Item.setCount
import cn.nukkit.item.Item.orCreateNamedTag
import cn.nukkit.nbt.tag.ByteTag
import cn.nukkit.nbt.tag.ShortTag
import cn.nukkit.nbt.tag.IntTag
import cn.nukkit.nbt.tag.LongTag
import cn.nukkit.nbt.tag.FloatTag
import cn.nukkit.nbt.tag.DoubleTag
import cn.nukkit.nbt.tag.ByteArrayTag
import cn.nukkit.nbt.tag.IntArrayTag
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.nbt.tag.NumberTag
import java.util.HashMap
import cn.nukkit.nbt.tag.LinkedCompoundTag
import java.util.TreeMap
import cn.nukkit.nbt.tag.TreeMapCompoundTag
import cn.nukkit.nbt.snbt.SNBTLexer
import java.util.concurrent.ConcurrentHashMap
import cn.nukkit.nbt.snbt.SNBTConstants
import java.util.NoSuchElementException
import cn.nukkit.nbt.snbt.ast.WHITESPACE
import cn.nukkit.nbt.snbt.InvalidToken
import cn.nukkit.nbt.snbt.SNBTConstants.LexicalState
import java.util.EnumSet
import cn.nukkit.nbt.snbt.SNBTNfaData.NfaFunction
import cn.nukkit.nbt.snbt.SNBTNfaData
import java.io.IOException
import java.nio.charset.CharacterCodingException
import java.nio.charset.Charset
import java.nio.charset.CharsetDecoder
import java.nio.charset.CoderResult
import cn.nukkit.nbt.snbt.SNBTNfaData.SNBT
import cn.nukkit.nbt.snbt.SNBTParserImplement.NonTerminalCall
import cn.nukkit.nbt.snbt.SNBTParserImplement
import java.io.PrintStream
import java.util.LinkedList
import java.util.concurrent.CancellationException
import cn.nukkit.nbt.snbt.ast.ByteArrayNBT
import cn.nukkit.nbt.snbt.ast.IntArrayNBT
import cn.nukkit.nbt.snbt.ast.ListNBT
import cn.nukkit.nbt.snbt.ast.CompoundNBT
import cn.nukkit.nbt.snbt.SNBTParserImplement.NodeScope
import cn.nukkit.nbt.stream.PGZIPOutputStream
import cn.nukkit.nbt.stream.PGZIPState
import cn.nukkit.nbt.stream.PGZIPBlock
import cn.nukkit.nbt.stream.PGZIPThreadLocal
import java.nio.ByteOrder
import java.io.DataInput
import java.io.DataInputStream
import java.util.concurrent.atomic.AtomicBoolean
import cn.nukkit.utils.VarInt
import java.io.DataOutput
import java.util.concurrent.ExecutorService
import java.io.FilterOutputStream
import java.util.concurrent.BlockingQueue
import java.util.concurrent.ArrayBlockingQueue
import java.io.InterruptedIOException
import java.util.concurrent.Executors
import java.util.concurrent.ThreadFactory
import java.io.RandomAccessFile
import cn.nukkit.nbt.stream.BufferedRandomAccessFile
import cn.nukkit.utils.LittleEndianByteBufInputStream
import cn.nukkit.network.protocol.ProtocolInfo
import cn.nukkit.block.BlockID
import cn.nukkit.level.updater.item.ItemUpdaters
import cn.nukkit.level.updater.block.BlockStateUpdaters
import cn.nukkit.nbt.NBTIO
import cn.nukkit.item.UnknownItem
import cn.nukkit.block.BlockUnknown
import java.io.FileInputStream
import java.io.ByteArrayInputStream
import cn.nukkit.nbt.stream.NBTInputStream
import java.io.BufferedInputStream
import cn.nukkit.utils.ThreadCache
import cn.nukkit.nbt.stream.NBTOutputStream
import java.io.FileOutputStream
import cn.nukkit.nbt.SNBTParser

