/**
 * 与[NBT格式](https://minecraft.wiki/w/NBT_format)相关的类.
 *
 *
 * Classes relevant to [NBT format](https://minecraft.wiki/w/NBT_format).
 */
package org.chorus.nbt

import org.chorus.item.Item.getCount
import org.chorus.item.Item.damage
import org.chorus.item.Item.id
import org.chorus.item.Item.hasCompoundTag
import org.chorus.item.Item.namedTag
import org.chorus.item.Item.isBlock
import org.chorus.item.Item.blockId
import org.chorus.item.Item.blockUnsafe
import org.chorus.level.updater.item.ItemUpdaters.updateItem
import org.chorus.item.Item.Companion.get
import org.chorus.item.Item.isNull
import org.chorus.item.Item.setNamedTag
import org.chorus.level.updater.block.BlockStateUpdaters.updateBlockState
import org.chorus.item.Item.setCount
import org.chorus.item.Item.orCreateNamedTag
import org.chorus.nbt.tag.ByteTag
import org.chorus.nbt.tag.ShortTag
import org.chorus.nbt.tag.IntTag
import org.chorus.nbt.tag.LongTag
import org.chorus.nbt.tag.FloatTag
import org.chorus.nbt.tag.DoubleTag
import org.chorus.nbt.tag.ByteArrayTag
import org.chorus.nbt.tag.IntArrayTag
import org.chorus.nbt.tag.StringTag
import org.chorus.nbt.tag.ListTag
import org.chorus.nbt.tag.CompoundTag
import org.chorus.nbt.tag.NumberTag
import java.util.HashMap
import org.chorus.nbt.tag.LinkedCompoundTag
import java.util.TreeMap
import org.chorus.nbt.tag.TreeMapCompoundTag
import org.chorus.nbt.snbt.SNBTLexer
import java.util.concurrent.ConcurrentHashMap
import org.chorus.nbt.snbt.SNBTConstants
import java.util.NoSuchElementException
import org.chorus.nbt.snbt.ast.WHITESPACE
import org.chorus.nbt.snbt.InvalidToken
import org.chorus.nbt.snbt.SNBTConstants.LexicalState
import java.util.EnumSet
import org.chorus.nbt.snbt.SNBTNfaData.NfaFunction
import org.chorus.nbt.snbt.SNBTNfaData
import java.io.IOException
import java.nio.charset.CharacterCodingException
import java.nio.charset.Charset
import java.nio.charset.CharsetDecoder
import java.nio.charset.CoderResult
import org.chorus.nbt.snbt.SNBTNfaData.SNBT
import org.chorus.nbt.snbt.SNBTParserImplement.NonTerminalCall
import org.chorus.nbt.snbt.SNBTParserImplement
import java.io.PrintStream
import java.util.LinkedList
import java.util.concurrent.CancellationException
import org.chorus.nbt.snbt.ast.ByteArrayNBT
import org.chorus.nbt.snbt.ast.IntArrayNBT
import org.chorus.nbt.snbt.ast.ListNBT
import org.chorus.nbt.snbt.ast.CompoundNBT
import org.chorus.nbt.snbt.SNBTParserImplement.NodeScope
import org.chorus.nbt.stream.PGZIPOutputStream
import org.chorus.nbt.stream.PGZIPState
import org.chorus.nbt.stream.PGZIPBlock
import org.chorus.nbt.stream.PGZIPThreadLocal
import java.nio.ByteOrder
import java.io.DataInput
import java.io.DataInputStream
import java.util.concurrent.atomic.AtomicBoolean
import org.chorus.utils.VarInt
import java.io.DataOutput
import java.util.concurrent.ExecutorService
import java.io.FilterOutputStream
import java.util.concurrent.BlockingQueue
import java.util.concurrent.ArrayBlockingQueue
import java.io.InterruptedIOException
import java.util.concurrent.Executors
import java.util.concurrent.ThreadFactory
import java.io.RandomAccessFile
import org.chorus.nbt.stream.BufferedRandomAccessFile
import org.chorus.utils.LittleEndianByteBufInputStream
import org.chorus.network.protocol.ProtocolInfo
import org.chorus.block.BlockID
import org.chorus.level.updater.item.ItemUpdaters
import org.chorus.level.updater.block.BlockStateUpdaters
import org.chorus.nbt.NBTIO
import org.chorus.item.UnknownItem
import org.chorus.block.BlockUnknown
import java.io.FileInputStream
import java.io.ByteArrayInputStream
import org.chorus.nbt.stream.NBTInputStream
import java.io.BufferedInputStream
import org.chorus.utils.ThreadCache
import org.chorus.nbt.stream.NBTOutputStream
import java.io.FileOutputStream
import org.chorus.nbt.SNBTParser

