/**
 * 与世界相关的类.
 *
 *
 * Classes related to world.
 */
package org.chorus.level

import org.chorus.blockentity.BlockEntitySpawnable.spawnCompound
import org.chorus.blockentity.BlockEntitySpawnable.spawnPacket
import org.chorus.blockentity.BlockEntity.saveNBT
import org.chorus.entity.Entity.canBeSavedWithChunk
import org.chorus.entity.Entity.saveNBT
import org.chorus.entity.Entity.getId
import org.chorus.blockentity.BlockEntity.close
import org.chorus.entity.Entity.close
import org.chorus.entity.Entity.Companion.createEntity
import org.chorus.blockentity.BlockEntity.Companion.createBlockEntity
import org.chorus.item.Item.runtimeId
import org.chorus.item.Item.damage
import org.chorus.entity.data.Skin.setSkinData
import org.chorus.entity.data.Skin.generateSkinId
import org.chorus.entity.data.EntityDataMap.setFlag
import org.chorus.entity.data.EntityDataMap.put
import org.chorus.entity.data.EntityDataMap.get
import org.chorus.item.Item.Companion.get
import org.chorus.item.enchantment.Enchantment.Companion.getEnchantment
import org.chorus.item.enchantment.Enchantment.Companion.registeredEnchantments
import org.chorus.entity.Entity.getX
import org.chorus.entity.Entity.getY
import org.chorus.entity.Entity.getZ
import org.chorus.item.enchantment.Enchantment.setLevel
import org.chorus.item.Item.addEnchantment
import org.chorus.item.Item.enchantments
import org.chorus.item.enchantment.Enchantment.level
import org.chorus.item.Item.getCount
import org.chorus.item.Item.setCount
import org.chorus.item.Item.clone
import org.chorus.item.Item.maxDurability
import org.chorus.item.enchantment.Enchantment.canEnchant
import org.chorus.item.enchantment.Enchantment.isCompatibleWith
import org.chorus.item.enchantment.Enchantment.maxLevel
import org.chorus.event.Event.isCancelled
import org.chorus.lang.BaseLang.tr
import org.chorus.event.Event.setCancelled
import org.chorus.entity.Entity.teleport
import org.chorus.entity.Entity.isInitialized
import org.chorus.entity.EntityAsyncPrepare.asyncPrepare
import org.chorus.entity.mob.EntityMob.getBehaviorGroup
import org.chorus.entity.Entity.onUpdate
import org.chorus.blockentity.BlockEntity.onUpdate
import org.chorus.entity.weather.EntityLightningBolt.spawnToAll
import org.chorus.entity.weather.EntityLightningBolt.setEffect
import org.chorus.entity.Entity.isAlive
import org.chorus.entity.Entity.getLocator
import org.chorus.entity.Entity.scheduleUpdate
import org.chorus.entity.Entity.canPassThrough
import org.chorus.event.block.BlockEvent.getBlock
import org.chorus.item.Item.isNull
import org.chorus.entity.Entity.Companion.getDefaultNBT
import org.chorus.entity.Entity.spawnToAll
import org.chorus.item.Item.getEnchantment
import org.chorus.item.Item.applyEnchantments
import org.chorus.event.block.BlockBreakEvent.isFastBreak
import org.chorus.event.block.BlockBreakEvent.drops
import org.chorus.event.block.BlockBreakEvent.dropExp
import org.chorus.blockentity.BlockEntity.onBreak
import org.chorus.item.Item.useOn
import org.chorus.item.Item.isTool
import org.chorus.entity.item.EntityXpOrb.Companion.splitIntoOrbSizes
import org.chorus.item.Item.getBlock
import org.chorus.item.Item.canBeActivated
import org.chorus.item.Item.onActivate
import org.chorus.item.ItemBucket.isWater
import org.chorus.item.Item.canBePlaced
import org.chorus.entity.Entity.getBoundingBox
import org.chorus.item.Item.getNamedTagEntry
import org.chorus.entity.Entity.canCollide
import org.chorus.entity.Entity.canCollideWith
import org.chorus.entity.EntityHuman.getName
import org.chorus.event.entity.EntityExplodeEvent.blockList
import org.chorus.event.block.BlockExplodeEvent.affectedBlocks
import org.chorus.entity.Entity.attack
import org.chorus.entity.Entity.despawnFrom
import org.chorus.entity.Entity.getServer
import org.chorus.level.util.BlockIndex
import org.chorus.utils.collection.FreezableArrayManager
import org.chorus.level.util.NibbleArray
import org.chorus.math.MathHelper
import org.chorus.level.DimensionData
import org.chorus.level.DimensionEnum
import org.chorus.level.util.LevelDBKeyUtil
import java.nio.ByteOrder
import org.chorus.level.util.TickCachedBlockStore.CachedBlockComputer
import org.chorus.level.util.TickCachedBlockStore
import java.util.concurrent.ConcurrentHashMap
import org.chorus.network.protocol.types.GameType
import org.chorus.math.BlockVector3
import org.chorus.utils.SemVersion
import org.chorus.network.protocol.ProtocolInfo
import org.chorus.level.format.leveldb.LevelDat.Abilities

import org.chorus.level.GameRules
import org.chorus.level.format.leveldb.LevelDat.Experiments
import org.chorus.level.format.leveldb.LevelDat.WorldPolicies
import org.iq80.leveldb.DB
import org.iq80.leveldb.impl.Iq80DBFactory
import java.io.IOException
import org.chorus.level.format.LevelProvider
import org.chorus.level.format.IChunk
import org.chorus.level.format.leveldb.LevelDBChunkSerializer
import org.iq80.leveldb.WriteOptions
import org.chorus.level.format.leveldb.LevelDBProvider
import org.chorus.utils.collection.nb.Long2ObjectNonBlockingMap
import org.chorus.level.format.leveldb.LevelDat
import org.chorus.level.format.leveldb.LevelDBStorage
import org.chorus.utils.ChunkException
import java.util.concurrent.atomic.AtomicReference
import org.chorus.level.format.UnsafeChunk
import io.netty.buffer.ByteBuf
import io.netty.buffer.ByteBufAllocator
import org.chorus.level.format.ChunkSection
import org.chorus.level.format.palette.RuntimeDataSerializer
import org.chorus.nbt.tag.CompoundTag
import org.chorus.blockentity.BlockEntitySpawnable
import io.netty.buffer.ByteBufOutputStream
import org.chorus.nbt.NBTIO
import java.io.FileInputStream
import java.io.BufferedInputStream
import java.io.ByteArrayInputStream
import org.chorus.level.GameRule
import org.chorus.nbt.tag.IntTag
import java.io.FileNotFoundException
import java.util.HashMap
import org.chorus.api.UsedByReflection
import org.chorus.level.format.LevelConfig.GeneratorConfig
import java.io.FileOutputStream
import org.chorus.nbt.tag.LinkedCompoundTag
import org.chorus.nbt.tag.ListTag
import org.chorus.nbt.tag.DoubleTag
import org.chorus.nbt.tag.FloatTag
import org.iq80.leveldb.WriteBatch
import io.netty.buffer.Unpooled
import org.chorus.level.format.IChunkBuilder
import org.chorus.level.format.palette.PersistentDataSerializer
import org.chorus.level.format.palette.BlockPalette
import org.chorus.block.BlockAir
import org.chorus.level.format.palette.RuntimeDataDeserializer
import org.chorus.block.BlockUnknown
import org.chorus.level.format.leveldb.BDSEntityTranslator
import org.chorus.utils.ByteBufVarInt
import org.chorus.block.BlockID
import io.netty.buffer.ByteBufInputStream
import org.chorus.nbt.stream.NBTInputStream
import org.chorus.level.format.palette.PaletteUtils
import org.chorus.level.updater.util.tagupdater.CompoundTagUpdaterContext
import org.chorus.level.updater.block.BlockStateUpdaters
import org.chorus.nbt.tag.TreeMapCompoundTag
import java.util.concurrent.atomic.AtomicLong
import org.chorus.level.AntiXraySystem
import org.chorus.utils.random.NukkitRandom
import org.chorus.math.NukkitMath
import org.chorus.level.format.bitarray.SingletonBitArray
import java.util.concurrent.locks.StampedLock
import org.chorus.level.biome.BiomeID
import org.chorus.nbt.tag.NumberTag
import java.util.function.BiPredicate



import org.chorus.level.format.LevelConfig.AntiXrayMode
import org.chorus.level.format.LevelProviderManager

import org.chorus.level.updater.item.ItemUpdater_1_20_60
import org.chorus.level.updater.item.ItemUpdater_1_20_70
import org.chorus.level.updater.item.ItemUpdater_1_20_80
import org.chorus.level.updater.item.ItemUpdater_1_21_0
import org.chorus.level.updater.item.ItemUpdater_1_21_20
import org.chorus.level.updater.item.ItemUpdater_1_21_30
import org.chorus.level.updater.item.ItemUpdater_1_21_40
import org.chorus.level.updater.item.ItemUpdaters
import org.chorus.level.updater.util.tagupdater.CompoundTagEditHelper
import org.chorus.level.updater.util.tagupdater.CompoundTagUpdater
import org.chorus.level.updater.util.tagupdater.CompoundTagUpdater.TryAddPredicate
import org.chorus.level.updater.util.tagupdater.CompoundTagUpdater.TagNamePredicate
import java.util.Deque
import org.chorus.level.updater.util.TagUtils
import org.chorus.nbt.tag.ByteTag
import org.chorus.nbt.tag.ShortTag
import org.chorus.nbt.tag.LongTag
import org.chorus.nbt.tag.StringTag
import org.chorus.nbt.tag.ByteArrayTag
import org.chorus.nbt.tag.IntArrayTag
import org.chorus.level.updater.util.OrderedUpdater
import org.chorus.level.updater.block.BlockStateUpdaterBase
import org.chorus.level.updater.block.BlockStateUpdater_1_10_0
import org.chorus.level.updater.block.BlockStateUpdater_1_12_0
import org.chorus.level.updater.block.BlockStateUpdater_1_13_0
import org.chorus.level.updater.block.BlockStateUpdater_1_14_0
import org.chorus.level.updater.block.BlockStateUpdater_1_15_0
import org.chorus.level.updater.block.BlockStateUpdater_1_16_0
import org.chorus.level.updater.block.BlockStateUpdater_1_16_210
import org.chorus.level.updater.block.BlockStateUpdater_1_17_30
import org.chorus.level.updater.block.BlockStateUpdater_1_17_40
import org.chorus.level.updater.block.BlockStateUpdater_1_18_10
import org.chorus.level.updater.block.BlockStateUpdater_1_18_30
import org.chorus.level.updater.block.BlockStateUpdater_1_19_0
import org.chorus.level.updater.block.BlockStateUpdater_1_19_20
import org.chorus.level.updater.block.BlockStateUpdater_1_19_70
import org.chorus.level.updater.block.BlockStateUpdater_1_19_80
import org.chorus.level.updater.block.BlockStateUpdater_1_20_0
import org.chorus.level.updater.block.BlockStateUpdater_1_20_10
import org.chorus.level.updater.block.BlockStateUpdater_1_20_30
import org.chorus.level.updater.block.BlockStateUpdater_1_20_40
import org.chorus.level.updater.block.BlockStateUpdater_1_20_50
import org.chorus.level.updater.block.BlockStateUpdater_1_20_60
import org.chorus.level.updater.block.BlockStateUpdater_1_20_70
import org.chorus.level.updater.block.BlockStateUpdater_1_20_80
import org.chorus.level.updater.block.BlockStateUpdater_1_21_0
import org.chorus.level.updater.block.BlockStateUpdater_1_21_10
import org.chorus.level.updater.block.BlockStateUpdater_1_21_20
import org.chorus.level.updater.block.BlockStateUpdater_1_21_30
import org.chorus.level.updater.block.BlockStateUpdater_1_21_40
import org.chorus.level.updater.block.BlockStateUpdater_1_21_60
import org.chorus.utils.JSONUtils

import org.chorus.network.protocol.DataPacket
import java.util.Locale
import org.chorus.level.particle.GenericParticle
import org.chorus.utils.BlockColor
import org.chorus.network.protocol.LevelEventPacket
import org.chorus.entity.data.EntityDataMap
import org.chorus.entity.data.EntityFlag
import org.chorus.entity.data.EntityDataTypes
import org.chorus.network.protocol.SetEntityDataPacket
import org.chorus.network.protocol.RemoveEntityPacket
import org.chorus.network.protocol.PlayerListPacket
import org.chorus.level.particle.FloatingTextParticle
import org.chorus.network.protocol.AddPlayerPacket
import org.chorus.utils.SerializedImage
import org.chorus.level.particle.SpellParticle
import com.dfsek.terra.api.handle.ItemHandle
import org.chorus.level.generator.terra.PNXAdapter
import org.chorus.level.generator.terra.delegate.PNXEnchantmentDelegate
import com.dfsek.terra.api.handle.WorldHandle
import org.chorus.level.generator.terra.mappings.JeBlockState
import org.chorus.level.generator.terra.mappings.MappingRegistries
import org.chorus.level.generator.terra.handles.PNXWorldHandle
import org.chorus.level.generator.terra.delegate.PNXEntityType
import org.chorus.level.generator.terra.delegate.PNXBlockStateDelegate
import com.dfsek.terra.api.world.ServerWorld
import org.chorus.level.generator.terra.delegate.PNXServerWorld
import com.dfsek.terra.api.inventory.item.ItemMeta
import org.chorus.block.BlockFlowingWater
import com.dfsek.terra.api.inventory.ItemStack
import com.dfsek.terra.api.inventory.item.Damageable
import org.chorus.level.generator.terra.delegate.PNXItemDelegate
import org.chorus.level.generator.terra.delegate.PNXItemMeta
import com.dfsek.terra.api.world.chunk.generation.ProtoChunk
import org.chorus.level.generator.terra.delegate.PNXProtoChunk
import com.dfsek.terra.api.world.chunk.generation.ProtoWorld
import org.chorus.level.generator.terra.delegate.PNXEntity
import com.dfsek.terra.api.world.chunk.generation.ChunkGenerator
import com.dfsek.terra.api.world.biome.generation.BiomeProvider
import com.dfsek.terra.api.config.ConfigPack
import org.chorus.level.generator.terra.TerraGenerator
import org.chorus.level.generator.terra.delegate.PNXChunkDelegate
import org.chorus.level.generator.terra.delegate.PNXItemStack
import com.dfsek.terra.api.world.biome.PlatformBiome
import org.chorus.level.generator.terra.delegate.PNXBlockType
import org.chorus.level.generator.terra.mappings.RegistryLoader
import org.chorus.level.generator.terra.mappings.loader.BiomeRegistryLoader
import org.chorus.level.generator.terra.mappings.populator.BlockRegistryPopulator
import org.chorus.level.generator.terra.mappings.BlockMappings
import org.chorus.block.BlockFlowingLava
import org.chorus.block.property.CommonBlockProperties
import org.chorus.level.generator.terra.mappings.SimpleRegistry
import org.chorus.level.generator.terra.mappings.SimpleMappingRegistry
import org.chorus.level.generator.terra.mappings.MappingRegistry
import org.chorus.level.generator.terra.mappings.ArrayMappingRegistry
import org.chorus.level.generator.terra.mappings.MappedRegistry
import org.chorus.level.generator.terra.mappings.SimpleMappedRegistry
import org.chorus.level.generator.terra.mappings.AbstractMappedRegistry
import org.chorus.level.generator.terra.mappings.MappedMappingRegistry
import org.chorus.level.generator.terra.mappings.BiMappedRegistry
import org.chorus.level.generator.terra.mappings.SimpleBiMappedRegistry
import org.chorus.level.generator.terra.mappings.DoubleKeyMappedRegistry.MapPair
import org.chorus.level.generator.terra.mappings.VersionedMappingRegistry
import org.chorus.level.generator.terra.mappings.DoubleKeyMappedRegistry
import org.chorus.level.generator.terra.delegate.PNXBiomeDelegate
import com.dfsek.terra.AbstractPlatform
import org.chorus.plugin.InternalPlugin
import org.chorus.level.generator.terra.PNXPlatform
import com.dfsek.tectonic.api.loader.type.TypeLoader
import com.dfsek.tectonic.api.loader.ConfigLoader
import com.dfsek.tectonic.api.depth.DepthTracker
import org.chorus.level.generator.terra.handles.PNXItemHandle
import org.chorus.registry.RegisterException
import com.dfsek.terra.api.event.events.platform.PlatformInitializationEvent
import com.dfsek.terra.api.world.chunk.generation.util.GeneratorWrapper
import com.dfsek.terra.api.world.info.WorldProperties
import org.chorus.level.generator.terra.TerraGenerator.TerraStage
import org.chorus.level.generator.GenerateStage
import org.chorus.level.generator.ChunkGenerateContext
import org.chorus.level.generator.terra.delegate.PNXProtoWorld
import com.dfsek.terra.api.world.chunk.generation.stage.GenerationStage
import org.chorus.level.generator.``object`

