/**
 * 与世界相关的类.
 *
 *
 * Classes related to world.
 */
package org.chorus.level

import cn.nukkit.blockentity.BlockEntitySpawnable.spawnCompound
import cn.nukkit.blockentity.BlockEntitySpawnable.spawnPacket
import cn.nukkit.blockentity.BlockEntity.saveNBT
import cn.nukkit.entity.Entity.canBeSavedWithChunk
import cn.nukkit.entity.Entity.saveNBT
import cn.nukkit.entity.Entity.getId
import cn.nukkit.blockentity.BlockEntity.close
import cn.nukkit.entity.Entity.close
import cn.nukkit.entity.Entity.Companion.createEntity
import cn.nukkit.blockentity.BlockEntity.Companion.createBlockEntity
import cn.nukkit.item.Item.runtimeId
import cn.nukkit.item.Item.damage
import cn.nukkit.entity.data.Skin.setSkinData
import cn.nukkit.entity.data.Skin.generateSkinId
import cn.nukkit.entity.data.EntityDataMap.setFlag
import cn.nukkit.entity.data.EntityDataMap.put
import cn.nukkit.entity.data.EntityDataMap.get
import cn.nukkit.item.Item.Companion.get
import cn.nukkit.item.enchantment.Enchantment.Companion.getEnchantment
import cn.nukkit.item.enchantment.Enchantment.Companion.registeredEnchantments
import cn.nukkit.entity.Entity.getX
import cn.nukkit.entity.Entity.getY
import cn.nukkit.entity.Entity.getZ
import cn.nukkit.item.enchantment.Enchantment.setLevel
import cn.nukkit.item.Item.addEnchantment
import cn.nukkit.item.Item.enchantments
import cn.nukkit.item.enchantment.Enchantment.level
import cn.nukkit.item.Item.getCount
import cn.nukkit.item.Item.setCount
import cn.nukkit.item.Item.clone
import cn.nukkit.item.Item.maxDurability
import cn.nukkit.item.enchantment.Enchantment.canEnchant
import cn.nukkit.item.enchantment.Enchantment.isCompatibleWith
import cn.nukkit.item.enchantment.Enchantment.maxLevel
import cn.nukkit.event.Event.isCancelled
import cn.nukkit.lang.BaseLang.tr
import cn.nukkit.event.Event.setCancelled
import cn.nukkit.entity.Entity.teleport
import cn.nukkit.entity.Entity.isInitialized
import cn.nukkit.entity.EntityAsyncPrepare.asyncPrepare
import cn.nukkit.entity.mob.EntityMob.getBehaviorGroup
import cn.nukkit.entity.Entity.onUpdate
import cn.nukkit.blockentity.BlockEntity.onUpdate
import cn.nukkit.entity.weather.EntityLightningBolt.spawnToAll
import cn.nukkit.entity.weather.EntityLightningBolt.setEffect
import cn.nukkit.entity.Entity.isAlive
import cn.nukkit.entity.Entity.getLocator
import cn.nukkit.entity.Entity.scheduleUpdate
import cn.nukkit.entity.Entity.canPassThrough
import cn.nukkit.event.block.BlockEvent.getBlock
import cn.nukkit.item.Item.isNull
import cn.nukkit.entity.Entity.Companion.getDefaultNBT
import cn.nukkit.entity.Entity.spawnToAll
import cn.nukkit.item.Item.getEnchantment
import cn.nukkit.item.Item.applyEnchantments
import cn.nukkit.event.block.BlockBreakEvent.isFastBreak
import cn.nukkit.event.block.BlockBreakEvent.drops
import cn.nukkit.event.block.BlockBreakEvent.dropExp
import cn.nukkit.blockentity.BlockEntity.onBreak
import cn.nukkit.item.Item.useOn
import cn.nukkit.item.Item.isTool
import cn.nukkit.entity.item.EntityXpOrb.Companion.splitIntoOrbSizes
import cn.nukkit.item.Item.getBlock
import cn.nukkit.item.Item.canBeActivated
import cn.nukkit.item.Item.onActivate
import cn.nukkit.item.ItemBucket.isWater
import cn.nukkit.item.Item.canBePlaced
import cn.nukkit.entity.Entity.getBoundingBox
import cn.nukkit.item.Item.getNamedTagEntry
import cn.nukkit.entity.Entity.canCollide
import cn.nukkit.entity.Entity.canCollideWith
import cn.nukkit.entity.EntityHuman.getName
import cn.nukkit.event.entity.EntityExplodeEvent.blockList
import cn.nukkit.event.block.BlockExplodeEvent.affectedBlocks
import cn.nukkit.entity.Entity.attack
import cn.nukkit.entity.Entity.despawnFrom
import cn.nukkit.entity.Entity.getServer
import cn.nukkit.level.util.BlockIndex
import cn.nukkit.utils.collection.FreezableArrayManager
import cn.nukkit.level.util.NibbleArray
import cn.nukkit.math.MathHelper
import cn.nukkit.level.DimensionData
import cn.nukkit.level.DimensionEnum
import cn.nukkit.level.util.LevelDBKeyUtil
import java.nio.ByteOrder
import cn.nukkit.level.util.TickCachedBlockStore.CachedBlockComputer
import cn.nukkit.level.util.TickCachedBlockStore
import java.util.concurrent.ConcurrentHashMap
import cn.nukkit.network.protocol.types.GameType
import cn.nukkit.math.BlockVector3
import cn.nukkit.utils.SemVersion
import cn.nukkit.network.protocol.ProtocolInfo
import cn.nukkit.level.format.leveldb.LevelDat.Abilities
import lombok.AccessLevel
import cn.nukkit.level.GameRules
import cn.nukkit.level.format.leveldb.LevelDat.Experiments
import cn.nukkit.level.format.leveldb.LevelDat.WorldPolicies
import org.iq80.leveldb.DB
import org.iq80.leveldb.impl.Iq80DBFactory
import java.io.IOException
import cn.nukkit.level.format.LevelProvider
import cn.nukkit.level.format.IChunk
import cn.nukkit.level.format.leveldb.LevelDBChunkSerializer
import org.iq80.leveldb.WriteOptions
import cn.nukkit.level.format.leveldb.LevelDBProvider
import cn.nukkit.utils.collection.nb.Long2ObjectNonBlockingMap
import cn.nukkit.level.format.leveldb.LevelDat
import cn.nukkit.level.format.leveldb.LevelDBStorage
import cn.nukkit.utils.ChunkException
import java.util.concurrent.atomic.AtomicReference
import cn.nukkit.level.format.UnsafeChunk
import io.netty.buffer.ByteBuf
import io.netty.buffer.ByteBufAllocator
import cn.nukkit.level.format.ChunkSection
import cn.nukkit.level.format.palette.RuntimeDataSerializer
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.blockentity.BlockEntitySpawnable
import io.netty.buffer.ByteBufOutputStream
import cn.nukkit.nbt.NBTIO
import java.io.FileInputStream
import java.io.BufferedInputStream
import java.io.ByteArrayInputStream
import cn.nukkit.level.GameRule
import cn.nukkit.nbt.tag.IntTag
import java.io.FileNotFoundException
import java.util.HashMap
import cn.nukkit.api.UsedByReflection
import cn.nukkit.level.format.LevelConfig.GeneratorConfig
import java.io.FileOutputStream
import cn.nukkit.nbt.tag.LinkedCompoundTag
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.nbt.tag.DoubleTag
import cn.nukkit.nbt.tag.FloatTag
import org.iq80.leveldb.WriteBatch
import io.netty.buffer.Unpooled
import cn.nukkit.level.format.IChunkBuilder
import cn.nukkit.level.format.palette.PersistentDataSerializer
import cn.nukkit.level.format.palette.BlockPalette
import cn.nukkit.block.BlockAir
import cn.nukkit.level.format.palette.RuntimeDataDeserializer
import cn.nukkit.block.BlockUnknown
import cn.nukkit.level.format.leveldb.BDSEntityTranslator
import cn.nukkit.utils.ByteBufVarInt
import cn.nukkit.block.BlockID
import io.netty.buffer.ByteBufInputStream
import cn.nukkit.nbt.stream.NBTInputStream
import cn.nukkit.level.format.palette.PaletteUtils
import cn.nukkit.level.updater.util.tagupdater.CompoundTagUpdaterContext
import cn.nukkit.level.updater.block.BlockStateUpdaters
import cn.nukkit.nbt.tag.TreeMapCompoundTag
import java.util.concurrent.atomic.AtomicLong
import cn.nukkit.level.AntiXraySystem
import cn.nukkit.utils.random.NukkitRandom
import cn.nukkit.math.NukkitMath
import cn.nukkit.level.format.bitarray.SingletonBitArray
import java.util.concurrent.locks.StampedLock
import cn.nukkit.level.biome.BiomeID
import cn.nukkit.nbt.tag.NumberTag
import java.util.function.BiPredicate
import lombok.AllArgsConstructor
import lombok.NoArgsConstructor
import lombok.experimental.Accessors
import cn.nukkit.level.format.LevelConfig.AntiXrayMode
import cn.nukkit.level.format.LevelProviderManager
import lombok.experimental.UtilityClass
import cn.nukkit.level.updater.item.ItemUpdater_1_20_60
import cn.nukkit.level.updater.item.ItemUpdater_1_20_70
import cn.nukkit.level.updater.item.ItemUpdater_1_20_80
import cn.nukkit.level.updater.item.ItemUpdater_1_21_0
import cn.nukkit.level.updater.item.ItemUpdater_1_21_20
import cn.nukkit.level.updater.item.ItemUpdater_1_21_30
import cn.nukkit.level.updater.item.ItemUpdater_1_21_40
import cn.nukkit.level.updater.item.ItemUpdaters
import cn.nukkit.level.updater.util.tagupdater.CompoundTagEditHelper
import cn.nukkit.level.updater.util.tagupdater.CompoundTagUpdater
import cn.nukkit.level.updater.util.tagupdater.CompoundTagUpdater.TryAddPredicate
import cn.nukkit.level.updater.util.tagupdater.CompoundTagUpdater.TagNamePredicate
import java.util.Deque
import cn.nukkit.level.updater.util.TagUtils
import cn.nukkit.nbt.tag.ByteTag
import cn.nukkit.nbt.tag.ShortTag
import cn.nukkit.nbt.tag.LongTag
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.nbt.tag.ByteArrayTag
import cn.nukkit.nbt.tag.IntArrayTag
import cn.nukkit.level.updater.util.OrderedUpdater
import cn.nukkit.level.updater.block.BlockStateUpdaterBase
import cn.nukkit.level.updater.block.BlockStateUpdater_1_10_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_12_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_13_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_14_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_15_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_16_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_16_210
import cn.nukkit.level.updater.block.BlockStateUpdater_1_17_30
import cn.nukkit.level.updater.block.BlockStateUpdater_1_17_40
import cn.nukkit.level.updater.block.BlockStateUpdater_1_18_10
import cn.nukkit.level.updater.block.BlockStateUpdater_1_18_30
import cn.nukkit.level.updater.block.BlockStateUpdater_1_19_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_19_20
import cn.nukkit.level.updater.block.BlockStateUpdater_1_19_70
import cn.nukkit.level.updater.block.BlockStateUpdater_1_19_80
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_10
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_30
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_40
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_50
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_60
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_70
import cn.nukkit.level.updater.block.BlockStateUpdater_1_20_80
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_0
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_10
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_20
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_30
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_40
import cn.nukkit.level.updater.block.BlockStateUpdater_1_21_60
import cn.nukkit.utils.JSONUtils
import lombok.RequiredArgsConstructor
import cn.nukkit.network.protocol.DataPacket
import java.util.Locale
import cn.nukkit.level.particle.GenericParticle
import cn.nukkit.utils.BlockColor
import cn.nukkit.network.protocol.LevelEventPacket
import cn.nukkit.entity.data.EntityDataMap
import cn.nukkit.entity.data.EntityFlag
import cn.nukkit.entity.data.EntityDataTypes
import cn.nukkit.network.protocol.SetEntityDataPacket
import cn.nukkit.network.protocol.RemoveEntityPacket
import cn.nukkit.network.protocol.PlayerListPacket
import cn.nukkit.level.particle.FloatingTextParticle
import cn.nukkit.network.protocol.AddPlayerPacket
import cn.nukkit.utils.SerializedImage
import cn.nukkit.level.particle.SpellParticle
import com.dfsek.terra.api.handle.ItemHandle
import cn.nukkit.level.generator.terra.PNXAdapter
import cn.nukkit.level.generator.terra.delegate.PNXEnchantmentDelegate
import com.dfsek.terra.api.handle.WorldHandle
import cn.nukkit.level.generator.terra.mappings.JeBlockState
import cn.nukkit.level.generator.terra.mappings.MappingRegistries
import cn.nukkit.level.generator.terra.handles.PNXWorldHandle
import cn.nukkit.level.generator.terra.delegate.PNXEntityType
import cn.nukkit.level.generator.terra.delegate.PNXBlockStateDelegate
import com.dfsek.terra.api.world.ServerWorld
import cn.nukkit.level.generator.terra.delegate.PNXServerWorld
import com.dfsek.terra.api.inventory.item.ItemMeta
import cn.nukkit.block.BlockFlowingWater
import com.dfsek.terra.api.inventory.ItemStack
import com.dfsek.terra.api.inventory.item.Damageable
import cn.nukkit.level.generator.terra.delegate.PNXItemDelegate
import cn.nukkit.level.generator.terra.delegate.PNXItemMeta
import com.dfsek.terra.api.world.chunk.generation.ProtoChunk
import cn.nukkit.level.generator.terra.delegate.PNXProtoChunk
import com.dfsek.terra.api.world.chunk.generation.ProtoWorld
import cn.nukkit.level.generator.terra.delegate.PNXEntity
import com.dfsek.terra.api.world.chunk.generation.ChunkGenerator
import com.dfsek.terra.api.world.biome.generation.BiomeProvider
import com.dfsek.terra.api.config.ConfigPack
import cn.nukkit.level.generator.terra.TerraGenerator
import cn.nukkit.level.generator.terra.delegate.PNXChunkDelegate
import cn.nukkit.level.generator.terra.delegate.PNXItemStack
import com.dfsek.terra.api.world.biome.PlatformBiome
import cn.nukkit.level.generator.terra.delegate.PNXBlockType
import cn.nukkit.level.generator.terra.mappings.RegistryLoader
import cn.nukkit.level.generator.terra.mappings.loader.BiomeRegistryLoader
import cn.nukkit.level.generator.terra.mappings.populator.BlockRegistryPopulator
import cn.nukkit.level.generator.terra.mappings.BlockMappings
import cn.nukkit.block.BlockFlowingLava
import cn.nukkit.block.property.CommonBlockProperties
import cn.nukkit.level.generator.terra.mappings.SimpleRegistry
import cn.nukkit.level.generator.terra.mappings.SimpleMappingRegistry
import cn.nukkit.level.generator.terra.mappings.MappingRegistry
import cn.nukkit.level.generator.terra.mappings.ArrayMappingRegistry
import cn.nukkit.level.generator.terra.mappings.MappedRegistry
import cn.nukkit.level.generator.terra.mappings.SimpleMappedRegistry
import cn.nukkit.level.generator.terra.mappings.AbstractMappedRegistry
import cn.nukkit.level.generator.terra.mappings.MappedMappingRegistry
import cn.nukkit.level.generator.terra.mappings.BiMappedRegistry
import cn.nukkit.level.generator.terra.mappings.SimpleBiMappedRegistry
import cn.nukkit.level.generator.terra.mappings.DoubleKeyMappedRegistry.MapPair
import cn.nukkit.level.generator.terra.mappings.VersionedMappingRegistry
import cn.nukkit.level.generator.terra.mappings.DoubleKeyMappedRegistry
import cn.nukkit.level.generator.terra.delegate.PNXBiomeDelegate
import com.dfsek.terra.AbstractPlatform
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.level.generator.terra.PNXPlatform
import com.dfsek.tectonic.api.loader.type.TypeLoader
import com.dfsek.tectonic.api.loader.ConfigLoader
import com.dfsek.tectonic.api.depth.DepthTracker
import cn.nukkit.level.generator.terra.handles.PNXItemHandle
import cn.nukkit.registry.RegisterException
import com.dfsek.terra.api.event.events.platform.PlatformInitializationEvent
import com.dfsek.terra.api.world.chunk.generation.util.GeneratorWrapper
import com.dfsek.terra.api.world.info.WorldProperties
import cn.nukkit.level.generator.terra.TerraGenerator.TerraStage
import cn.nukkit.level.generator.GenerateStage
import cn.nukkit.level.generator.ChunkGenerateContext
import cn.nukkit.level.generator.terra.delegate.PNXProtoWorld
import com.dfsek.terra.api.world.chunk.generation.stage.GenerationStage
import cn.nukkit.level.generator.``object`

