package cn.nukkit.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class BigDripleafTilt {
    FULL_TILT,

    NONE,

    PARTIAL_TILT,

    UNSTABLE
}
