package cn.nukkit.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class FlowerType {
    POPPY,
    ORCHID,
    ALLIUM,
    HOUSTONIA,
    TULIP_RED,
    TULIP_ORANGE,
    TULIP_WHITE,
    TULIP_PINK,
    OXEYE,
    CORNFLOWER,
    LILY_OF_THE_VALLEY,
}
