package cn.nukkit.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class MonsterEggStoneType {
    CHISELED_STONE_BRICK,

    COBBLESTONE,

    CRACKED_STONE_BRICK,

    MOSSY_STONE_BRICK,

    STONE,

    STONE_BRICK
}
