package cn.nukkit.block.property.enums

/**
 * @author daoge_cmd <br></br>
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project <br></br>
 */
enum class OldLogType {
    OAK,

    SPRUCE,

    BIRCH,

    JUNGLE
}
