package cn.nukkit.block.property.enums

/**
 * Automatically generated by `org.allaymc.codegen.VanillaBlockPropertyTypeGen` <br></br>
 * Allay Project
 *
 *
 *
 * @author daoge_cmd
 */
enum class StoneSlabType4 {
    MOSSY_STONE_BRICK,
    SMOOTH_QUARTZ,
    STONE,
    CUT_SANDSTONE,
    CUT_RED_SANDSTONE
}
