/**
 * 与物品栏相关的类.
 *
 *
 * Classes relevant to Inventory.
 */
package org.chorus.inventory

import cn.nukkit.entity.Entity.getDirectionVector
import cn.nukkit.entity.EntityHuman.getWidth
import cn.nukkit.entity.EntityHuman.getHeight
import cn.nukkit.entity.Entity.getLocator
import cn.nukkit.blockentity.BlockEntity.Companion.getDefaultCompound
import cn.nukkit.entity.Entity.getRiding
import cn.nukkit.entity.EntityHumanType.getInventory
import cn.nukkit.entity.EntityHumanType.getOffhandInventory
import cn.nukkit.entity.EntityHumanType.getEnderChestInventory
import cn.nukkit.entity.Entity.getServer
import cn.nukkit.event.Event.isCancelled
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.getReputation
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.addExperience
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.addGossip
import cn.nukkit.blockentity.BlockEntityBeacon.primaryPower
import cn.nukkit.blockentity.BlockEntityBeacon.secondaryPower
import cn.nukkit.entity.EntityHuman.getName
import cn.nukkit.blockentity.BlockEntity.setDirty
import cn.nukkit.blockentity.BlockEntity.block
import cn.nukkit.entity.Entity.setDataFlag
import cn.nukkit.entity.Entity.getId
import cn.nukkit.entity.IHuman.getLevel
import cn.nukkit.entity.IHuman.getEntity
import cn.nukkit.entity.Entity.getViewers
import cn.nukkit.entity.IHuman.getOffhandInventory
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.setTradingPlayer
import cn.nukkit.entity.mob.villagers.EntityVillagerV2.updateTrades
import cn.nukkit.blockentity.BlockEntityBrewingStand.updateBlock
import cn.nukkit.blockentity.BlockEntity.scheduleUpdate
import cn.nukkit.blockentity.BlockEntitySpawnable.spawnToAll
import cn.nukkit.blockentity.BlockEntityFurnace.calculateXpDrop
import cn.nukkit.blockentity.BlockEntityChest.realInventory
import cn.nukkit.entity.EntityEquipment.getHead
import cn.nukkit.entity.EntityEquipment.setHead
import cn.nukkit.entity.EntityEquipment.getChest
import cn.nukkit.entity.EntityEquipment.setChest
import cn.nukkit.entity.EntityEquipment.getLegs
import cn.nukkit.entity.EntityEquipment.setLegs
import cn.nukkit.entity.EntityEquipment.getFeet
import cn.nukkit.entity.EntityEquipment.setFeet
import cn.nukkit.entity.EntityEquipment.getMainHand
import cn.nukkit.entity.EntityEquipment.getOffHand
import cn.nukkit.entity.EntityEquipment.setMainHand
import cn.nukkit.entity.EntityEquipment.setOffHand
import cn.nukkit.entity.EntityEquipment.equip
import cn.nukkit.blockentity.BlockEntityEnderChest.name
import java.util.HashSet
import cn.nukkit.inventory.fake.FakeInventory
import cn.nukkit.event.inventory.ItemStackRequestActionEvent
import cn.nukkit.inventory.fake.FakeInventoryType
import cn.nukkit.inventory.BaseInventory
import cn.nukkit.inventory.InputInventory
import java.util.HashMap
import cn.nukkit.inventory.fake.FakeBlock
import cn.nukkit.network.protocol.types.itemstack.ContainerSlotType
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.network.protocol.ContainerOpenPacket
import cn.nukkit.network.protocol.ContainerClosePacket
import cn.nukkit.network.protocol.types.itemstack.request.action.ItemStackRequestAction
import cn.nukkit.network.protocol.types.itemstack.request.ItemStackRequestSlotData
import cn.nukkit.network.protocol.types.itemstack.request.action.TransferItemStackRequestAction
import cn.nukkit.network.protocol.types.itemstack.request.action.SwapAction
import cn.nukkit.network.protocol.types.itemstack.request.action.DropAction
import cn.nukkit.inventory.fake.SingleFakeBlock
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.block.BlockStructureBlock
import cn.nukkit.math.BlockVector3
import cn.nukkit.network.protocol.UpdateBlockPacket
import cn.nukkit.network.protocol.BlockEntityDataPacket
import cn.nukkit.blockentity.IStructBlock
import cn.nukkit.inventory.InventoryType
import cn.nukkit.block.BlockID
import cn.nukkit.inventory.fake.DoubleFakeBlock
import cn.nukkit.network.protocol.types.itemstack.response.ItemStackResponseContainer
import lombok.experimental.UtilityClass
import cn.nukkit.inventory.CraftingTableInventory
import cn.nukkit.inventory.request.ItemStackRequestActionProcessor
import cn.nukkit.network.protocol.types.itemstack.request.action.ItemStackRequestActionType
import cn.nukkit.inventory.request.ItemStackRequestContext
import cn.nukkit.inventory.request.ActionResponse
import cn.nukkit.event.player.PlayerDropItemEvent
import cn.nukkit.inventory.request.DropActionProcessor
import cn.nukkit.network.protocol.types.itemstack.response.ItemStackResponseSlot
import cn.nukkit.inventory.request.SwapActionProcessor
import cn.nukkit.inventory.request.TransferItemActionProcessor
import cn.nukkit.network.protocol.types.itemstack.request.action.TakeAction
import cn.nukkit.network.protocol.types.itemstack.request.action.PlaceAction
import cn.nukkit.network.protocol.types.itemstack.request.action.CreateAction
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftRecipeAction
import cn.nukkit.inventory.request.CreateActionProcessor
import cn.nukkit.recipe.Recipe
import cn.nukkit.inventory.CreativeOutputInventory
import cn.nukkit.network.protocol.types.itemstack.request.action.ConsumeAction
import cn.nukkit.inventory.request.ConsumeActionProcessor
import cn.nukkit.inventory.request.CraftRecipeActionProcessor
import cn.nukkit.network.protocol.types.itemstack.request.action.DestroyAction
import cn.nukkit.inventory.request.CraftResultDeprecatedActionProcessor
import cn.nukkit.inventory.request.DestroyActionProcessor
import cn.nukkit.network.protocol.types.itemstack.request.ItemStackRequest
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftLoomAction
import cn.nukkit.inventory.request.CraftLoomActionProcessor
import cn.nukkit.inventory.LoomInventory
import cn.nukkit.network.protocol.types.BannerPatternType
import cn.nukkit.item.ItemBannerPattern
import cn.nukkit.utils.DyeColor
import cn.nukkit.item.ItemDye
import cn.nukkit.item.ItemBanner
import cn.nukkit.network.protocol.types.BannerPattern
import cn.nukkit.network.protocol.types.itemstack.request.action.AutoCraftRecipeAction
import cn.nukkit.recipe.descriptor.ItemDescriptor
import cn.nukkit.event.inventory.CraftItemEvent
import cn.nukkit.recipe.descriptor.ItemTagDescriptor
import cn.nukkit.recipe.descriptor.DefaultDescriptor
import cn.nukkit.inventory.request.CraftRecipeAutoProcessor
import cn.nukkit.network.protocol.types.itemstack.request.action.MineBlockAction
import cn.nukkit.inventory.HumanInventory
import cn.nukkit.inventory.request.MineBlockActionProcessor
import cn.nukkit.network.protocol.InventorySlotPacket
import cn.nukkit.inventory.SpecialWindowId
import cn.nukkit.network.protocol.types.inventory.FullContainerName
import cn.nukkit.network.protocol.PlayerEnchantOptionsPacket
import cn.nukkit.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import cn.nukkit.event.inventory.EnchantItemEvent
import cn.nukkit.inventory.EnchantInventory
import cn.nukkit.utils.TradeRecipeBuildUtils
import cn.nukkit.nbt.NBTIO
import cn.nukkit.entity.mob.villagers.EntityVillagerV2
import cn.nukkit.recipe.SmithingTrimRecipe
import cn.nukkit.recipe.SmithingTransformRecipe
import cn.nukkit.inventory.SmithingInventory
import cn.nukkit.network.protocol.types.TrimPattern
import cn.nukkit.network.protocol.types.TrimData
import cn.nukkit.network.protocol.types.TrimMaterial
import cn.nukkit.inventory.request.CraftCreativeActionProcessor
import cn.nukkit.inventory.SoleInventory
import cn.nukkit.network.protocol.types.itemstack.request.action.BeaconPaymentAction
import cn.nukkit.inventory.request.BeaconPaymentActionProcessor
import cn.nukkit.inventory.BeaconInventory
import cn.nukkit.blockentity.BlockEntityBeacon
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftCreativeAction
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftRecipeOptionalAction
import cn.nukkit.inventory.request.CraftRecipeOptionalProcessor
import cn.nukkit.inventory.AnvilInventory
import cn.nukkit.inventory.CartographyTableInventory
import it.unimi.dsi.fastutil.objects.ObjectIntMutablePair
import java.util.LinkedHashSet
import cn.nukkit.level.Sound
import cn.nukkit.item.ItemFilledMap
import cn.nukkit.item.ItemID
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftGrindstoneAction
import cn.nukkit.inventory.request.CraftGrindstoneActionProcessor
import cn.nukkit.inventory.GrindstoneInventory
import cn.nukkit.event.inventory.GrindstoneEvent
import cn.nukkit.math.NukkitMath
import cn.nukkit.network.protocol.types.itemstack.request.action.CraftResultsDeprecatedAction
import cn.nukkit.recipe.RecipeType
import cn.nukkit.api.DoNotModify
import cn.nukkit.inventory.InventoryListener
import java.util.TreeMap
import cn.nukkit.event.entity.EntityInventoryChangeEvent
import cn.nukkit.event.inventory.InventoryOpenEvent
import cn.nukkit.event.inventory.InventoryCloseEvent
import cn.nukkit.network.protocol.InventoryContentPacket
import lombok.RequiredArgsConstructor
import cn.nukkit.block.BlockLoom
import cn.nukkit.block.BlockAnvil
import cn.nukkit.inventory.ContainerInventory
import cn.nukkit.inventory.CraftTypeInventory
import cn.nukkit.blockentity.BlockEntityChest
import cn.nukkit.inventory.BlockEntityInventoryNameable
import cn.nukkit.inventory.DoubleChestInventory
import cn.nukkit.network.protocol.BlockEventPacket
import cn.nukkit.block.BlockTrappedChest
import cn.nukkit.event.redstone.RedstoneUpdateEvent
import cn.nukkit.utils.RedstoneComponent
import cn.nukkit.utils.LevelException
import cn.nukkit.blockentity.BlockEntityNameable
import cn.nukkit.entity.mob.animal.EntityHorse
import cn.nukkit.entity.data.EntityFlag
import cn.nukkit.network.protocol.LevelSoundEventPacket
import cn.nukkit.network.protocol.MobArmorEquipmentPacket
import cn.nukkit.network.protocol.UpdateEquipmentPacket
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.inventory.HorseInventory
import java.io.IOException
import cn.nukkit.entity.IHuman
import cn.nukkit.inventory.InventorySlice
import cn.nukkit.event.player.PlayerItemHeldEvent
import cn.nukkit.network.protocol.MobEquipmentPacket
import cn.nukkit.item.ItemArmor
import cn.nukkit.level.vibration.VibrationType
import cn.nukkit.event.entity.EntityArmorChangeEvent
import cn.nukkit.network.protocol.PlayerArmorDamagePacket
import cn.nukkit.network.protocol.PlayerArmorDamagePacket.PlayerArmorDamageFlag
import cn.nukkit.blockentity.BlockEntityBarrel
import cn.nukkit.block.BlockBarrel
import cn.nukkit.blockentity.BlockEntityHopper
import cn.nukkit.blockentity.BlockEntityFurnace
import cn.nukkit.inventory.SmeltingInventory
import cn.nukkit.blockentity.BlockEntityBrewingStand
import cn.nukkit.blockentity.BlockEntityDropper
import cn.nukkit.inventory.EjectableInventory
import cn.nukkit.blockentity.BlockEntityEnchantTable
import cn.nukkit.item.enchantment.EnchantmentHelper
import cn.nukkit.event.player.PlayerEnchantOptionsRequestEvent
import cn.nukkit.blockentity.BlockEntityCampfire
import cn.nukkit.block.BlockSmithingTable
import cn.nukkit.entity.item.EntityChestBoat
import cn.nukkit.AdventureSettings
import cn.nukkit.blockentity.BlockEntityDispenser
import cn.nukkit.block.BlockGrindstone
import cn.nukkit.blockentity.BlockEntityShulkerBox
import cn.nukkit.tags.BlockTags
import cn.nukkit.inventory.ChestInventory
import cn.nukkit.inventory.EntityArmorInventory
import cn.nukkit.block.BlockStonecutterBlock
import cn.nukkit.blockentity.BlockEntityStructBlock
import cn.nukkit.blockentity.BlockEntityCommandBlock
import cn.nukkit.entity.EntityEquipment
import cn.nukkit.block.BlockCraftingTable
import cn.nukkit.entity.item.EntityChestMinecart
import cn.nukkit.entity.item.EntityHopperMinecart
import cn.nukkit.inventory.EntityEquipmentInventory
import cn.nukkit.blockentity.BlockEntityEnderChest
import cn.nukkit.block.BlockCartographyTable
import cn.nukkit.inventory.InventoryNameable

