/**
 * 与物品栏相关的类.
 *
 *
 * Classes relevant to Inventory.
 */
package org.chorus.inventory

import org.chorus.entity.Entity.getDirectionVector
import org.chorus.entity.EntityHuman.getWidth
import org.chorus.entity.EntityHuman.getHeight
import org.chorus.entity.Entity.getLocator
import org.chorus.blockentity.BlockEntity.Companion.getDefaultCompound
import org.chorus.entity.Entity.getRiding
import org.chorus.entity.EntityHumanType.getInventory
import org.chorus.entity.EntityHumanType.getOffhandInventory
import org.chorus.entity.EntityHumanType.getEnderChestInventory
import org.chorus.entity.Entity.getServer
import org.chorus.event.Event.isCancelled
import org.chorus.entity.mob.villagers.EntityVillagerV2.getReputation
import org.chorus.entity.mob.villagers.EntityVillagerV2.addExperience
import org.chorus.entity.mob.villagers.EntityVillagerV2.addGossip
import org.chorus.blockentity.BlockEntityBeacon.primaryPower
import org.chorus.blockentity.BlockEntityBeacon.secondaryPower
import org.chorus.entity.EntityHuman.getName
import org.chorus.blockentity.BlockEntity.setDirty
import org.chorus.blockentity.BlockEntity.block
import org.chorus.entity.Entity.setDataFlag
import org.chorus.entity.Entity.getId
import org.chorus.entity.IHuman.getLevel
import org.chorus.entity.IHuman.getEntity
import org.chorus.entity.Entity.getViewers
import org.chorus.entity.IHuman.getOffhandInventory
import org.chorus.entity.mob.villagers.EntityVillagerV2.setTradingPlayer
import org.chorus.entity.mob.villagers.EntityVillagerV2.updateTrades
import org.chorus.blockentity.BlockEntityBrewingStand.updateBlock
import org.chorus.blockentity.BlockEntity.scheduleUpdate
import org.chorus.blockentity.BlockEntitySpawnable.spawnToAll
import org.chorus.blockentity.BlockEntityFurnace.calculateXpDrop
import org.chorus.blockentity.BlockEntityChest.realInventory
import org.chorus.entity.EntityEquipment.getHead
import org.chorus.entity.EntityEquipment.setHead
import org.chorus.entity.EntityEquipment.getChest
import org.chorus.entity.EntityEquipment.setChest
import org.chorus.entity.EntityEquipment.getLegs
import org.chorus.entity.EntityEquipment.setLegs
import org.chorus.entity.EntityEquipment.getFeet
import org.chorus.entity.EntityEquipment.setFeet
import org.chorus.entity.EntityEquipment.getMainHand
import org.chorus.entity.EntityEquipment.getOffHand
import org.chorus.entity.EntityEquipment.setMainHand
import org.chorus.entity.EntityEquipment.setOffHand
import org.chorus.entity.EntityEquipment.equip
import org.chorus.blockentity.BlockEntityEnderChest.name
import java.util.HashSet
import org.chorus.inventory.fake.FakeInventory
import org.chorus.event.inventory.ItemStackRequestActionEvent
import org.chorus.inventory.fake.FakeInventoryType
import org.chorus.inventory.BaseInventory
import org.chorus.inventory.InputInventory
import java.util.HashMap
import org.chorus.inventory.fake.FakeBlock
import org.chorus.network.protocol.types.itemstack.ContainerSlotType
import org.chorus.plugin.InternalPlugin
import org.chorus.network.protocol.ContainerOpenPacket
import org.chorus.network.protocol.ContainerClosePacket
import org.chorus.network.protocol.types.itemstack.request.action.ItemStackRequestAction
import org.chorus.network.protocol.types.itemstack.request.ItemStackRequestSlotData
import org.chorus.network.protocol.types.itemstack.request.action.TransferItemStackRequestAction
import org.chorus.network.protocol.types.itemstack.request.action.SwapAction
import org.chorus.network.protocol.types.itemstack.request.action.DropAction
import org.chorus.inventory.fake.SingleFakeBlock
import org.chorus.nbt.tag.CompoundTag
import org.chorus.block.BlockStructureBlock
import org.chorus.math.BlockVector3
import org.chorus.network.protocol.UpdateBlockPacket
import org.chorus.network.protocol.BlockEntityDataPacket
import org.chorus.blockentity.IStructBlock
import org.chorus.inventory.InventoryType
import org.chorus.block.BlockID
import org.chorus.inventory.fake.DoubleFakeBlock
import org.chorus.network.protocol.types.itemstack.response.ItemStackResponseContainer
import lombok.experimental.UtilityClass
import org.chorus.inventory.CraftingTableInventory
import org.chorus.inventory.request.ItemStackRequestActionProcessor
import org.chorus.network.protocol.types.itemstack.request.action.ItemStackRequestActionType
import org.chorus.inventory.request.ItemStackRequestContext
import org.chorus.inventory.request.ActionResponse
import org.chorus.event.player.PlayerDropItemEvent
import org.chorus.inventory.request.DropActionProcessor
import org.chorus.network.protocol.types.itemstack.response.ItemStackResponseSlot
import org.chorus.inventory.request.SwapActionProcessor
import org.chorus.inventory.request.TransferItemActionProcessor
import org.chorus.network.protocol.types.itemstack.request.action.TakeAction
import org.chorus.network.protocol.types.itemstack.request.action.PlaceAction
import org.chorus.network.protocol.types.itemstack.request.action.CreateAction
import org.chorus.network.protocol.types.itemstack.request.action.CraftRecipeAction
import org.chorus.inventory.request.CreateActionProcessor
import org.chorus.recipe.Recipe
import org.chorus.inventory.CreativeOutputInventory
import org.chorus.network.protocol.types.itemstack.request.action.ConsumeAction
import org.chorus.inventory.request.ConsumeActionProcessor
import org.chorus.inventory.request.CraftRecipeActionProcessor
import org.chorus.network.protocol.types.itemstack.request.action.DestroyAction
import org.chorus.inventory.request.CraftResultDeprecatedActionProcessor
import org.chorus.inventory.request.DestroyActionProcessor
import org.chorus.network.protocol.types.itemstack.request.ItemStackRequest
import org.chorus.network.protocol.types.itemstack.request.action.CraftLoomAction
import org.chorus.inventory.request.CraftLoomActionProcessor
import org.chorus.inventory.LoomInventory
import org.chorus.network.protocol.types.BannerPatternType
import org.chorus.item.ItemBannerPattern
import org.chorus.utils.DyeColor
import org.chorus.item.ItemDye
import org.chorus.item.ItemBanner
import org.chorus.network.protocol.types.BannerPattern
import org.chorus.network.protocol.types.itemstack.request.action.AutoCraftRecipeAction
import org.chorus.recipe.descriptor.ItemDescriptor
import org.chorus.event.inventory.CraftItemEvent
import org.chorus.recipe.descriptor.ItemTagDescriptor
import org.chorus.recipe.descriptor.DefaultDescriptor
import org.chorus.inventory.request.CraftRecipeAutoProcessor
import org.chorus.network.protocol.types.itemstack.request.action.MineBlockAction
import org.chorus.inventory.HumanInventory
import org.chorus.inventory.request.MineBlockActionProcessor
import org.chorus.network.protocol.InventorySlotPacket
import org.chorus.inventory.SpecialWindowId
import org.chorus.network.protocol.types.inventory.FullContainerName
import org.chorus.network.protocol.PlayerEnchantOptionsPacket
import org.chorus.network.protocol.PlayerEnchantOptionsPacket.EnchantOptionData
import org.chorus.event.inventory.EnchantItemEvent
import org.chorus.inventory.EnchantInventory
import org.chorus.utils.TradeRecipeBuildUtils
import org.chorus.nbt.NBTIO
import org.chorus.entity.mob.villagers.EntityVillagerV2
import org.chorus.recipe.SmithingTrimRecipe
import org.chorus.recipe.SmithingTransformRecipe
import org.chorus.inventory.SmithingInventory
import org.chorus.network.protocol.types.TrimPattern
import org.chorus.network.protocol.types.TrimData
import org.chorus.network.protocol.types.TrimMaterial
import org.chorus.inventory.request.CraftCreativeActionProcessor
import org.chorus.inventory.SoleInventory
import org.chorus.network.protocol.types.itemstack.request.action.BeaconPaymentAction
import org.chorus.inventory.request.BeaconPaymentActionProcessor
import org.chorus.inventory.BeaconInventory
import org.chorus.blockentity.BlockEntityBeacon
import org.chorus.network.protocol.types.itemstack.request.action.CraftCreativeAction
import org.chorus.network.protocol.types.itemstack.request.action.CraftRecipeOptionalAction
import org.chorus.inventory.request.CraftRecipeOptionalProcessor
import org.chorus.inventory.AnvilInventory
import org.chorus.inventory.CartographyTableInventory
import it.unimi.dsi.fastutil.objects.ObjectIntMutablePair
import java.util.LinkedHashSet
import org.chorus.level.Sound
import org.chorus.item.ItemFilledMap
import org.chorus.item.ItemID
import org.chorus.network.protocol.types.itemstack.request.action.CraftGrindstoneAction
import org.chorus.inventory.request.CraftGrindstoneActionProcessor
import org.chorus.inventory.GrindstoneInventory
import org.chorus.event.inventory.GrindstoneEvent
import org.chorus.math.NukkitMath
import org.chorus.network.protocol.types.itemstack.request.action.CraftResultsDeprecatedAction
import org.chorus.recipe.RecipeType
import org.chorus.api.DoNotModify
import org.chorus.inventory.InventoryListener
import java.util.TreeMap
import org.chorus.event.entity.EntityInventoryChangeEvent
import org.chorus.event.inventory.InventoryOpenEvent
import org.chorus.event.inventory.InventoryCloseEvent
import org.chorus.network.protocol.InventoryContentPacket
import lombok.RequiredArgsConstructor
import org.chorus.block.BlockLoom
import org.chorus.block.BlockAnvil
import org.chorus.inventory.ContainerInventory
import org.chorus.inventory.CraftTypeInventory
import org.chorus.blockentity.BlockEntityChest
import org.chorus.inventory.BlockEntityInventoryNameable
import org.chorus.inventory.DoubleChestInventory
import org.chorus.network.protocol.BlockEventPacket
import org.chorus.block.BlockTrappedChest
import org.chorus.event.redstone.RedstoneUpdateEvent
import org.chorus.utils.RedstoneComponent
import org.chorus.utils.LevelException
import org.chorus.blockentity.BlockEntityNameable
import org.chorus.entity.mob.animal.EntityHorse
import org.chorus.entity.data.EntityFlag
import org.chorus.network.protocol.LevelSoundEventPacket
import org.chorus.network.protocol.MobArmorEquipmentPacket
import org.chorus.network.protocol.UpdateEquipmentPacket
import org.chorus.nbt.tag.ListTag
import org.chorus.inventory.HorseInventory
import java.io.IOException
import org.chorus.entity.IHuman
import org.chorus.inventory.InventorySlice
import org.chorus.event.player.PlayerItemHeldEvent
import org.chorus.network.protocol.MobEquipmentPacket
import org.chorus.item.ItemArmor
import org.chorus.level.vibration.VibrationType
import org.chorus.event.entity.EntityArmorChangeEvent
import org.chorus.network.protocol.PlayerArmorDamagePacket
import org.chorus.network.protocol.PlayerArmorDamagePacket.PlayerArmorDamageFlag
import org.chorus.blockentity.BlockEntityBarrel
import org.chorus.block.BlockBarrel
import org.chorus.blockentity.BlockEntityHopper
import org.chorus.blockentity.BlockEntityFurnace
import org.chorus.inventory.SmeltingInventory
import org.chorus.blockentity.BlockEntityBrewingStand
import org.chorus.blockentity.BlockEntityDropper
import org.chorus.inventory.EjectableInventory
import org.chorus.blockentity.BlockEntityEnchantTable
import org.chorus.item.enchantment.EnchantmentHelper
import org.chorus.event.player.PlayerEnchantOptionsRequestEvent
import org.chorus.blockentity.BlockEntityCampfire
import org.chorus.block.BlockSmithingTable
import org.chorus.entity.item.EntityChestBoat
import org.chorus.AdventureSettings
import org.chorus.blockentity.BlockEntityDispenser
import org.chorus.block.BlockGrindstone
import org.chorus.blockentity.BlockEntityShulkerBox
import org.chorus.tags.BlockTags
import org.chorus.inventory.ChestInventory
import org.chorus.inventory.EntityArmorInventory
import org.chorus.block.BlockStonecutterBlock
import org.chorus.blockentity.BlockEntityStructBlock
import org.chorus.blockentity.BlockEntityCommandBlock
import org.chorus.entity.EntityEquipment
import org.chorus.block.BlockCraftingTable
import org.chorus.entity.item.EntityChestMinecart
import org.chorus.entity.item.EntityHopperMinecart
import org.chorus.inventory.EntityEquipmentInventory
import org.chorus.blockentity.BlockEntityEnderChest
import org.chorus.block.BlockCartographyTable
import org.chorus.inventory.InventoryNameable

