/**
 * 与方块实体(例如TNT方块爆炸时的实体)相关的类
 *
 *
 * Classes relevant to block entity,such as entity when TNT blocks explode
 */
package org.chorus.blockentity

import org.chorus.level.format.IChunk
import org.chorus.nbt.tag.CompoundTag
import org.chorus.blockentity.BlockEntityID
import org.chorus.utils.ChunkException
import org.chorus.plugin.InternalPlugin
import org.chorus.blockentity.ICommandBlock.CommandBlockTrigger
import org.chorus.nbt.tag.ListTag
import org.chorus.nbt.tag.StringTag
import org.chorus.blockentity.ICommandBlock
import org.chorus.blockentity.BlockEntitySpawnable
import org.chorus.block.BlockID
import org.chorus.utils.DyeColor
import org.chorus.nbt.tag.ByteTag
import org.chorus.nbt.tag.IntTag
import org.chorus.level.Sound
import org.chorus.blockentity.BlockEntitySign
import org.chorus.block.BlockStandingSign
import org.chorus.utils.BlockColor
import org.chorus.event.block.SignChangeEvent
import org.chorus.blockentity.BlockEntitySpawnableContainer
import org.chorus.inventory.DoubleChestInventory
import org.chorus.inventory.ContainerInventory
import org.chorus.inventory.ChestInventory
import org.chorus.inventory.BaseInventory
import org.chorus.blockentity.BlockEntityChest
import org.chorus.math.NukkitMath
import org.chorus.block.BlockHead
import org.chorus.network.protocol.types.BannerPattern
import org.chorus.inventory.BarrelInventory
import org.chorus.blockentity.BlockEntityInventoryHolder
import org.chorus.inventory.BeaconInventory
import org.chorus.blockentity.BlockEntityBeacon
import org.chorus.block.BlockHopper.IHopper
import org.chorus.inventory.HopperInventory
import org.chorus.math.AxisAlignedBB
import org.chorus.math.BlockVector3
import org.chorus.math.SimpleAxisAlignedBB
import org.chorus.block.BlockHopper
import org.chorus.nbt.NBTIO
import org.chorus.math.BlockFace
import org.chorus.event.block.HopperSearchItemEvent
import org.chorus.block.BlockComposter
import org.chorus.event.inventory.InventoryMoveItemEvent
import java.util.HashSet
import org.chorus.block.property.type.IntPropertyType
import org.chorus.block.property.CommonBlockProperties
import org.chorus.blockentity.BlockEntityHopper
import org.chorus.blockentity.BlockEntityFurnace
import org.chorus.inventory.SmeltingInventory
import org.chorus.blockentity.BlockEntityBrewingStand
import org.chorus.inventory.BrewingInventory
import org.chorus.item.ItemPotion
import org.chorus.item.ItemSplashPotion
import org.chorus.inventory.SmokerInventory
import org.chorus.recipe.SmeltingRecipe
import org.chorus.blockentity.BlockEntityBeehive.Occupant
import org.chorus.block.BlockBeehive
import org.chorus.entity.mob.animal.EntityBee
import org.chorus.block.BlockLiquid
import org.chorus.blockentity.BlockEntityBeehive
import org.chorus.nbt.tag.FloatTag
import org.chorus.event.block.ConduitDeactivateEvent
import org.chorus.event.block.ConduitActivateEvent
import org.chorus.event.entity.EntityDamageByBlockEvent
import org.chorus.event.entity.EntityDamageEvent
import org.chorus.entity.mob.monster.EntityMonster
import org.chorus.tags.BiomeTags
import org.chorus.tags.BlockTags
import org.chorus.blockentity.BlockEntityConduit
import org.chorus.blockentity.BlockEntityEjectable
import org.chorus.inventory.DropperInventory
import org.chorus.inventory.FurnaceTypeInventory
import org.chorus.event.inventory.FurnaceBurnEvent
import org.chorus.item.ItemLavaBucket
import org.chorus.event.inventory.FurnaceSmeltEvent
import org.chorus.network.protocol.ContainerSetDataPacket
import org.chorus.inventory.InventorySlice
import org.chorus.item.ItemMusicDisc
import org.chorus.network.protocol.PlaySoundPacket
import org.chorus.network.protocol.StopSoundPacket
import org.chorus.item.ItemBlock
import org.chorus.block.BlockAir
import org.chorus.utils.RedstoneComponent
import org.chorus.inventory.CampfireInventory
import org.chorus.recipe.CampfireRecipe
import org.chorus.block.BlockCampfire
import org.chorus.event.inventory.CampfireSmeltEvent
import org.chorus.block.BlockCauldron

import org.chorus.inventory.DispenserInventory
import org.chorus.inventory.EjectableInventory
import org.chorus.block.BlockFrame
import org.chorus.event.block.ItemFrameUseEvent
import org.chorus.entity.item.EntityItem
import org.chorus.network.protocol.LevelEventPacket
import java.util.OptionalInt
import java.io.IOException
import org.chorus.positiontracking.PositionTrackingService
import org.chorus.positiontracking.PositionTracking
import org.chorus.blockentity.BlockEntityLodestone
import org.chorus.blockentity.BlockEntityMovingBlock
import org.chorus.event.entity.EntityMoveByPistonEvent
import org.chorus.blockentity.BlockEntityPistonArm
import org.chorus.block.BlockPistonArmCollision
import org.chorus.utils.Faceable
import org.chorus.network.protocol.BlockEntityDataPacket
import org.chorus.block.BlockRedstoneComparator
import org.chorus.blockentity.BlockEntityNameable
import org.chorus.blockentity.BlockEntityEndGateway
import org.chorus.entity.projectile.throwable.EntityEnderPearl
import org.chorus.event.player.PlayerTeleportEvent.TeleportCause
import org.chorus.network.protocol.BlockEventPacket
import org.chorus.block.BlockBedrock
import org.chorus.blockentity.BlockEntityMobSpawner
import org.chorus.level.GameRule
import org.chorus.entity.mob.animal.EntityAnimal
import org.chorus.block.BlockFlowable
import org.chorus.event.entity.CreatureSpawnEvent
import org.chorus.inventory.ShulkerBoxInventory
import org.chorus.block.BlockUndyedShulkerBox
import org.chorus.level.vibration.VibrationListener
import org.chorus.block.BlockSculkSensor
import org.chorus.blockentity.IStructBlock
import org.chorus.network.protocol.types.StructureAnimationMode
import org.chorus.block.property.enums.StructureBlockType
import org.chorus.network.protocol.types.StructureMirror
import org.chorus.network.protocol.types.StructureRedstoneSaveMode
import org.chorus.network.protocol.types.StructureRotation
import org.chorus.inventory.StructBlockInventory
import org.chorus.network.protocol.StructureBlockUpdatePacket
import org.chorus.network.protocol.types.StructureEditorData
import org.chorus.inventory.BlastFurnaceInventory
import org.chorus.event.inventory.StartBrewEvent
import org.chorus.event.inventory.BrewEvent
import org.chorus.recipe.MixRecipe
import org.chorus.recipe.ContainerRecipe
import org.chorus.item.ItemID
import org.chorus.block.BlockBrewingStand
import org.chorus.block.property.type.BooleanPropertyType
import org.chorus.permission.PermissibleBase
import org.chorus.inventory.CommandBlockInventory
import org.chorus.block.BlockCommandBlock
import org.chorus.block.BlockChainCommandBlock
import org.chorus.event.command.CommandBlockExecuteEvent
import org.chorus.blockentity.BlockEntityCommandBlock
import org.chorus.permission.PermissionAttachment
import org.chorus.permission.PermissionAttachmentInfo
import org.chorus.lang.TranslationContainer
import org.chorus.lang.TextContainer
import org.chorus.permission.Permissible
import org.chorus.command.ConsoleCommandSender
import org.chorus.lang.CommandOutputContainer
import org.chorus.network.protocol.types.CommandOutputMessage
import org.chorus.inventory.EnchantInventory
import org.chorus.entity.mob.monster.EntityCreaking
import org.chorus.block.BlockCreakingHeart
import org.chorus.blockentity.BlockEntityItemFrame
import org.chorus.block.property.enums.NetherReactorState
import org.chorus.math.MathHelper
import org.chorus.block.BlockDaylightDetector
import org.chorus.block.BlockChiseledBookshelf
import kotlin.math.pow
import org.chorus.api.DoNotModify
import org.chorus.blockentity.BlockEntityChiseledBookshelf
import org.chorus.block.BlockCalibratedSculkSensor

