/**
 * 与方块实体(例如TNT方块爆炸时的实体)相关的类
 *
 *
 * Classes relevant to block entity,such as entity when TNT blocks explode
 */
package org.chorus.blockentity

import cn.nukkit.level.format.IChunk
import cn.nukkit.nbt.tag.CompoundTag
import cn.nukkit.blockentity.BlockEntityID
import cn.nukkit.utils.ChunkException
import cn.nukkit.plugin.InternalPlugin
import cn.nukkit.blockentity.ICommandBlock.CommandBlockTrigger
import cn.nukkit.nbt.tag.ListTag
import cn.nukkit.nbt.tag.StringTag
import cn.nukkit.blockentity.ICommandBlock
import cn.nukkit.blockentity.BlockEntitySpawnable
import cn.nukkit.block.BlockID
import cn.nukkit.utils.DyeColor
import cn.nukkit.nbt.tag.ByteTag
import cn.nukkit.nbt.tag.IntTag
import cn.nukkit.level.Sound
import cn.nukkit.blockentity.BlockEntitySign
import cn.nukkit.block.BlockStandingSign
import cn.nukkit.utils.BlockColor
import cn.nukkit.event.block.SignChangeEvent
import cn.nukkit.blockentity.BlockEntitySpawnableContainer
import cn.nukkit.inventory.DoubleChestInventory
import cn.nukkit.inventory.ContainerInventory
import cn.nukkit.inventory.ChestInventory
import cn.nukkit.inventory.BaseInventory
import cn.nukkit.blockentity.BlockEntityChest
import cn.nukkit.math.NukkitMath
import cn.nukkit.block.BlockHead
import cn.nukkit.network.protocol.types.BannerPattern
import cn.nukkit.inventory.BarrelInventory
import cn.nukkit.blockentity.BlockEntityInventoryHolder
import cn.nukkit.inventory.BeaconInventory
import cn.nukkit.blockentity.BlockEntityBeacon
import cn.nukkit.block.BlockHopper.IHopper
import cn.nukkit.inventory.HopperInventory
import cn.nukkit.math.AxisAlignedBB
import cn.nukkit.math.BlockVector3
import cn.nukkit.math.SimpleAxisAlignedBB
import cn.nukkit.block.BlockHopper
import cn.nukkit.nbt.NBTIO
import cn.nukkit.math.BlockFace
import cn.nukkit.event.block.HopperSearchItemEvent
import cn.nukkit.block.BlockComposter
import cn.nukkit.event.inventory.InventoryMoveItemEvent
import java.util.HashSet
import cn.nukkit.block.property.type.IntPropertyType
import cn.nukkit.block.property.CommonBlockProperties
import cn.nukkit.blockentity.BlockEntityHopper
import cn.nukkit.blockentity.BlockEntityFurnace
import cn.nukkit.inventory.SmeltingInventory
import cn.nukkit.blockentity.BlockEntityBrewingStand
import cn.nukkit.inventory.BrewingInventory
import cn.nukkit.item.ItemPotion
import cn.nukkit.item.ItemSplashPotion
import cn.nukkit.inventory.SmokerInventory
import cn.nukkit.recipe.SmeltingRecipe
import cn.nukkit.blockentity.BlockEntityBeehive.Occupant
import cn.nukkit.block.BlockBeehive
import cn.nukkit.entity.mob.animal.EntityBee
import cn.nukkit.block.BlockLiquid
import cn.nukkit.blockentity.BlockEntityBeehive
import cn.nukkit.nbt.tag.FloatTag
import cn.nukkit.event.block.ConduitDeactivateEvent
import cn.nukkit.event.block.ConduitActivateEvent
import cn.nukkit.event.entity.EntityDamageByBlockEvent
import cn.nukkit.event.entity.EntityDamageEvent
import cn.nukkit.entity.mob.monster.EntityMonster
import cn.nukkit.tags.BiomeTags
import cn.nukkit.tags.BlockTags
import cn.nukkit.blockentity.BlockEntityConduit
import cn.nukkit.blockentity.BlockEntityEjectable
import cn.nukkit.inventory.DropperInventory
import cn.nukkit.inventory.FurnaceTypeInventory
import cn.nukkit.event.inventory.FurnaceBurnEvent
import cn.nukkit.item.ItemLavaBucket
import cn.nukkit.event.inventory.FurnaceSmeltEvent
import cn.nukkit.network.protocol.ContainerSetDataPacket
import cn.nukkit.inventory.InventorySlice
import cn.nukkit.item.ItemMusicDisc
import cn.nukkit.network.protocol.PlaySoundPacket
import cn.nukkit.network.protocol.StopSoundPacket
import cn.nukkit.item.ItemBlock
import cn.nukkit.block.BlockAir
import cn.nukkit.utils.RedstoneComponent
import cn.nukkit.inventory.CampfireInventory
import cn.nukkit.recipe.CampfireRecipe
import cn.nukkit.block.BlockCampfire
import cn.nukkit.event.inventory.CampfireSmeltEvent
import cn.nukkit.block.BlockCauldron
import lombok.RequiredArgsConstructor
import cn.nukkit.inventory.DispenserInventory
import cn.nukkit.inventory.EjectableInventory
import cn.nukkit.block.BlockFrame
import cn.nukkit.event.block.ItemFrameUseEvent
import cn.nukkit.entity.item.EntityItem
import cn.nukkit.network.protocol.LevelEventPacket
import java.util.OptionalInt
import java.io.IOException
import cn.nukkit.positiontracking.PositionTrackingService
import cn.nukkit.positiontracking.PositionTracking
import cn.nukkit.blockentity.BlockEntityLodestone
import cn.nukkit.blockentity.BlockEntityMovingBlock
import cn.nukkit.event.entity.EntityMoveByPistonEvent
import cn.nukkit.blockentity.BlockEntityPistonArm
import cn.nukkit.block.BlockPistonArmCollision
import cn.nukkit.utils.Faceable
import cn.nukkit.network.protocol.BlockEntityDataPacket
import cn.nukkit.block.BlockRedstoneComparator
import cn.nukkit.blockentity.BlockEntityNameable
import cn.nukkit.blockentity.BlockEntityEndGateway
import cn.nukkit.entity.projectile.throwable.EntityEnderPearl
import cn.nukkit.event.player.PlayerTeleportEvent.TeleportCause
import cn.nukkit.network.protocol.BlockEventPacket
import cn.nukkit.block.BlockBedrock
import cn.nukkit.blockentity.BlockEntityMobSpawner
import cn.nukkit.level.GameRule
import cn.nukkit.entity.mob.animal.EntityAnimal
import cn.nukkit.block.BlockFlowable
import cn.nukkit.event.entity.CreatureSpawnEvent
import cn.nukkit.inventory.ShulkerBoxInventory
import cn.nukkit.block.BlockUndyedShulkerBox
import cn.nukkit.level.vibration.VibrationListener
import cn.nukkit.block.BlockSculkSensor
import cn.nukkit.blockentity.IStructBlock
import cn.nukkit.network.protocol.types.StructureAnimationMode
import cn.nukkit.block.property.enums.StructureBlockType
import cn.nukkit.network.protocol.types.StructureMirror
import cn.nukkit.network.protocol.types.StructureRedstoneSaveMode
import cn.nukkit.network.protocol.types.StructureRotation
import cn.nukkit.inventory.StructBlockInventory
import cn.nukkit.network.protocol.StructureBlockUpdatePacket
import cn.nukkit.network.protocol.types.StructureEditorData
import cn.nukkit.inventory.BlastFurnaceInventory
import cn.nukkit.event.inventory.StartBrewEvent
import cn.nukkit.event.inventory.BrewEvent
import cn.nukkit.recipe.MixRecipe
import cn.nukkit.recipe.ContainerRecipe
import cn.nukkit.item.ItemID
import cn.nukkit.block.BlockBrewingStand
import cn.nukkit.block.property.type.BooleanPropertyType
import cn.nukkit.permission.PermissibleBase
import cn.nukkit.inventory.CommandBlockInventory
import cn.nukkit.block.BlockCommandBlock
import cn.nukkit.block.BlockChainCommandBlock
import cn.nukkit.event.command.CommandBlockExecuteEvent
import cn.nukkit.blockentity.BlockEntityCommandBlock
import cn.nukkit.permission.PermissionAttachment
import cn.nukkit.permission.PermissionAttachmentInfo
import cn.nukkit.lang.TranslationContainer
import cn.nukkit.lang.TextContainer
import cn.nukkit.permission.Permissible
import cn.nukkit.command.ConsoleCommandSender
import cn.nukkit.lang.CommandOutputContainer
import cn.nukkit.network.protocol.types.CommandOutputMessage
import cn.nukkit.inventory.EnchantInventory
import cn.nukkit.entity.mob.monster.EntityCreaking
import cn.nukkit.block.BlockCreakingHeart
import cn.nukkit.blockentity.BlockEntityItemFrame
import cn.nukkit.block.property.enums.NetherReactorState
import cn.nukkit.math.MathHelper
import cn.nukkit.block.BlockDaylightDetector
import cn.nukkit.block.BlockChiseledBookshelf
import kotlin.math.pow
import cn.nukkit.api.DoNotModify
import cn.nukkit.blockentity.BlockEntityChiseledBookshelf
import cn.nukkit.block.BlockCalibratedSculkSensor

